# Chapter Eleven

Inevitably, the ladies that Aunt Hattie was hosting began to make inquiries---not so much about Lloyd, but about her membership (or lack thereof) in a church. Where was she baptized? Where did she get married? It was a real problem because Aunt Hattie and Uncle Frank only went to church for weddings, funerals, and the occasional Christmas or Easter service. One time, Hattie claimed that she was a Presbyterian---it was the least controversial church she could think of. The Lutheran Church was for the Norwegians and Germans, and the Catholic Church was for the Irish. She had nothing against the Mormons, but she wasn't about to claim that she was one of them; it would have been social suicide. 

There was a Presbyterian church close to Lila's house. As a demonstration of her faith, Aunt Hattie decided that Veda and Lila should get baptized. Lila's mother pointed out that they had been baptized in the local church when they were babies, but Hattie said it was fine---it was common for people to get baptized again once they joined a church in the city. She would buy new dresses for the girls; afterward, they would have a lovely party at her house. Lila's parents were not immediately convinced, but Veda desperately wanted to go shopping with Aunt Hattie. She quietly asked their mother about it every few days until finally, she threw up her hands and said, "Fine, I guess if you really want to get baptized again you can."

On the day of the shopping trip, Uncle Frank arrived in his car to pick up the girls. Aunt Hattie had invited their mother, but she decided that she couldn't leave the younger boys without supervision. Veda and Lila were secretly thrilled&hellip;what an adventure! Uncle Frank drove them downtown and dropped them off in front of Doerflingers, which was Hattie's favorite department store. The savings from her years of work allowed her to shop in ways that Hazel could not have imagined. Lila's astonishment began when they went through the revolving door. Aunt Hattie said, "Come along dear." In her breathless state, Lila had stopped walking and was blocking the door for other customers. The building was five stories tall with an atrium in the middle; the roof was supported by enormous columns that were clad with dark granite. It was so highly polished that as they walked by, Lila could see a bit of her reflection in the stone. Their footsteps echoed on the tile floor, which had an elegant pattern of black and white squares. 

The grand staircase at the far end was covered with emerald-green carpet, but instead of heading for the stairs Aunt Hattie turned to the left. There was a man patiently standing there, wearing a gray suit with two rows of shiny gold buttons and gold trim around the collar, a flat gray cap, and white gloves. He said, "Which floor would you ladies like to visit today?" 

Without hesitation, Aunt Hattie said, "Third floor please." 

He pushed a screen into a space behind the wall and said, "Ladies first." 

It was Lila's first ride in an elevator. There were mirrors all around the walls, which made it appear as if they were standing in a crowd of people who looked exactly like them. When Lila lifted the corner of her dress, so did the rest of the girls. When she waved her hand, they all waved back. She could have stayed in the elevator all day, but suddenly there was a "ding!" and the man in the suit said, "Third floor, ladies; please watch your step."
	
When the door opened, it appeared that they had just entered the sitting room for a very fancy house. It had a matching set of sofas and chairs covered in velvet, a large oriental rug, an enormous radio, a crystal chandelier, and a low table set up for tea with a silver tea service and various colors of china. The back wall was filled with bookcases. Lila could not imagine that anyone would be able to fill so many shelves, but the room was impressive. It was a teaser for the floor above, which was filled with furniture, linens, cookware, and china. Veda and Lila followed Aunt Hattie past the men's clothing, shoes, and hats, around the back to the children's section which contained a mixture of clothing for boys and girls. There were also toys---china dolls with curly hair and frilly dresses, miniature tea sets, a rocking horse with a mane and a tail made of real horsehair---but Lila knew better than to touch anything. They were here to shop for dresses for the baptism, not for toys. 

A woman approached them and said, "May I help you with anything today, ladies?" Similar to the man who helped with the elevator, she was also wearing gray, but instead of gold buttons, her dress was accented with a crisp white collar and cuffs. 

Aunt Hattie told her, "Yes dear, we're here to find dresses." To clarify "for the girls," she put her arm behind Veda and gently nudged her forward. 

The woman reached out for Veda's hand and said, "Oh, aren't you a beauty! I know just the dress for you." After pulling out some dresses that Veda and Lila could try on, the woman indicated that they should follow her to the back. The fitting room was large enough to hold all four of them. It was painted dark green and there were two large mirrors hanging together in one corner. 

Aunt Hattie sat down on the elegant sofa and said, "You can take off your shoes and dresses but leave on your panties and undershirt." Although Aunt Hattie behaved like they were doing the most natural thing in the world, Lila found it unsettling to take off her clothes in front of a stranger. 

The saleswoman held out a beautiful light blue dress and said to Veda, "I think you should try this one on first; the color will be lovely with your eyes." 

Veda blushed and said, "I like that one too." 

Aunt Hattie insisted that she try on several dresses (just to be sure), but everyone agreed that the blue one was the best. Veda looked stunning---like a young woman instead of a child. The fluttery sleeves and full skirt accented her tiny waist. Aunt Hattie said, "We'll need to get you some nice shoes to go with that."

While she was still trying on dresses, the saleswoman held one out for Lila. It was white with red polka dots and a red sash. "I think this one will look gorgeous on you." Much to Lila's dismay, however, the dress would not fit over her hips. 

Aunt Hattie said, "Don't pull on it, Lila, it's alright if the dress doesn't fit." 

The saleswoman added, "Don't worry, dear. I'll find you a larger size." The woman left the room and came back with five more. "Unfortunately, I don't have a larger size for the red-and-white dress, but here are some others that I think you will like." None of those dresses fit either. Lila was starting to feel very embarrassed. Why did trying on dresses have to be so easy for Veda and so difficult for her? When one of the dresses finally fit (it was yellow and made Lila feel like a giant goldfinch), she put on a big smile and said, "Oh, I love this one." 

The saleswoman could not disguise her sigh of relief. "You look beautiful, dear. I'm so happy that one works for you." She turned to Aunt Hattie and said, "Is there anything else you need today, or shall I take your packages downstairs?"

Before heading to another shop to look for shoes, Aunt Hattie took them to the tearoom on the second floor so they could have lunch. A waitress (who, Lila observed, was wearing the same gray dress with a white apron) brought them a tray with tea, milk, sugar, little sandwiches cut into triangles, a bowl of fruit, and a plate of cookies. Some of the sandwiches were filled with egg salad (delicious); others were filled with cream cheese and had a slice of cucumber on top. The cookies were dark pink and filled with cream. The first one was so good, but when Lila reached for one more Aunt Hattie said, "Do you really think you should be eating that?" Lila pulled her hand back and was silent for the rest of the meal.

A few weeks later, Aunt Hattie invited them back to her house for tea. Veda was thrilled. Aunt Hattie was so glamorous. Veda wanted to live in a house like hers someday, with a modern stove and washing machine and big beautiful sitting room to entertain guests. After they had their first cup of tea Aunt Hattie said, "Veda&hellip;on top of the dresser in my bedroom is a big jewelry box. Why don't you go pick something out to keep as a present? A young lady like you should have an elegant piece of jewelry to wear to parties." 

Veda's eyes lit up with excitement and she said, "Really?" 

Aunt Hattie smiled and nodded her head. She said, "Go on, dear." Once she was out of earshot, Aunt Hattie turned to Lila and said, "Your sister is such a beautiful girl. In just a few years she's going to be very attractive as a bride." 

Why was Aunt Hattie telling her this? Lila knew that Veda was beautiful, but it was hard to imagine her as a grown-up. 

"As for you&hellip;" Aunt Hattie continued, "You need to pay more attention to your diet. Stout girls do not get invited to parties." 

Lila was so embarrassed. She had no idea what to say. She looked down into her empty teacup and resolved to stay away from Aunt Hattie. 

## Notes

The Slabacks were not very religious. It took me months to figure out the denomination of the church that was next to her father's farm in Crawford County (Methodist). The only evidence that Lila Slaback went to church in La Crosse is her baptismal record. This is a mystery to me since the church for her baptism was Presbyterian. It is not uncommon for Christians in the US to attend church only for Easter and Christmas.

Doerflingers was a real department store in La Crosse in the early 1900s. Although I could only find images of the exterior, I used images of other department stores from the same time to imagine what the inside would have looked like. In the 1930s, only the most luxurious stores in the Midwest had elevators. They were more dangerous and difficult to operate than elevators today, so buildings hired operators to open and close the doors and direct customers. The staff in grand department stores wore uniforms similar to the attendants in theaters and hotels. I have no idea when Lila rode an elevator for the first time, but I remember being fascinated by them as a child. I also loved three-way mirrors due to the way they created "many girls" when I looked in them. In the early 1900s, buying ready-to-wear was still a novelty, especially for working-class girls and women in the Midwest. (It was more common for men.)

One of the problems with mass-manufactured clothing is that it doesn't fit everyone. Shopping can be a fun adventure when the clothes fit. If they don't fit, shopping can foster (and reinforce) feelings of body-consciousness and embarrassment. Before "plus-size" became a dominant term in the fashion industry, young women who were too large for standard sizes were referred to as "stout." By rewarding Veda and shaming Lila, Aunt Hattie (whether intentionally or not) was driving a wedge between them. This is foreshadowing for future chapters.

For more information, see the author[-@akou2024a], @peters2023a, and @whitaker2006a.  
