# Chapter Fifty-Seven

The seizures started in 1957. Lila fainted at work and couldn't be revived; she was taken to the hospital in an ambulance. She half expected to be told that she was pregnant again, even though she had turned down all offers of sex for the last two years. At first, the doctors were not sure what was wrong and told her they would need to run some tests. In the end, they said her symptoms were probably from the repeated pregnancies and toxemia; her kidneys were damaged, and her blood pressure was out of control. Out of shame and misplaced loyalty, she never told them about the pills from Merlin.  

The hospital asked her for her next of kin. She didn't trust anyone and didn't want to give them a name. Are your parents still alive? What about a sibling? She never did tell them anything, but they found her parents and brothers based on her last name. Reluctantly, she had returned to using her maiden name after the divorce; she felt like she had burned all of her bridges with the Schneiders.  

By the time her father visited the hospital, she was in and out of consciousness. The seizures were lasting longer and becoming more frequent; Lila knew she was dying. Her father asked what she wanted to do with the girls. In tears, she said, "I want Hazel and Bonnie to stay together." When she was unable to leave the hospital, the state had sent them to live in the orphanage. In a flat tone that she could not read, her father said, "Izro will take them." The thought was comforting. She had barely seen Izro in the last ten years, but she trusted her more than Veda and her mother.  

Myrtle Joyce was fourteen and looked so much like her father. Sometimes in her dreams, Lila saw the men who had drifted in and out of her life: Lloyd, Daniel, Herman, Jack. Aside from John and Alice, she had never named the fathers on the children's birth certificates. The social workers had asked repeatedly for names, but she didn't know what to tell them. She didn't know the men who had raped her; even years later, it gave her nightmares to think about the attack that led to Hazel's birth.  

The damage to her kidneys caused her body and face to swell uncontrollably. One day, a nurse gave her a mirror to hold while she brushed her hair. Lila barely recognized her own image.  

## Notes

I know from my Aunt June that Lila had some time to plan what would happen with her children after she died. There are photographs of her in the hospital with her father and her son, Randy. I don't know if there are others, but those are the photographs that I have seen. Lila was very bloated and sitting in a wheelchair; compared to photos in her twenties, she is barely recognizable.  

For more information, see @byrom1969a, @institute2015a, and @ng1993a.  