# Chapter Fifty-Five

Lila was in the hospital for three months. When she entered, it was winter; when she left, it was spring. Her son was born on March 8th, 1954. She had no idea what to name him. One of the attendants (who struck Lila as being incredibly young in her little pink apron) said, "I'll help you come up with a name!" They chose Randy, which was a popular new name for boys. Lila was relieved that he seemed to be unharmed by the pills and the toxemia. He had a vigorous cry and was hungry all the time. Concerned that he wasn't getting enough to eat, the nurses made him extra bottles with evaporated milk and corn syrup.  

One day, Myrtle and Carl arrived during visiting hours. Lila was surprised to see them; in the last three years, they had rarely spoken. Myrtle was wearing a striped dress that made her hips look enormous. She was holding her handbag in front of her like a shield. She sat down in the chair next to the bed, and Carl went into the hallway to find another one. For a few moments, Lila stared at her while she looked at the door, waiting for Carl to return. Finally, Myrtle cleared her throat and said, "I want you to give your son to us."  

"But why?" said Lila. "I won't be in the hospital for much longer."  

Myrtle glanced over at Carl, whose face was expressionless. Myrtle said, "You can't keep living this way, Lila. Carl and I can adopt Randy and raise him as one of our own. It's not right for your children to grow up with a single mother."  

Lila wanted to scream; the only thing that stopped her was knowing that the nurses would scold her for disturbing the ward and inject her with a sedative. She stared at Myrtle with such intensity that Myrtle shifted her gaze to the floor. After a few moments of silence, she stood up, and Carl followed her to the door. Myrtle turned and said, "I know you're upset, but think about it, Lila. Randy will have a stable home and two parents who love him." And with that, they left the room. Lila was so enraged that the nurses gave her a sedative anyway.  

Within a few days, her anger turned to sorrow. Myrtle was right. She wasn't doing her children any favors by clinging to them. She had tried so hard to be a good mother, but it just wasn't enough. The grief of that realization extended her stay in the hospital; the nurses were worried about her fragile state of mind. By the time she was ready to be discharged, she had decided that Myrtle and Carl could have her son. A nurse brought her the adoption papers.  

As she held Randy for the last time as his legal mother, the nurse said that they would release him to the Schneiders. With a compassionate tone, she said, "I know this is hard, but you're doing the right thing. The hospital will take care of the rest."  

Leaving the hospital without a child in her arms was the worst feeling she could have imagined. She had never felt so ashamed and full of grief. Gladys had visited her several times during her stay in the hospital, but she was not there the morning Lila was discharged. A social worker had given her money for a cab. She asked the driver to stop at the apartment, but she was not surprised to find that her key no longer worked. There had not been enough time (or money) to make arrangements with the landlord. Now she had no home, no possessions, no job, and all of her children were gone. Was she even still a mother? In a fog of disbelief, she gave the driver directions to Emma's house.  

Summer arrived early that year, but Lila felt so cold and completely empty. How was she going to get Myrtle Joyce out of the orphanage again when she could barely get out of the house? Emma urged her to go back to the doctor. He was dismissive when she described how tired she was, but when he felt her neck during the exam he said, "Hmm&hellip;you do have a goiter. I'll write you a prescription."  

Lila froze and said, "No pills; I don't want to take anything."  

The doctor forced her to take the prescription, but she never went to the pharmacy.  

Unable to bear the thought of walking across the bridge, Lila decided to take the first job on French Island that she was offered. It was at the tavern on Bainbridge Street, the one she had rejected after Hazel was born. Nothing had changed; it was just as creepy as she remembered. "Beggars can't be choosers," she thought ruefully. Without an income, she had no hope of renting an apartment. Even Emma wouldn't tolerate her forever.  

## Notes

In 1954, "Randy" was the thirty-third most popular name for newborn boys in the United States. It was not a family name for the Slabacks or the Schneiders.  

In the 1950s, there was tremendous social pressure for women to marry young and give birth only in the context of an intact, heterosexual, nuclear family. Less than five percent of white women pursued single motherhood. I knew Myrtle Schneider, who died when I was twenty years old. She cared tremendously about her children but also had very rigid values regarding birth and marriage. I respect her for taking care of Randy when the Slabacks were unwilling to step up; however, she probably put a lot of (well-meaning) pressure on Lila.  

For more information, see @babycenter2024a, @feldstein2018a, @glaser2021a, and @weiss2000a.  