# Chapter Fifty-One

What did Herman's kiss mean? The question rattled in Lila's mind. Did he forgive her? Did he want her to come back? Maybe it just meant "goodbye." Nora and Gladys had seen the kiss, but they offered no explanations.  

There was heavy snow in January. Between the snow, the pregnancy, and carrying Hazel (who was walking but not old enough to walk by herself in the street), it was getting difficult for Lila to travel more than a few blocks. By the time the blizzards eased up and Lila was able to go back to West Salem, it was already the end of February. Gladys was visibly relieved to see her. She welcomed the children and brewed a pot of tea to warm them up. By the time it was ready, the children were off playing. After some easy conversation, Gladys put her hands over Lila's. (Oh no, Lila thought&hellip;here comes another "talk.") Gladys looked her in the eye and said, "Lila, I truly do care about you. I don't know what happened between you and Herman, and it's not my place to judge. I love him as my brother, and I love you as my sister." Lila felt tears welling up. She didn't want to be a burden or to break down in front of Gladys.  

"What can I do to help you, Lila? Myrtle Joyce and Hazel can stay with us while you're in the hospital. I don't know what else you might need." It was like talking with Emma. Unlike Myrtle, Gladys didn't jump to conclusions or make demands. She just listened. 

Lila started to cry, and Gladys offered her a handkerchief. Eventually, Lila replied, "Maybe I should move back to West Salem." 

"Is that what you want?" said Gladys. "Would that make you happy?" 

A flood of emotions was building in her heart---sadness, anger, grief, anguish---maybe even hope. Gladys didn't press her for an answer. Lila said, "I just don't know. I don't think Herman and I belong together, but how would I find a job if I moved back here?"  

With her encouragement, Lila went to La Crosse Hospital to ask for an appointment. It had never occurred to her to see a doctor before going into labor. Gladys said that it was called "prenatal care." When the doctor opened her file, his eyebrows furrowed in concentration. "I'm glad you came in, Mrs. Schneider. Hopefully, we can make this delivery easier for you than the last time." He scheduled surgery for April sixth but told her to return immediately if she noticed any signs of labor. Lila promised that she would.  

Lila worked at the bar right until the end. She was grateful to have the income and to be around people, even though the men had stopped flirting with her. A small group of regulars who had known one another since childhood were singing drinking songs at the bar on Friday nights. Some of them were funny and some were tearjerkers. One of her favorite songs was "My Bonnie Lies Over the Ocean." 

> | My bonnie lies over the ocean,
> | My bonnie lies over the sea,
> | My bonnie lies over the ocean,
> | Oh, bring back my bonnie to me!

During the chorus, everyone sitting at the bar would sway back and forth to the words. When her fifth child was born---another girl---Lila decided to name her Bonnie. Naming them after friends and family had never done any good. It was time for something new.  

## Notes

After a long series of challenges (and sometimes poor decisions), Lila has grown wary of "the talk" from friends and family members. The unconditional acceptance she feels from Gladys allows her to take some bits of advice, like pursuing prenatal care.  

I don't know if Lila ever received any kind of mental health support; it is unlikely since the concept of "Rape Trauma Syndrome" was coined in 1974 and PTSD in the 1980s. 

For more information, see @cray1999a, @herman1992a, and @seigel2013a.  