# Chapter Fifty-Four

The next person she had sex with was Merlin. The pills were losing effectiveness; once again, she was tired all the time. He said he could fix that, but it would cost extra. How much? Two dollars per week. She must have looked shocked or desperate because after a few moments he added, "If you can't afford it, we can set up a trade."  

Merlin had been a soldier. He had lost one of his ears to a sniper's bullet, but he wore a fake and kept his hair a bit long. Most people didn't notice. Lila wasn't sure why he had decided to work in a bar. He didn't sing or tell jokes. He didn't even drink. He made the hamburgers and cheese curds and Reuben sandwiches without complaint, but it didn't take much skill to be that kind of cook. Before he started working, there had been a series of cooks who quit after a few weeks. The job was boredom punctuated by burns from the deep fryer. Later, Merlin told her that he just enjoyed watching people: the regulars, the waitresses, the brawlers, and the criers. He thought they were all fascinating. He admitted that he made more money selling pills than he did as a cook. Everyone at the bar was a potential customer.  

The trade with Merlin was a monthly night of sex, but it was never impulsive. He didn't want to wear rubbers but told her that if they had sex right after her period ended, she wouldn't get pregnant. Could it really work? She had never heard of it before. After a few months, she started to enjoy their time together. Like Jack, Merlin never gave any indication that he wanted to get married or be a father, yet Lila found herself fantasizing about sharing a life with him---cooking for him, waking up next to him, having someone who could share the burdens and joys of being a parent. Merlin was not fazed by her life as a single mother. He knew that she worked in a bar and didn't judge her for it; she thought it was the best she could hope for.  

There was just one problem with Merlin's plan: Lila's cycle was no longer regular. Was it the pills? Was it normal for her age? She had no idea. One time her period returned after just three weeks. Another time it took seven weeks. She wept from relief when she started bleeding again. What was she supposed to do about the bargain? One month she didn't have her period and decided just to tell Merlin that it was "time."  

Late in the summer of 1953, Lila realized that she was pregnant. She didn't want to say anything to Merlin, but she saw him every time she had to pick up a tray from the kitchen. The secret was eating away at her. It didn't take him long to ask what was wrong. When she told Merlin that she was pregnant, he froze. After a pause that felt like hours, he said, "How is that possible?" Lila started to cry. She couldn't cry at work, so she walked out to the back of the building. A few minutes later, Merlin followed her. "You can't take those pills while you're pregnant&hellip;you need to start tapering down right away."  

By the time she went to the doctor, she was no longer taking them. It had been a hard adjustment. The fatigue came roaring back, and she felt a crushing sense of sadness and doom. She was gaining weight (Merlin told her it was good for the baby), and the apartment was an absolute mess. She had put Myrtle Joyce in charge of washing the dishes, but they often sat in the sink for days. A few times she was so angry that she hit her with the cord from the iron. She felt bad for lashing out; it was terrifying to be so out of control. Alice was wetting the bed and Bonnie was teething. Lila had been through difficult times, but this was a new level of difficult.  

At her appointment, the doctor said, "Your blood pressure is higher than I would like. I need to see you again in one week." What did that mean? The doctor didn't explain. 

The next time he said, "Mrs. Schneider&hellip;I'm concerned that you're developing toxemia. Have you ever heard of that?" 

Lila shook her head to say no. 

"Since the start of this pregnancy, have you had any dizziness or vomiting?" 

"A little," she said, thinking that it was probably because she had stopped taking the pills. In that moment, she wanted them so badly. 

The doctor asked her to raise her legs and pressed his fingers into her ankles. "Have you had any headaches or blurry vision?" Merlin had warned her that she would "feel like crap" for a while, but he hadn't been very specific. She had been so focused on getting off the pills that she hadn't really considered how the pregnancy itself was affecting her.  

After the doctor asked a few more questions he said, "Mrs. Schneider&hellip;for the health of you and your baby, I want you to go on bed rest. I want you to lay down and not get up for more than one hour per day." 

Lila was shocked. What he was asking was impossible. "But how will I work? Who will take care of my children?" 

Sternly, the doctor said, "You need to figure this out right away. You could have a stroke; you could be damaging your liver and kidneys&hellip;you could even die from this." He underscored his seriousness by gripping her shoulders and staring straight into her eyes.  

When she left the hospital, her head was swimming. She went to work in a daze and somehow managed to work her shift, but it would be her last one. The next day she took the children to West Salem. When Myrtle Joyce asked, "Why are we not going to school today?" Lila snapped back: "Don't ask questions&hellip;just do what you're told." When Gladys answered the door, she knew immediately that something was wrong. She told the children to go play and ushered Lila to the sofa. As Lila told her what the doctor had said, Gladys's eyes grew wide with alarm. "I'm so sorry that this is happening to you, Lila. I'm glad you came to me for help."  

By the next day, Gladys and Lila had come up with a plan. Myrtle Joyce would go back to the orphanage in La Crosse. Alice would go with her father. Hazel and Bonnie would go with a family that Gladys knew from church. She reassured Lila that they were kind people who had a lot of experience with children; they lived on a farm a few miles from town. Gladys said that she would drop them off, but Lila said, "No, it's my responsibility. I want to be with them until the last possible moment." Gladys gave her the directions and the key to Carl's truck. They hugged just before she drove off, and Lila said, "Don't cry, Gladys. If you cry&hellip;I'm going to cry, and I don't think I'll be able to stop." Her throat was already clenching.  

Lila didn't know if she would ever see her daughters again, but when she left Hazel and Bonnie with the Jostads, she told them, "I'll be back soon." Dropping them off took all of Lila's remaining energy. Gladys took Alice back to Herman. By then, Lila was getting so drowsy that Gladys had to leave Myrtle Joyce and her own children with Nora so she could drive her to La Crosse Hospital. They drove so fast that Gladys was sure she would get a speeding ticket.  

## Notes

I've met people like Merlin before---men and women who appear to be doing a certain job but are actually there for their own private reasons. I used this chapter to speculate on how people like Merlin and Lila end up in their positions as drug sellers and drug users. At any time in her life, Lila could have walked away. I respect how hard she fought to stay in her children's lives, even though it led her down some very dark paths.  

When my second pregnancy ended in a loss, I read the book *Taking Charge of Your Fertility* to help conceive my son. It builds on older knowledge of the "rhythm method" of birth control, which works for many people. Unfortunately, one problem with thyroid disorders is that they tend to throw off the timing of the reproductive cycle. In the 1970s, toxemia was relabeled as "hypertensive disorder of pregnancy." Today, it is called pre-eclampsia.  

When I reconnected with one of my mother's sisters (June) in early 2020, she told me about her memory of Lila dropping her off at the Jostad house. They were kind people, but June and her younger sister Bonnie---who always stayed together---did not see Lila again for two years.  

For more information, see @campbell2000a, @tilden1974a, @weinberg2017a, and @weschler1995a.  