# Chapter Fifty-Two

Lila had given up her apartment after she found a house to rent on French Island. The owner had been diagnosed with tuberculosis and needed some time away to recover. Emma's sons had helped her move. Less than three weeks after Bonnie arrived, Lila was back at work. It was the first time she had been able to return to the same job after having a baby. Lila was grateful, but she was also exhausted. Some of the regulars cheered when she returned, but Betty (the curvy waitress) pulled her into the storeroom and said, "I'm worried about you, Lila&hellip;why are you back to work so soon?" 

Lila shrugged. "I need this job to support my children." 

Betty gave her a hug and vowed to help her as much as she could. After a few weeks, Lila realized that Betty's "help" consisted mostly of cashing out her tabs and taking the tips.  

At the end of the month, Gladys visited with Myrtle Joyce and Hazel. Lila felt ashamed that she had not been able to clean the house or bake any treats. She was just too tired. Gladys said, "Don't be silly. I'll wash these dishes and you can enjoy a little time with your children." Myrtle Joyce was excited that the baby was a girl. "I told you, Mom!" After a few minutes, she said, "I'm going to Emma's house to see if she has any cookies." Before Lila could object, she was already out the door. Her increasing independence made Lila nervous.  

Gladys put two cups of tea on the table and said, "Let me hold Bonnie&hellip;I'm sure Hazel would like to sit with you for a while." She was sucking her thumb when Lila pulled her into her lap. She laid her head on Lila's chest and quickly fell asleep. 

"I hope the girls haven't been too much trouble." 

"No trouble at all," said Gladys. "If you don't mind, I think it would be good for them to stay with us until the school year is finished next month." 

"That's fine," said Lila. As much as she wanted them back home, she knew that as soon as they returned it would be more work and more expense. She wasn't sure that she could handle it.  

Lila did her best to be attractive and outgoing at work. Her breasts felt enormous in the uniform, even though she had purchased a new bra to keep the "girls" under control. She began curling her hair and wearing dark red lipstick. One of the regulars said she looked like Elizabeth Taylor, but the cook---who everyone called Merlin---was not fooled. One night after the dinner rush, he told Lila, "You look like you've been through a war&hellip;I see the exhaustion in your eyes." Lila looked down at the floor and said nothing. The next night, he slipped her a package of pills in a tiny envelope. "Try these for a week&hellip;take one at the start of your shift. If you like what it does, I can get you more." After her experience with the thyroid medication, Lila was skeptical that they would do anything.  

She had no idea what was in the pills, but she decided to try one the next night. To her surprise, she made it through her shift, picked Bonnie up from Emma's house, and had enough energy to wash the dishes before falling asleep. The next night was the same, and the night after that. It was like a switch had flipped. She told Merlin that she wanted more. "Five dollars per week," he replied. It was a lot of money, but she was tired of being so tired. They shook hands and settled the deal.  

At the end of May, Lila took the train to West Salem. Gladys asked to hold Bonnie and told her, "You must be a good little sleeper&hellip;your mother looks fantastic!" To Lila's surprise, Alice was there with Myrtle Joyce and Hazel. All of her girls were together. She sat on the floor, and they piled around her. For a moment, Lila was filled with joy. When the children left to play again, Lila and Gladys sat down at the kitchen table to have coffee and strawberry pie.  

Gladys said casually, "Herman asked me to take Alice. She was having a tough time on the farm."  

"Oh?" said Lila. "What kind of trouble?"  

"Herman didn't say, just that it would be better if Alice stayed with you."  

Lila had mixed feelings. She was thrilled at the idea of having Alice back, but could she really take care of four children? Myrtle Joyce was the only one old enough to be in school. Regardless of her feelings, she felt like she didn't have a choice. If the Schneider family trusted her enough to have Alice back, she better not disappoint them.  

## Notes

Much of this chapter is based on my own experience as a worker and single mother. I've never used recreational drugs, but I remember when I started drinking coffee daily (after my last child was born). I wondered how I had managed without it. 

During World War II, the Nazis gave soldiers meth to keep them alert and motivated beyond normal levels of human endurance. In response, the US military began experimenting with amphetamines; some soldiers developed addictions and sought out the drug when they returned home. In the 1930s, 1940s, and 1950s, doctors prescribed amphetamines (mostly to women) as an appetite suppressant and treatment for depression. As a street drug, it became known as "speed" for its ability to keep exhausted workers on their feet.  

I'm not certain that Lila used speed; however, she did lose a lot of weight a few years before her death (from causes that are consistent with amphetamine abuse).  

For more information, see @andreas2020a, @grinspoon1975a, and @rasmussen2008a.  