# Chapter Fifty

Lila was skeptical about Myrtle's plans, but she went back to visit as promised. Johnny remembered her immediately and gave her a long hug. Since she had missed his birthday, she gave him a slinky as a gift. The children were fascinated and played with it for hours. Alice was shy; she was more interested in the new baby than in her mother. Myrtle said, "Give her a little time&hellip;she'll warm up." By the end of the visit, Alice was sitting in her lap. Until that moment, Lila had not realized just how much she had missed her two other children. It was like part of her soul had been ripped out when Helen sent them to live with Herman.  

For the next visit, Myrtle invited Gladys. She gave Lila a big hug and said, "I'm so glad to see you again." Lila was ashamed that they had fallen out of touch; she could have written her letters. Gladys had a little boy who was the same age as Hazel. After church, they traded funny stories about being mothers. She was such a joy to be around. The children also swirled around her like honeybees around their queen. 

"Look at this carrot I dug up, Aunt Gladys&hellip;it looks like a little person!"  

"Watch me do a somersault&hellip;now watch me do a cartwheel!"  

When the older children wanted to play baseball, they asked her to be their pitcher. One visit turned into another until Lila was taking the train to West Salem nearly every Sunday.  

It took weeks for the Schneiders to realize that Lila was pregnant; they just assumed that she was gaining weight. Myrtle was the one who finally confronted her. When Lila responded, "Yes, I am pregnant," Myrtle had tears in her eyes. "How could you do this? I just want you to be happy and straighten things out with Herman and now you're having another baby that is not even his." Lila froze. She had let her guard down, but Myrtle was no better than Veda. She had been such a good friend when she was pregnant with Myrtle Joyce. It was a punch in the gut to realize that she had stopped being a friend as soon as Lila became part of the Schneider family. Family was Myrtle's whole life; she assumed that Lila felt the same way.  

Before the confrontation with Myrtle, Gladys had asked Lila to spend Christmas at her house and Lila had agreed. December was a lonely time of the year in La Crosse. The bar would be closed, and Emma would be busy with her own children and grandchildren. Although she tried not to think about it, December also reminded Lila of the rape: Christmas lights, people laughing, clusters of soldiers. Every dumpster felt like a threat. The year before, she had white-knuckled her way through the month. The only way she could sleep was by drinking shots before bed. It made her stomach sour, but it kept the nightmares away.  

When Lila took the train for Christmas it was packed with college students going home for the holidays. It was easy to recognize them with their sweater sets and carefree laughter. She wondered what it would be like to have that kind of life. Watching the other passengers was her favorite thing about riding the train. Since she and the children were staying in West Salem for a few days and going to church, Lila had packed their best outfits in a plaid suitcase that she had found in a secondhand shop. It fit neatly under their seat.  

Lila had not considered that Herman would be at church. He entered just a few moments before the service started and sat down next to her without saying a word. She felt like her heart was going to leap out of her throat. Was he angry? Did he want to talk? What would they say? With her mind racing, she barely heard the songs or the sermon. Herman was warm beside her and smelled like soap and hay. He didn't sing along with the hymns. Lila wanted so badly just to hear his voice, but when the service ended, he left without saying anything. Lila felt crushed. She wanted to be desired. She wanted to be missed.  

She was relieved when Herman joined them for dinner. Nora and her family were there too. The house was chaos from all of the children laughing and running around; their glee was infectious. Gladys had made Christmas crackers for the children to open after dinner. The best way to open them was to have two people pull on the ends, which caused the rolls of cardboard covered with shiny paper to open with a bang.  

> | What do you call a cat that lives in the desert?
> | *Sandy claws!* 
> | 
> | Why does Santa have three gardens?
> | *So he can ho, ho, ho!*
> | 
> | What do Santa's little helpers learn at school?
> | *The elf-abet!*

Lila groaned over the first few jokes, but the children were delighted. By the end, everyone was in tears from laughing so hard. They drank hot chocolate (with mint schnapps for the adults) and stayed up late. At the end of the evening, Lila was standing in the kitchen with Gladys and Nora. Herman was already wearing his coat when he gave Lila a kiss on the cheek. He smiled and then walked out the door without saying a word.  

## Notes 

"Christmas crackers" are not as common in the United States as in the United Kingdom (where they were invented), but some people make and open them for Christmas. I included these jokes to remind the reader that Lila has a sense of humor. She is weighed down by many challenges but (like any person) still desires companionship and fun.  

The culture of drinking is very strong in Wisconsin, especially around La Crosse: a college town with a large military base nearby and a large German-heritage population (e.g., the Schneiders). I was introduced to alcohol when I was still in diapers.  

For more information, see @oldenglishcrackers2024a, @clemente2014a, @draeger2012a, @ford2016a, and @shafer2016a.  