# Chapter Five 

One night that fall while the family was eating dinner, Theron said that he needed to make an announcement: he was planning to get married. Lila's mother stood up, handed the baby to Izro, and went over to Theron to give him a big hug. Although she had tears in her eyes, she was clearly not sad. She said, "Oh Theron, I'm so happy for you!" 

Lila turned to Veda and said, "What does that mean?" 

Veda said, "Theron wants to have a wife so they can become a mommy and daddy." 

It wasn't long before she heard the word "marriage" at school. Some of the girls were playing a clapping game: "First comes love, then comes marriage, then comes the baby in the baby carriage!" Is that what her parents had done? Lila had learned where babies came from thanks to her new little brother but thought she knew nothing about love and marriage.  

A few weeks later, a stranger named Myron arrived at their house for dinner. It wasn't that unusual to have a guest over. Maybe he was one of her brother's friends. Lila's father shook his hand, and the men went out to the backyard to look at the garage and the truck while Izro and her mother finished cooking. Izro handed a stack of plates to Veda and the silverware to Lila and told them to go set the table. She wasn't exactly rude about it, but she seemed nervous---not her usual self. Lila noticed that her cheeks were pink.  

At dinner, they talked about Myron's family. His parents had lived in La Crosse and his mother was best friends with Aunt Hattie before they moved to Onalaska. His parents were from Norway and changed their names from Lars and Anna to Louis and Antoinette. (Lila thought that was fascinating; she had no idea that it was possible to change your name.) There were seven children in Myron's family, three girls and four boys. He was the youngest son, the sixth out of seven kids, the same as Lila. It was nice to hear about something besides lumber prices and vegetables. Then Myron said, "Mr. Slaback, what I came to ask you is&hellip;would you allow me to marry your daughter, Izro?" Lila's mother had been so happy when Theron said he was getting married, but that night she was very quiet. Lila was confused about the difference in her reaction. Was she angry at Myron for some reason? Did she not want Izro to get married? Her father said "Yes," and her older brothers gathered around to laugh, slap Myron on the back, and say, "Welcome to the family!" Lila looked across the table at Izro and thought she must be running a fever because her cheeks had turned from pink to red.  

The family decided to have a double wedding in January, and it was very cold---the kind of cold where the snow is crunchy and screams when you step on it. Lila was still on vacation from school, and she was wearing a new dress that her mother had made on the sewing machine. It was the same shape as the other two dresses she wore to school, but this one was thicker (and warmer) with a pattern of red roses on a blueish-green background. Lila felt beautiful in the new dress, especially with a matching red ribbon in her braids. She had received the dress and ribbon for Christmas, along with an orange, a new pair of mittens (made by Izro), a scarf for her doll (knitted by Veda, who was just learning), and a rope for playing games outside. Her mother told her to start putting on her coat and hat because Uncle Frank would be there soon with the car to pick them up and take them to church. Lila vaguely remembered going to church back when they lived on the farm---it already seemed like they had been in La Crosse forever. Where was Izro? "She's at the church waiting for us," said her mother. Without Izro there to give her a reminder, Lila forgot to put on her mittens. Her mother scolded her when she noticed.  

Theron and Izro were getting married in the Norwegian church. It was just far enough from their house that Lila had never noticed it before. When the car pulled up to the curb, she could hardly believe how tall it was. The main part was brick and shaped like her school, but in the front, the church had an enormous tower with a tall gray roof. Lila had heard about castles and wondered if this was one of them. The size of the building was breathtaking; the front door was big enough for a giant. Lila got out of the car with her mother and the younger children and together they stepped into the building. The entrance was dark, even though it was daytime. As they went up the stairs, however, and the bright interior came into view, it was like climbing into heaven. They entered from the back of the main room, which was filled with rows and rows of wooden benches. (Lila wondered how many&hellip;she wished that she could walk from one end to the other and count them all.) The walls were painted white, but they were streaked with colors from the light streaming in through the windows, which were filled with pieces of colored glass. The effect was incredible. At the front of the room, there was a very large wooden cross hanging on the wall, a table with a white cloth, racks of large white candles, and a wooden railing with a long bench in front of it. There was soft music playing. Where was it coming from?  

There were already people sitting in the first few rows. Lila recognized Uncle Frank and Aunt Hattie, her cousin Lloyd, and her older brothers, but most of them were strangers. Myron and Theron were standing in the front of the room by the railing. Where was her father? Where was Izro? Her mother handed Looy to Aunt Hattie; as she took off her coat and hat and placed them next to Lila, she ordered Veda to look after Earl ("Make sure he doesn't leave this bench"). Then she turned and left. 

"Where are you going?" Lila asked, but her mother didn't answer her. 

Aunt Hattie said, "Your mother will be back soon, Lila. Please be a good girl and stay quiet."  

Shortly after her mother returned, the music changed, and everyone turned to look at the back of the room. There was a beautiful woman with blonde hair standing next to a man who she didn't recognize. As they started walking slowly towards the front of the church, Lila saw that there was another woman behind her---it was Izro! She was standing with their father, who was wearing his best shirt and pants. Izro looked shy and nervous, but her father was calm. As they arrived at the front of the room, Lila noticed a man wearing a dress and she giggled---why was he wearing a dress? Her mother nudged her, which was a clear sign to be quiet. She saw that Izro and the blonde woman (whom she would quickly learn was named "Borg-knee") were both wearing long white dresses and veils made of beautiful white lace. How could they see with the veils over their faces? As they reached the front, Izro stood next to Myron and Borgny took her place next to Theron; Lila was relieved when the men lifted the lace and pulled it back so the women could see. Maybe she really was in a castle because they both looked like princesses.  

Lila thought most of the service was boring. The man in the dress read from a book and told everyone what to say. Each groom gave his new wife a ring and the man said, "You may now kiss the bride." Ew! Lila had never seen a man and a woman kiss before. Sometimes Izro kissed her on the cheek or the top of the head, but this was different. They were kissing on the lips and some of the young men watching from the pews cheered and clapped. Izro blushed, but she was smiling as the couples walked past. Her mother told Lila they were heading downstairs for lunch and to please bring her coat and hat. As they ate ham sandwiches and pickles and drank coffee (which Lila was usually not allowed to drink; her father warned that it would "stunt your growth" if you drank it as a child), Lila looked around the room. Everyone was smiling, even her mother. She thought a wedding must be a very good thing.  

## Notes 

Theron and Izro were the first- and second-born siblings. They were married in a double ring ceremony in January 1929. Theron's bride, Borgny, grew up in a tiny village in the fjords of western Norway; as a young woman, she traveled alone (through Ellis Island) to the United States, probably to work as a domestic servant. Izro's groom, Myron, was born in Wisconsin, but his mother and grandparents were Norwegian. Based on census data, I speculate that Aunt Hattie served as a matchmaker for some of John and Hazel's children. There was a Methodist church next to the farm where Lila's mother grew up, but I did not find any evidence that the Slabacks joined a church when they moved to La Crosse. 

Since Borgny and Myron's family were Lutheran, I assume their wedding was in a Lutheran church. I was Lutheran growing up, so my descriptions of the church and the pastor's clothing are based on memories from my childhood. Bethel Lutheran was an enormous church on the north side of La Crosse. In northern Wisconsin, ham sandwiches are one of the most common foods for church weddings and funerals. 

My father grew up in a household with six girls and only two boys. The household chores were highly gendered; the girls did all the cooking and cleaning. My father's main responsibility was to shovel coal into the furnace. To this day, he barely knows how to cook. Lila's family had a very different configuration with more boys than girls. When Izro got married and moved to Onalaska, it would have been a huge loss to the family.

Christmas presents were very meager in the 1920s and 30s, especially for working-class families. My grandparents all described how exciting it was to receive a single orange. Receiving a pair of mittens was more common since they were necessary in the winter and could easily be made at home. As a small child in the early 1980s, I received a lot of clothing as Christmas gifts (even socks and underwear). I did some research on common toys in the 1930s; jump ropes and yo-yos were two of the most popular. 

For more information, see @bergland2011a, @york2012a, @ellis2020a, and @hoffmann2004a. 
