# Chapter Forty

Independence Day was on a Friday that year, so Nora and Gladys had decided to hold a gathering in Veterans Park. It was close to the farm, which would make it easy for Herman to drive back and forth. Lila had never slept in a tent and wasn't sure what to expect, but she was looking forward to spending some time with Myrtle and Gladys. It had been a tough year. Alice was not getting better. Myrtle had lost the baby. When Gladys asked Lila how she was feeling, she said, "Exhausted," but when Myrtle and Carl arrived, she felt ashamed. Why couldn't she just be satisfied with her life? At least the baby inside of her was still alive.  

When nightfall finally arrived, the men took the older children to the riverside to shoot bottle rockets. Nora, Gladys, Lila, and Myrtle sat around the fire. Nora's baby (her second and last) was just a few weeks old. Gladys told them that Carl had proposed. It was wonderful news! They tried to be lighthearted, but then the conversation took a dark turn. They talked about Alice and Viola and John. Their children were living with their grandparents in La Crosse until Viola could remarry. Lila was surprised and said, "Why?" 

Myrtle had been lost in her thoughts, but she looked up and said, "My parents don't want them to be raised by a single mother. Viola should have stayed with John." 

The conversation turned back to Gladys, but the news about the divorce and Viola's forced separation from her children haunted Lila for months. Would the Slabacks do the same to her if she left Herman?  

On Saturday, Carl drove to La Crosse to pick up Helen. Her son, Duane, was ten years old and growing fast. Wistfully Helen said, "He's going to be tall like his father." As they made lunch (grilled bratwurst and blueberry streusel for dessert) she asked Lila if she had a place to stay before the birth; if not, she could stay with her. Lila was relieved. She had been thinking of asking Veda but wasn't sure that she would agree. The contrast between Viola and Helen was striking. They were both single mothers, but as far as she knew the Schneider family was not pressuring Helen to marry again. Was it because she was widowed and not divorced?  

Herman drove Lila to La Crosse on the last weekend in July. Although her last delivery had been at St. Ann's, La Crosse Hospital was much closer to Helen's house. Lila thought she knew what to expect, but she was wrong. As soon as she arrived in the labor and delivery ward, the doctor said he was going to "medicate" her. That was the last thing she remembered. As soon as she woke up, she vomited. Once the bed was cleaned up and she had regained her senses, the nurse explained that the baby was turned sideways, so the doctor had put her under and given her a "c-section." Cheerfully, she added, "Isn't it better than going through labor?"  

Lila was speechless. How was this better? The room was spinning, and it hurt to cough. When they finally brought the baby into her room, she was sleepy and difficult to feed. Was there something wrong with her? Lila started to cry out of worry and frustration, and the nurse scolded her for disturbing the rest of the mothers. She had never had surgery or stitches before. The nurse who came to change her bandages every morning would not allow her to touch her belly or see what the stitches looked like. It was almost a week before they allowed Herman to visit his wife and newborn daughter.  

Lila was so disoriented from the birth that she didn't name the baby right away. Herman suggested "Alice" after his mother. Alice was also the middle name of Lyle's wife, Allene, so on the application for the birth certificate she wrote, "Alice Allene Schneider." As they drove out to West Salem to pick up Myrtle Joyce and John, Lila wondered how she was going to handle three small children along with the rest of the chores. Myrtle Joyce had recently turned three, and John was not quite two. It was daunting.  

By the end of September, Lila felt like she was losing her mind. Her life had become an endless stream of cooking and cleaning, snot, vomit, dirty diapers, crying, and begging. Myrtle Joyce had responded to the baby's arrival by refusing to take naps. John had learned to say NO and MINE. Do you want a cookie? MINE. Share that with your sister. MINE. Time for bed. NO. Herman was so good and patient with them. He loved the children, and they loved him. She knew it wasn't a contest, but it made her feel like a bad parent. Herman was busy with the cows and the harvest, so most of the time it was just her and the children. They were always getting into trouble with something: the stove, the pump, the baby, the farm animals. Once she fell asleep from exhaustion and woke up just in time to prevent John from falling through the hole in the outhouse. That would have been a disaster.  

One day, Lila was so desperate for relief that she piled the children in the truck and drove to Veda's house. "Why are they so dirty?" Veda asked. Myrtle Joyce and John were playing in the yard with David and Patty. They were all laughing and throwing acorns, so they took the baby inside to clean her up. When hot water came out of the tap, Lila started crying over the ease of Veda's life. She suddenly realized that living in a house with no running water was making her own life much more difficult. Sternly, Veda said, "You're the parent, Lila, not a child. You need to pull yourself together." She left the bathroom to check on the oven; they were having pot roast for dinner, cooked with an electric oven. When she returned, she had clean outfits for the children. "David and Patty have outgrown these, so you can keep them." Mercifully, she held Alice while Lila gave Myrtle Joyce and Johnny a bath. They didn't fuss like usual; they were so fascinated by the indoor bath and the bar of pink soap. Myrtle Joyce even let her wash and comb her hair. Lila caught a glimpse of herself in the mirror, but it was like looking at a stranger. There were dark circles under her eyes. Her hair was a mess, and there was dried vomit on her shoulder; she had barely even noticed when the baby spit up earlier that day. When dinner was done and it was time to go, the younger children wailed, and Myrtle Joyce begged to stay with her cousins.  

When they got back to the house, Herman asked where they had been all day. He wasn't angry, but Lila realized (with horror) that she had forgotten to prepare something for dinner. He had been working hard and deserved to have a hot meal. Lila said, "I'm sorry&hellip;I lost track of the time. I'll cook you something right away." 

"That's alright," he replied. "I'll have a peanut butter sandwich and a glass of milk." 

The next day as she was making more bread, she decided that she would ask Herman to put a lock on the door. If she could keep the older children clean and safe indoors, maybe she could get a little bit of sleep while Alice was napping.  

## Notes 

When I was young, most of my family's vacations involved camping. I enjoyed the freedom to go fishing and swimming and make new friends. Myrtle Schneider and her second husband, John Schneider (Viola's former husband) spent a lot of time camping in their RV at Veterans Park, so I have vivid memories of camping there for family reunions.  

This chapter offers more insights into attitudes surrounding divorce and single parenthood in the 1940s, which could be---but were not always---highly stigmatizing. Viola Schneider chose (or felt forced) to send her daughters away until she could remarry. On the other hand, Helen---a single mother due to her husband's untimely death---was not forced to remarry quickly or give up her son. This chapter also foreshadows that divorce is rattling in the back of Lila's mind as a future possibility.  

My mother, Alice, was Lila's third child. I know from newspaper announcements that Lila's first hospital birth was at St. Francis and her second was at La Crosse Hospital. In the United States, the medicalization of childbirth really accelerated in the 1940s. For the first time, more children were born at hospitals than at home. While this trend undoubtedly saved lives, it lengthened the time that mothers spent away from their partners and younger children; it also increased the rate of invasive procedures like cesarean deliveries.  

When I was little, my mother usually purchased either Zest soap (which was white) or Camay soap (which was light pink). I remember being fascinated by the color of Camay. In the 1940s and 1950s, using commercial bar soap in the bathroom was a solid marker of middle-class life. In rural areas, it was still a luxury for many families.  

For more information, see @hall2019a, @kunzel1993a, @swasy2012a, and @young2017a.  