# Chapter Forty-Five

Cleaning did not pay as much as being a cocktail waitress, but it was just enough. Myrtle Joyce had started school, so on weekdays Lila arranged to work from 4:00 to 11:00 p.m. It was brutal walking home from Emma's house late at night (especially with Alice getting so big and heavy), but the children loved her. Lila decided not to advertise in the newspaper. The first three months in La Crosse felt like a dream. Lila was making her own money and choices. Although she had not made a conscious decision to hide, her life was simpler without the Slabacks and the Schneiders; they had no idea where she was living.  

In mid-November, the bars and restaurants on French Island started putting up lights for Christmas. It gave the long nights a more festive and hopeful feeling. There were not as many soldiers at Camp McCoy now that the war was over, but there were still some; Carroll's was as busy as ever, especially on the weekends. One night, a soldier noticed Lila as she was leaving work and whistled to her from across the street. "Hey there, gorgeous! Why don't you come over here for a minute?" Against her better judgment, she walked across the street.  

There were three soldiers standing together in the parking lot, smoking cigarettes. Lila asked where they were from, and they offered her a cigarette, but when she turned to leave, one of them grabbed her by the wrist and whispered into her ear, "The fun is just getting started." He pulled her into a dark corner between the building and the dumpster, and one of the men put his hand over her mouth. "Just be quiet and this will be quick." She tried to get away, but they were too strong. While two of the men held her arms and legs against the wall, the other one raped her. Then they switched places. The struggle and the rough texture of the bricks ripped her coat in the back. The last one grabbed her hair and pushed her lower to the ground so he could force himself into her mouth. She tried to bite him, but one of them slapped her so hard that she nearly blacked out. How long was she trapped there? In her memories, it would seem like an eternity, but it must have been only a few minutes. It was the most violent thing she had ever experienced.  

As she walked to Emma's house after the attack, Lila was shaking. Emma noticed the rip, her messy hair, and the wet spots where her knees had touched her skirt, but Lila brushed her off. "It's fine&hellip;I'm just cold and tired. I'll be fine once I get the children home." It was snowing as they passed Carroll's. The soldiers were gone, but Lila urged the children to walk faster. When they got home, she tucked them into bed and said, "I'll be back in a few minutes." She locked herself in the bathroom and wept silently for hours, hoping the children would not notice.  

For a few weeks Lila managed to perform most of her usual routine: taking Myrtle Joyce to school, work, Emma's house, cleaning, feeding the children, and putting them to bed at night. But for her, sleep was elusive. Even when she fell asleep (which was not guaranteed), she often woke up in the middle of the night in a sweat with her heart racing. By early February, she was living in a constant fog. 

One day when she dropped the children off at Emma's house Emma said, "You look so tired, dear. Why don't you take a day or two off from work?" 

Lila looked down at her shoes. "I can't really afford to." 

Emma hugged her, and she felt so solid and warm. Lila reluctantly let go and waved goodbye to the children, who were looking out the front window.  

At the supper club, Lila had begun to work part of the time as a waitress. She found that her memory was not as sharp as it used to be. Even though she was writing the orders down, she sometimes forgot the extra little requests that customers made ("Could you bring me another cup of salad dressing, please?"). It was embarrassing. One day, the owner's wife asked if they could talk for a minute after the dinner rush. Lila said, "Sure, no problem," but her heart sank.  

Stella had grown her hair long and was pulling it back into a new style that she called a "French twist." Lila wished that she could be even half as elegant; Stella looked like a movie star. They were standing in the back hallway near the kitchen, and Stella leaned in. "Lila, I'm sorry to ask this, but are you pregnant?" Lila was stunned. She didn't cry or protest, she just froze. Why would Stella think that? She had been separated from Herman for months. "I don't think you should be working in this condition, Lila. If you can't work a little faster, I'll have to let you go." Lila nodded. The word "pregnant" rattled in her head for the rest of the shift.  

When she picked the children up from Emma's house that night she said, "You were right about needing some rest. I'm going to take the day off tomorrow." 

Emma smiled and said, "I'm so glad to hear that. You can bring the children over here if you want some time to yourself." 

"I might," said Lila with a chuckle. 

The next day after Myrtle Joyce left for school, she took Johnny and Alice to the playground at Copeland Park. She sat on a bench and watched them play---first on the swings and then on the slide. Johnny looked like her, but Alice looked more like her father. For the first time since leaving West Salem, Lila wondered how Herman was doing. What would he say if he knew she was pregnant again? Although she didn't think she wanted to go back to him, having another baby that was clearly not his would make it impossible. After the affair with Fred, he would never believe that she had been raped. She never told anyone about the attack; it was so traumatizing and shameful that she could barely admit to herself it had happened.

## Notes

Through DNA testing, I was able to help my aunt (Lila's fourth child) determine that her father was a soldier in the mid-1940s, one of two brothers from Idaho. I don't know the circumstances of her conception (that secret died with Lila), but sexual violence is a common tool of war that doesn't magically stop when soldiers return home.  

The experience of being raped has long-term consequences. As described by behavioral scientist @basile2005a [p. 110], 

> PTSD is the most common diagnosis for trauma victims and has been widely studied among rape survivors. PTSD is a psychological response to an extreme stressor involving threat of death or serious injury (Koss et al., 1994). Examples of PTSD symptoms include feeling numb, not being able to fall asleep or stay asleep, not being able to stop thinking about the traumatic event, and trying to avoid reminders of the traumatic event (Weiss & Marmar, 1996).  

As a married woman separated from her husband, Lila's fourth pregnancy would have a serious impact on her relationship and options moving forward. In many ways, it was the beginning of the end for her.  

For more information, see @basile2005a, @heineman2011a, @lilly2007a, and @lutz2001a.  