# Chapter Forty-Eight

By the end of October, Lila had regained some strength and decided to look for a job as a waitress; it was her best chance to earn enough money for another apartment. Emma told her that she could stay a little longer to save money. With a sprinkle of cornstarch, Lila wrestled her belly into a girdle; she felt enormous and very unglamorous. With some lipstick and her hair pulled back in her best attempt at making a French twist, she looked in the mirror and said to her reflection, "Well&hellip;here goes nothing."  

She steeled herself to go back to Carroll's. The tips had been good. If she could make enough money, maybe her family would decide that it wasn't so bad to be a single mother. To her surprise, when she went in the staff was completely new. Even the manager was new; there was nobody who remembered her. When she asked if they were hiring, one of the waitresses smiled and said, "I'm sorry, but we don't have anything right now." It was starting to drizzle when Lila walked across the street to the supper club. Maybe she could get her old job back. Stella saw her as soon as she entered and said, "Lila! I'm so glad to see you again." She gave her a hug, but then looked at her belly. Even with the girdle, Lila looked at least four months pregnant. In a more serious tone Stella said, "If you're looking for a job, I'm afraid I can't help. Things have been a bit slow." 

"That's alright," said Lila. "I'm sure I'll find something." 

As she turned to head out the door, Stella said, "Good luck dear. Take care of yourself."  

Reluctantly, Lila walked across the Clinton Street bridge. She wished that she could stay on French Island, but there were more jobs on the other side of the river. It took her three days to find a place that was hiring. It wasn't much, not like Carroll's during the war. It was a place for working men to get dinner and a beer. The most popular thing on the menu was a hamburger with deep-fried cheese curds. The owner's name was Hank. He loved to talk and could make friends with anyone. He knew everyone's name and favorite drink. Lila was starting to enjoy working there, but then one day she had to go behind the bar and Hank pinched her on the rear. When Lila flinched, he winked and said, "Tight squeeze back here." After that, she tried to avoid being around him. It was difficult in such a small place.  

As the snow began to fall, Lila's thoughts returned to Myrtle Joyce, Johnny, and Alice. How was she going to get them back? She had decided that she would start by visiting Myrtle Joyce and introducing the new baby. But when she arrived at Veda's house, she was shocked to find that Myrtle Joyce was not there. Veda was blocking the doorway and wouldn't let Lila inside. 

"What do you mean, she's not here? I need to see my daughter!" There was a tone of panic in her voice. 

Red emerged behind Veda and said firmly, "We took her to St. Michael's orphanage. She was too wild for Veda to handle with the rest of the children&hellip;you're not the only one with a new baby." 

Lila stood on the porch, stunned into silence. Veda's arms were crossed in a feeble gesture of protection against the cold.  

Looking past her, Veda said, "St. Michael's is on Market Street. Red will get the car and drive you there&hellip;take care of yourself, Lila." She gently closed the door. Although Lila didn't know it, Red was the one who had suggested taking Myrtle Joyce to the orphanage. Veda had reluctantly agreed; she knew it would break Lila's heart, but she really was overwhelmed with the baby. She also felt like she couldn't go against her husband's wishes.  

As Red and Lila rode in silence to the orphanage, Lila's mind was reeling. How could Veda do something so awful? Would she be able to see Myrtle Joyce? To keep her warm, she was holding Hazel inside of her coat. She had been asleep during the confrontation on Veda's porch, but now she was squirming.  

The orphanage was run by the Franciscan Sisters of Perpetual Adoration; Lila noticed a sign when Red dropped her off at the main entrance. A bell rang when she opened the door, and a tall nun wearing a black and white outfit stepped into the hallway. Lila had seen nuns when she went to church with Veda and Red, but she had never spoken with one. "Can I help you?" The nun's tone was more efficient than welcoming. 

"I believe you have my daughter, Myrtle Joyce." 

"Oh, I see." The nun looked her up and down. "Come with me. You can sit in the office, and I'll get one of the priests to speak with you." 

While she waited, she fed Hazel. Shortly before the priest opened the door, she felt a trickle of warm liquid from Hazel's diaper flowing down the front of her dress. She hoped the priest would not notice the smell.  

Father James was a young man, not much older than Lila. "What brings you here today, Miss&hellip;" he paused so Lila could answer. 

"Mrs. Schneider" she replied, thinking that he might listen to a married woman. "I came to find my daughter, Myrtle Joyce, who was brought here by my sister, Veda Metcalf." 

"I see," he said, turning towards the wall. "Give me just a moment to find her papers." 

Lila was not religious, but for a moment she prayed that Veda had listed her as "Myrtle Schneider" and not "Myrtle Slaback," even though that was her legal name. She held her breath until Father James said, "Ah, here's the folder." He spread the handful of papers on the desk and started reading. "It says here that your sister brought Myrtle to us because you were unable to care for her." He looked up from the desk and for a moment, Lila froze; it felt like he was staring into her soul. 

"I was," she said with her voice wavering. But then she took a breath and added, "It was supposed to be temporary&hellip;I came to La Crosse to give birth, but I ended up staying in the hospital longer than expected. I guess it was too much for my sister. She recently had a baby too." 

The priest looked down again. "So where is your husband, Mrs. Schneider?" 

Lila felt like she could barely breathe. "Herman is a farm laborer. He kept the younger children on the farm, but we thought it would be easier for Myrtle to stay with her cousins so he wouldn't have to drive her back and forth to school."  

She had no idea what Veda might have told the orphanage when she dropped Myrtle Joyce off. Feeling pressure to fill the silence, Lila said, "Now that I'm out of the hospital, I'm very anxious to get our daughter back&hellip;I'm sure Herman would like to have us home for the holidays." 

Father James pushed his chair back from the desk. "Well, I'm glad you're here, Mrs. Schneider. Many of the children at St. Michael's have been abandoned by their parents. It's very sad at this time of the year. I'll ask Sister Jerome to find Myrtle straight away."  

Lila pulled a handkerchief out of her pocket. She had stretched the truth, but her tears of relief were genuine.  

## Notes

Lila's children told me that she worked in bars. At the time, it was very unusual for a married woman with four children to work outside of the home. None of her sisters or brothers' wives had a career. I'm sure this is one of the reasons why Lila was the black sheep of her family. Even if they did not disapprove, how could they have understood her lifestyle?  

My description of the working-class bar owned by "Hank" is based on my experiences in bars, particularly as a child. I visited La Crosse many times, and my family regularly ate in a small-town bar in Fall Creek, Wisconsin called "Chicken Chasers." I have fond memories of eating their hamburgers and deep-fried cheese curds while my parents sat at the bar with their friends. Sometimes they had barrels of peanuts. You could eat as many as you wanted while throwing the shells on the wooden floor.  

As the oldest (and not one of Herman's biological children), Myrtle Joyce spent more time in orphanages than her siblings. The two options were St. Michael's (run by Catholic Charities) and the La Crosse Home for Children (run by the Social Service Society, a precursor to United Way). My mother and her two younger sisters lived at the latter, which was smaller and not as institutional. St. Michael's (where Myrtle Joyce lived) was much more cold and punishing. 

For more information, see @fcconline2024a, @burns-ardolino2007a, @cobble1992a, @fehribach2023a, and @reef2005a.  