# Chapter Forty-Six 

For weeks, Lila managed to avoid thinking about her waistline. But by the summer there was no denying it; she was pregnant again. She could feel the baby kicking. The first week of May, Stella handed her an envelope and said, "This is your pay plus an extra week. I'm sorry to do this, but you can't keep working here in this condition." Stella glanced down at the growing bulge in Lila's dress. "I worry too much about you&hellip;goodbye, Lila." And with that, she turned and left. It was only 4:30 in the afternoon. The dinner rush had not even begun. Lila gathered her sweater and purse and exited through the door marked "Employees Only."  

Her feet knew the way back to Emma's house, but her mind was elsewhere. What was she supposed to do now? Without a job, she would lose the apartment. Without the apartment, she would not be able to live on her own. Who would take her in? Veda? Herman? Her parents? Emma wouldn't have enough room for four more people. She was next to the gas station when another idea popped into her head. For a dime, she bought a cup of coffee and a newspaper and sat on the curb to look at the Help Wanted section.  

> | **WANTED**
> | Girl or woman for clerking and
> | waitress work. Hours 11 am -- 
> | 7 pm. Steady Employment. 
> | JUSTINGER'S FOOD STORE 
> | 700 West Ave. South

It was the kind of work she was looking for, but the job was too far from Emma's house and the apartment. Also, the hours would require Myrtle Joyce to walk home alone from school; it was too risky. "Girl for general housework." Lila was no longer a girl, but she also knew the job would never pay enough. "General office worker. Must have some knowledge of bookkeeping, State age, experience, and salary expected." Lila had never considered working in an office. She assumed it was the kind of work that required a high school diploma. Some of the ads made her wonder what the job was even about. "LADIES---Work in your spare time, realize big profits having fun." It made her laugh. She might have called out of curiosity if she had a phone. There was only one advertisement in the "Help---Men or Women" section: 

> | **CLOTHES** presser in our dry cleaning 
> | department. The Modern Laundry 
> | and Dry Cleaning Co.  

Lila had no idea what "dry cleaning" was, but she had seen the building on Caledonia Street; it was near Myrtle Joyce's school. Lila decided to go investigate. If she went to Emma's house before 10 p.m., Emma would know immediately that something was wrong.  

When she opened the door a bell chimed, and a man dressed in white came out of the back room. "Picking up or dropping off?" 

Lila felt sick to her stomach. "Neither." Nervously, she twisted the handles of her purse. "I'm here about the ad in the newspaper." Like Stella, the man glanced at her waistline. 

"Do you have experience with dry cleaning?" 

"No, but I've done plenty of laundry. I'm willing to learn." 

The man paused, clearly thinking it over. "All right," he said. "I need someone to press and help with customers. We're a little behind and the complaints are killing me. Can you work evenings?" 

"Sure," said Lila. 

"Great&hellip;come back tomorrow at 3:00, and I'll start training you." 

"Would 4:00 work?" Lila held her breath; she needed this job. 

"Yeah, sure&hellip;whatever." 

Lila was so relieved that she didn't ask about the salary or what the job would involve.  

There were five other people who worked at the Modern Laundry, three men and two women. Howard, the manager who had offered her the job, was constantly in motion---taking orders, moving bins of laundry from one area to the next, conferring about difficult stains and difficult customers---doing anything that needed to be done. No matter how hard he worked, his clothes were always immaculate. He said, "Nobody would trust a sloppy dry cleaner." Patrick and Charles had been in prison. Patrick was gaunt, and his face was always red. Sometimes, he came to work drunk, but he was such a wizard at dry cleaning that Howard let it go. Rebecca was older than Lila and had never been married. She was as strong as the men and always wore pants to work, which Lila found astonishing. It wasn't normal for grown women to wear pants outside of the home. Mary's husband had been in the war. A few months after returning home, he was sent to prison for killing someone during a bar fight. When customers yelled about stains and missing garments, Mary never yelled back. Sometimes, she would ask Howard or Lila for help so she could go compose herself in the back room.  

Lila's main job was to iron and get the clothes ready for pick-up. Ironing was hot, but at least she was working with clean clothes. Mary and Patrick had to figure out the stains. Mud or chocolate? Wine or urine? Lipstick or blood? It was a horrible game. Lila's starting wage was forty cents per hour. It was more than her pay as a waitress, but there were no tips. By the end of the month, she realized that she would have to tell Emma; she wasn't paying her much to take care of the children, but it was more than she could afford. What would she do without Emma?  

Sometimes while she was ironing her thoughts drifted to her recent choices. Was it really so bad on the farm with Herman? Was Veda right to be so harsh? Why did she cross the street and talk to those soldiers when she could have walked away? Was there any way that Herman would take her back? One day she was so lost in her thoughts that she dropped the iron on her foot. As Howard helped her put a dressing on the burn, he said, "You should buy some work boots. I should have told you that before." Lila knew he was right, but there was no way she could afford them. She could barely afford to pay the rent or the school fees for Myrtle Joyce. She picked up the iron and continued working.  

## Notes 

For this chapter, I did what I imagine Lila would have done as a newly unemployed waitress: I opened the newspaper (archival versions on [newspapers.com](https://www.newspapers.com/)) and checked the help-wanted advertisements. It was not very promising. Most jobs available to women were not a good match for Lila's age, experience, and/or qualifications.  

For several years while I was in graduate school, I worked part-time as a production weaver for Custom Woven Interiors in Minneapolis, Minnesota, a small business that makes high-end rugs and upholstery fabric. Like ironing, weaving can be very monotonous, allowing plenty of time for the mind to wander. I used it to think about my research, but Lila had much more pressing concerns: how was she going to take care of herself and four children under the age of six?  

For more information, see @foster1918a, @greenholt2023a, and @licht200a.  