# Chapter Forty-Seven

There was an unofficial code of silence at Modern Laundry: don't ask personal questions. Lila felt like her belly was ready to pop, especially around the scar from the c-section, but none of her co-workers said anything about her appearance, not even Howard. They all needed their jobs. It was better not to ruffle feathers.  

When she finally told Emma about the job at the laundry, Emma asked what she was planning to do about the baby. Lila closed her eyes. She didn't want to think or talk about it. Emma said nothing more and just waited, holding Lila's hand. The children were sleeping, and they sat on her sofa until Lila was able to squeeze out, "The doctor at La Crosse Hospital told me I need to go back there." 

"I guess the doctors know best," said Emma. "My babies were born at home, but my daughter Margaret says the hospital is better. She's also having a baby."  

By August, work felt like torture. Everything hurt---her ankles, her belly, and especially her lower back. It was so hard to stand at the ironing board for six or seven hours and then walk across the bridge to pick up the children. Lila would fall asleep as soon as they got home but often woke up after two or three hours. She used the time to bake, until one night she fell back asleep and almost burned down the apartment with a loaf of bread. After that, she stuck with cleaning. There was nothing else to do. She never liked reading and didn't have a radio.  

One evening at work, she felt even more uncomfortable than usual. It was like the baby was deliberately ramming its head into her bladder. When she went to the bathroom there was blood in her panties. It was time to go to the hospital. The children were safe with Emma, but she had done nothing else to prepare. Mary noticed her look of panic and asked if she needed any help. 

"Can you call me a cab to La Crosse Hospital? I think I have enough money in my purse." 

"Don't worry about it," said Grace. "I'll take care of it."

When she arrived at the hospital, the nurse asked if she had given birth before. Lila told her that she had, and the nurse left the room to get her chart. When she returned, she said with a scolding tone, "You should have come earlier, Mrs. Schneider. You could have died if you went fully into labor. We need to prep you for surgery immediately." Two orderlies were already in the hallway with a gurney. She was scared to have another c-section, but there was no time to argue. When she woke up, a different nurse was standing by the bed looking at her chart. "You have a healthy baby girl, Mrs. Schneider!" Lila closed her eyes again. She just wanted to sleep and forget about everything.  

That stay at the hospital was her longest one yet. She named the baby Hazel, after her mother. It seemed appropriate after naming Alice for Herman's mother. Since Herman didn't have a phone (and had begun working at a different farm, although Lila didn't know that yet), the hospital had reached out to his sister, Helen. It was obvious that the baby was not Herman's. They had not been together; the baby looked nothing like him. When Helen came to her room in the hospital it was like seeing a ghost. They had not talked for almost two years.  

Helen pulled a chair next to the bed and sat down. When she finally spoke, it was with a soft tone. "I don't know what happened between you and Herman, but I know how hard it is to raise a child on your own. You've been managing with three and now you have four." It wasn't a question. Lila wasn't sure where the conversation was heading. "I don't think you can do this by yourself, Lila. It's just too much." She looked down at the floor like there might be answers to Lila's problems hidden in the linoleum. Lila didn't know what to say. For a little while they sat there in silence, listening to the sounds of the ward---the phone ringing, babies screaming, patients being rolled down the hall. "I talked to your sister, Veda. She can take Myrtle for a while, and Herman can take John and Alice." Lila was stunned. Give her children away? For how long? Sensing her thoughts, Helen added, "It won't be forever&hellip;just until you can work things out. I'll make all the arrangements if you tell me where the children are." 

"Do I have a choice?" Lila said in a whisper. 

Helen gave her a compassionate look and said, "Not really." 

Was this how Viola felt when her children were taken away? Lila was terrified that she would never get her children back. Who would want to marry her now?  

When she was finally released from the hospital, she took a taxi to the apartment. There was a note on the door: "Your rent is overdue; pay now, or leave by September 30th." That was in three days. As Lila stood in the hallway staring at the note, Hazel started crying. After being in the hospital for two weeks, Lila knew she couldn't afford the rent. Would she still have a job? Doubtful. Once Charles had missed two days of work (for reasons that he never divulged), and Howard had nearly fired him. She unlocked the door and rocked Hazel as she walked around the apartment. The only piece of furniture besides the mattress was an upholstered chair that she had found sitting on the curb one day. There was a big hole on the side, but it was comfortable. She sat down to nurse the baby and thought about what she wanted to keep---her clothes, the bundle of letters and photographs, and a nice pot and saucepan that she had purchased at Woolworths. The plates and silverware had been left by a previous tenant, and the glasses were just jelly jars. She noticed a doll that belonged to Myrtle Joyce and burst into tears. The children didn't have much, but it took her hours to pack their things. She fell asleep hugging a sweater that had been passed down from Myrtle Joyce to Johnny to Alice. Herman's mother had made it.  

She wrapped everything into two bundles using the bedsheets. Unable to carry the baby and the bundles at the same time, Lila had taken another taxi to Emma's house. Emma said, "I'm so relieved to see you, dear. I was worried about you." She gave Lila a hug, and Lila melted into her arms, sobbing for everything that had happened to her and for everything she had lost---not just her apartment and the children, but her hopes of making a better life, a life where she could be free to make her own choices. Emma made a private place for her to sleep on the porch. She sunk into the little bed with Hazel and quickly fell asleep.  

A few days later at breakfast, Emma said, "Your cheeks are flushed. Let me check to see if you're running a fever." She put her hand on Lila's forehead and said, "I think you better see the doctor again. As soon as Laverne gets home, he can borrow a car from a neighbor." When they were out of the house, Lila asked him to take her to St. Francis. "Sure thing," he responded. She couldn't bear the thought of going back to La Crosse Hospital. The doctor at St. Francis was a tall, skinny man with enormous glasses. He gave her a prescription and told her to return in ten days. "It's a good thing you came in. You don't want to let an infection get out of control."  

The antibiotics worked, but Lila was exhausted. How was she going to look for another job? The days had become a strange jumble---both too fast and too slow. She felt guilty about living in Emma's house and not contributing to the chores. She felt even more guilty that other people were taking care of her children. "Veda must hate me." The thought rumbled around in her head like a pinball. She felt like she was running through deep snow, struggling so hard but making very little progress. When she returned to St. Francis and the doctor asked how she was doing, she said tearfully, "I'm so tired. I don't know how I'm going to do this." 

"I can give you another prescription," he said. "This one will give you energy, improve your mood, and help you lose the weight you gained during your pregnancy." 

The pills were for her thyroid, but the doctor didn't explain how they were supposed to work. The effect was so subtle that Lila decided it was not worth the expense. When the prescription ran out, she didn't refill it.  

## Notes

I could not have written this book as a younger woman. Many of my descriptions in this chapter are based on my own experiences with pregnancy (particularly my changing body and lifestyle). My last pregnancy was particularly stressful since the previous one had ended with a second-trimester loss. I was overjoyed when my son was born, but I was quickly overwhelmed trying to heal from a physically and emotionally stressful pregnancy while raising a two-year-old and a newborn. I wondered how my grandmothers had managed, especially Lila. When her fourth child was born, her oldest child (Myrtle) was still only five years old.  

I was diagnosed with a thyroid disorder (Hashimoto's disease) a few months after my last birth. I don't know when Lila was diagnosed, but my mother told me that she had a goiter---which indicates that she either went undiagnosed for a long time or was not taking her medication.  

For more information, see @brewer2011a, @davis-floyd1992a, and @solinger2000a.  