# Chapter Forty-Three

When Lila moved to West Salem, she had more than three hundred dollars in small bills stashed away from working. She had used some of it to purchase her wedding dress. Since the wedding, she had used a trickle of the money to stretch the household budget. Stationery and postage stamps. Her driver's license. A new pair of boots for Johnny after he lost one playing outside. (They never did find it.) A bit of lace to make a pretty dress that Myrtle Joyce could wear to church. Two pounds of coffee for the picnics. Nothing extravagant. Herman never said a word about it; she wasn't sure that he even noticed. By the time her affair with Fred Hicks was over, the stash was small enough to fit into an empty can of baking powder.  

Lila had fantasized many times about leaving the farm, but as the days of silence turned into weeks, her fantasies became more urgent. Should she take the truck and just drive to La Crosse? Would Herman follow her? Did she want him to? Where would she live? Should she take the children along? For a few days, she seriously considered just walking away---taking a train and getting out of Wisconsin, starting a whole new life. It was an appealing thought. She was only twenty-six years old. But then doubts crept in. What would happen to their children? Who would raise them? Would she miss spending time with the Schneiders? Would she miss Veda or the rest of the Slabacks or even just La Crosse? She felt like she was standing on the edge of a powerful river; she could get in and let the current carry her away to an unknown destination, or she could turn and walk back to solid land. Stay on the farm or move to La Crosse. Stay with the Schneiders or go back to Veda. For days, she wracked her brain for other options. She fantasized about standing on the bridge to French Island, steeling herself to jump into the river. It was such a dark fantasy that it made her shudder. She forced the thought out of her mind; it was a sin to think about ending your life. The children needed her. If she was gone, where on earth would Herman find another wife to take care of them?  

Lila was waiting for some kind of sign that it was time to decide. August was hot and dry, but in early September the weather suddenly turned gloomy. After several days of rain, Lila woke up to see a brilliant beam of light piercing the clouds. The light poured through the bedroom window and filled her with a sense of strength and purpose. It was the sign she had been waiting for---the day to take the next step. Herman had left to do the milking, so she went to the pump to draw a bucket of water. By the time she was heating the water on the stove to make coffee and give everyone a quick wash, she was humming a song that she remembered from long ago on the radio.  

They couldn't take much without arousing suspicion. It had to look like they were just leaving for the day to visit La Crosse. Lila filled a small bag with a change of clothes and some diapers for the baby. She put her hairbrush, a packet of letters, and the baking powder can of money in her purse. As they walked out the door, Myrtle Joyce sobbed, "We can't leave Kitty!" 

Her sense of panic almost made Lila turn back. Gathering her composure, she knelt and said, "Don't worry, Kitty will be fine. You'll see her again later." 

Johnny was more excited. When they got into the truck he said, "Go, mommy!" 

"Well, alright then," she replied as she pushed the button to start the truck's engine.

Lila knew that there was a train station in West Salem. She had decided that she would drive to the station, buy tickets to La Crosse, and leave the truck there. Somebody would figure out who the truck belonged to and let Herman know. What would happen next? Would he just go back home? Would he drive to La Crosse to look for her? She wasn't sure what she wanted him to do. She just knew that something had to change. Veda and Red's house was only three blocks away from the train station in La Crosse. When the train arrived, they would walk from the station to Veda's house and then she would figure out her next move.  

When Veda opened the door, she said, "Oh, Lila. I wasn't expecting you. Come on in." Myrtle Joyce and Johnny darted into the house to look for their cousins. "David is still at school, but the bus will drop him off in a couple of hours. I was just getting ready to make lunch." 

Lila stepped inside and said, "I can help if you like." 

Veda tilted her head to the side. Did she suspect that something was wrong? She straightened back up and smiled faintly. "It's kind of you to offer, but I can handle it. Have a seat." 

Lila put Alice on the floor. She had just started walking and immediately pulled herself up on the sofa. Lila took off her sweater and put it in the diaper bag. In the corner there was a new television set. Lila had never seen one before. At first, she thought it was a radio. Veda returned to the living room and saw her staring at it. "We got that a couple of months ago. Sometimes we make popcorn and invite the neighbors over to watch with us like our house is a miniature movie theater." 

"Oh, that's nice," said Lila. She suddenly felt like she had taken more than just a trip to La Crosse; she had stumbled into a new century.  

After lunch, Veda made tea. "I looked out the window, but I didn't see the truck. Did Herman drop you off?" 

Lila hesitated. Now the truth was going to come out, ready or not. "No, we took the train this time." 

"Oh?" said Veda. "Are you planning to stay for dinner?" 

"If that's alright with you," Lila replied. She took a sip of the tea. It was hot and burned the roof of her mouth. 

"Yes, of course that's fine." Veda put her hand out. "Lila&hellip;is everything alright?" 

Lila was starting to sweat. "Um&hellip;well, you see&hellip;we're moving to La Crosse. Just me and the children&hellip;without Herman." 

Veda's mouth fell open in shock. "What happened? Did he hit you?" 

"No, nothing like that," said Lila. 

"Then what? Did he have an affair?" Veda had set down her cup of tea and her eyes were open wide. 

Lila's stomach twisted into a knot. For a few seconds she was silent. They could hear the children running around and laughing upstairs. Quietly, Lila said, "I just couldn't keep living there."  

Veda stared at her. "I don't understand. Herman is your husband. You can't leave him for no reason." 

Lila looked down into her lap. Had she been wrong to leave? How was she going to explain this? Summoning her last bit of courage, she looked at Veda and said, "Could we stay here for a few nights? I can find a job and a place to live&hellip;it won't be for long." 

Veda's lips were tightly pinched. She looked both angry and concerned. "The children can stay here for a few nights. You need to take the train back to West Salem and straighten this out right away."  

Suddenly they heard footsteps on the front porch. It was David, returning from school. By the time the door opened, Veda had flipped to "loving mother." "How was your day, dear?" 

"It was good, Mom," said David. Before Veda could say anything more, he turned and said, "Hi, Aunt Lila." 

Lila raised her hand to say hello, but he was already heading upstairs to look for his cousins. When he was out of earshot, Veda turned back to Lila. "You should leave now. I don't know what you need to do to make this right, but your children will be fine. Just go."  

Lila picked up her purse. Without saying another word or looking back, she went out the door, down the steps, and started walking back to the train station. Her mind was blank. In the distance she could hear a whistle; a train was coming into the station. Should she buy a ticket and go back to West Salem? Instead of going to the ticket window, she decided to sit on one of the benches by the tracks. A train was getting ready to leave. An agent in a dark blue suit leaned out of one of the middle doors and said, "Last call for Rochester with service to Winona." Where would the train go after that? She sat on the bench for what felt like hours, watching the trains. Eventually, someone came out of the station to ask, "Ma'am, are you alright?" 

"Yes, I'm fine, thank you. I was waiting for someone, but it appears that they're not going to show today." She was astonished at how easily the lie tumbled out. She stood up and started walking in the other direction, away from Veda's house and toward the river.  

By then it was late afternoon. It was getting chilly, and the sun was low on the horizon. Maybe the children were eating dinner. Without even thinking about where she was going, she had reached Copeland Park. She walked past the playground---there were only a few children playing on the swings and the merry-go-round---and headed right down to the river. In a few minutes, she could see the Clinton Street bridge. Her darkest fantasy was coming to life.  

As she walked closer, she thought about an accident that had happened when she was a child. This bridge could only handle small cars, but there was a larger bridge on the south side of La Crosse. One day, a man driving a car passed out as he was crossing and collided with one of the support beams. It caused a big section of the bridge to collapse and fall into the water, and his car fell with it. He managed to get out and swim to safety, but two of his passengers drowned. Lila heard the story at the dinner table; one of her brothers (maybe Lyle) had read the newspaper article out loud. It gave her nightmares for months. The crash. Plunging into the river. Drowning while trapped in the back seat. Lila had walked over the replacement bridge many times, but she never really trusted it. The water below was always dark and churning.  

Lila sat on a boulder near the pilings. How long did she stare at the river? Her body was numb with the cold. The moon was nearly full. She could see its swirling reflection in the water. Subconsciously, she had hoped that a brilliant solution to her problems would spring to mind, but nothing came. Her mind was as numb as her body. She could hear cars going back and forth over the bridge, but nobody walked by. She was completely alone.  

Eventually, the sun crawled back over the horizon. With a sigh, she climbed up the bank and crossed over the bridge to French Island. Everything looked golden in the early morning light. She caught a glimpse of herself in a window. Her dress was dirty and wrinkled and her hair was a mess. She laughed out loud thinking, "I look like a banshee." Then she sat on the curb and her laughter turned into sobs.  

## Notes

For many couples, the household budget is a major challenge. It was for me. I often spent my own money on things for the kids and the house that I'm sure my husband never noticed. Money is a significant barrier for many women who want to leave a marriage. Many occupations (and the tax codes) are structured to benefit heterosexual, married couples and punish singles. Until the Equal Credit Opportunity Act was passed in 1974, women were not allowed to open a bank account without a male co-signer.  

This chapter is a pivotal moment in the book. Lila has decided to walk away from her life with Herman. She doesn't really know what she wants; she only knows what she doesn't want. She takes a leap of faith into the unknown, but will she have the courage to stay there?  

For more information, see @joiner2009a, @lamphier2017a, @spigel1992a, and @stark2009a.  