# Chapter Forty-Four

An older woman tapped Lila on the shoulder. "Are you alright, dear?" Lila looked up, and a tear dripped off the end of her nose. "Why don't you come with me? My house is just a few blocks away&hellip;you look like you could use a cup of coffee."  

The woman introduced herself as Emma as they walked to her house. It was extremely small, but the kitchen was cozy and warm. Emma took a frying pan off the shelf and set it on the stove. "How do you like your eggs, dear?" 

Lila took a seat at the table. "Oh&hellip;fried, I guess?" 

With a warm smile, Emma replied, "Fried eggs and toast, coming right up." 

Lila's stomach rumbled. Her last meal had been lunch at Veda's house. It was very quiet. For a few minutes, they listened to the sound of the eggs frying and a train whistle blowing in the distance. 

Lila was the one who broke the silence. "Do you live here by yourself?" 

"Oh no," chuckled Emma. "The girls are married now, but my husband, Edward, is at work and the boys are at school." 

"How many children do you have?" said Lila. 

"Three girls and three boys. The oldest, Margaret, is probably the same age as you." 

Quietly, Lila said, "I have three children. Myrtle Joyce, John, and Alice." 

"Oh, that's lovely," said Emma. "Children are such a gift."  

As Lila finished eating, Emma put her hand on Lila's arm and said very gently, "You seem to be having some trouble, dear. Is there anything I can do to help?" 

Lila's eyes welled with tears, and Emma offered her a handkerchief. When her throat stopped clenching, she said, "I don't know&hellip;I guess the first thing I need to do is find a job." She was staring at a smear of egg yolk left on her plate. 

Lila expected Emma to start asking questions and making demands, but Emma just said, "Well, now that your belly is full, let's get you cleaned up. I think I have a dress you can borrow. I'll wash the one you're wearing, and you can pick it up when you come back. Emma put a pail of water on the stove and showed her to a room with a sink and a mirror. "You can change your clothes here. I'll bring you soap and a washcloth as soon as the water is ready." Lila had a comb in her purse and started fixing her hair, avoiding her reflection in the mirror. The dress from Emma was not stylish, but it was clean. By the time she had washed up, the sun was bright overhead. Emma gave her a hug, and Lila walked back in the direction of the bridge. She had noticed that there was a new tavern on Bainbridge Street.  

When Lila pushed open the door, there were just a few locals sitting at the bar for lunch. It was dark and there was already a cloud of smoke in the air. She immediately wanted to leave, but the bartender said, "Is there something you need?" 

Swallowing, she replied, "I'm looking for a job as a cocktail waitress&hellip;I worked at Carroll's during the war." 

The bartender looked her up and down in a way that made her skin crawl. "Is that so? I might have a job for you if you come back tonight." One of the men at the bar laughed. Without saying another word, she turned and left. She might be desperate, but not that desperate.  

Carroll's was only two blocks away, but Lila resisted going in. She worried there would be nobody left who remembered her; worse, that somebody would remember exactly why and how she had left. Summoning her last bit of courage, she walked into the supper club across the street from Carroll's. She had never been inside before. The restaurant was on the edge of the water, and the entire back wall was filled with windows&hellip;the view of the water was impressive. 

"Would you like a seat at the bar?" 

Lila snapped back to attention and said, "Actually, I came to see if you were hiring." 

The hostess was older than Lila, but well put together. She was wearing a pearl necklace and a black dress with a sharply tailored white collar. She said, "I'll take you to the kitchen, so you can talk with the owner. I'm his wife, Stella." To Lila's relief, he asked how quickly she could start working.  

When Lila returned to Emma's house, her sons were home from school. She hugged Lila like they were old friends and invited her to stay for dinner. 

"That's so kind of you, but now that I've found a place to work, I need to find a place to live."  

"You can stay here for one night," Emma said. "Why don't you look for a place to live tomorrow when you've had some rest?" 

She had a point. Lila felt tears welling up again, but Emma put her hand on her shoulder and said, "It's no trouble, dear. Whatever problems you're having will work themselves out." Lila fell asleep on her sofa not long after dinner, and Emma covered her with a quilt. She slept heavily without dreaming.  

She left Emma's house early the next day, hoping to find an apartment and buy some new clothing before starting her shift at 4:00 p.m. It was easier than she had expected to find a place to live. It wasn't much, but she could afford the deposit of one hundred dollars. It was on Rose Street, not far from the boarding house where Lloyd had lived. The rent included water, heat, and electricity. The restaurant did not require uniforms, but Lila realized that she would need to be more stylish if she was going to work her way up from washing dishes to being a waitress again. She purchased a long, gray skirt, two white blouses, and a cheap pair of black pumps that caused terrible blisters until she could afford to replace them.  

Her next goal was to bring the children back to the apartment, but when she went to pick them up, Veda asked sternly, "Who exactly is going to watch them while you're working?" Lila had hoped that Veda might offer to help. It was crushing to leave her house (alone) for a second time. As she walked out the door, Johnny screamed "Mommy&hellip;Mommy, don't go!"  

Emma had invited her back for dinner that week. Lila offered her two dollars, but she refused to take it. "You're going to need that for your children, dear." As they worked together on preparing the meal, Lila decided to ask Emma for advice. It felt strange; she had been able to confide in Lloyd, but his problems were always so much worse than hers. Lila worried that she was asking too much. 

Emma turned from the stove and said, "You could put an ad in the paper for a childminder, but why don't you bring the children here while you're working?" 

"Really?" said Lila. She could hardly believe the depth of Emma's kindness. "That would be so helpful, and the restaurant is nearby." 

"That settles it then," said Emma. I'll cover the first two weeks. After that, you can hire someone, or pay me whatever you think is fair." 

## Notes 

When I reconnected with one of my mom's sisters in early 2020 (just before the pandemic), I was astonished to learn that Emma was the children's babysitter. I have no idea how she and Lila met, but I have such fond memories of visiting Emma at her little house on French Island. She was an incredibly kind and gentle person. If anyone could have saved Lila from herself, it would have been Emma.  

In my research for this book, I learned that Emma had a difficult childhood. Her father was forty years older than her mother; Emma was born when her mother was sixteen years old. Her parents had two more children (both girls), but the second one died when she was only two years old. Emma met her first husband as a teenager when she was working as a servant on his parents' farm. I imagine these hardships are what made her able to help Lila without judging her.  

I was heavily pregnant when my firstborn child was two years old (nearly three). She had been co-sleeping with me, but I decided that I needed to make room for the new baby. So, one night, I tucked her into bed in her bedroom (which she had never slept in) and closed the door to her room. For an hour she cried and banged on the door with her tiny fists, screaming, "Mommy, my best friend, Mommy!" It was heartbreaking. I recalled that memory as I imagined Lila having to say goodbye to her children for a second time.  

For more information, see @fine2008a, @paules1991a, and @polakow1994a.  