# Chapter Forty-One

Winter started early that year. Myrtle Joyce was the first one to notice the snow falling. "What is that, Mom?" The flakes were so small that they were barely visible, but by November there was enough snow on the ground to make a snowman. Just when Lila was starting to feel like she couldn't take being a mother for one more day, the winter gave her relief. Fall had been rainy and muddy; the colder temperatures froze the ground. It was cold going to the outhouse, but it was easier to keep the house clean now that they were no longer tracking mud all over the floors. During her last trip to La Crosse, she had purchased coats and boots for the two older children. Alice was already big enough to wear Myrtle's coat from the year before. Evelyn had given her some handspun yarn. Although Lila had not done any knitting for years, she managed to make some basic scarves, hats, and mittens. They were ugly but warm.  

Once the silage and hay were safely stored away for the long winter, Herman had more time to spend at home. He started taking the children out for walks---to climb on the bales of hay, to see what it was like in the barn (Myrtle Joyce had been worried that the animals would freeze), to see how the ice was forming on the creek, and to go sledding once there was enough snow. He made snowshoes using strips of hide and wood from an old barrel. Lila watched from the window as he taught the children how to use them; it was funny to watch them tripping over their own feet, but John was competitive with his older sister and determined to be the first one to figure it out. The look on his face when he did was pure delight.  

Lila had stopped going to church after Alice was born. Herman went from time to time, but the children couldn't go with dirty clothes. They couldn't go if they had refused to eat that morning or if they didn't get enough sleep the night before. They might cry in church, which would be embarrassing to the whole family. Lila might have been able to manage it with help, but with Alice needing so much support there was nothing left for Gladys and Nora to give. It was heartbreaking to watch her mother-in-law's decline. She could no longer hold or even talk with her beloved grandchildren. Myrtle Joyce was too young to remember what she was like before the stroke. During one visit, she asked, "Who is that scary woman in the corner?" 

Lila was mortified. Gladys gently took Myrtle Joyce and Johnny by the hand and said, "Why don't we go play outside for a little while?" 

The Schneiders were always kind, but remembering the incident made Lila feel like she wanted to disappear.  

Carl and Gladys married in December, but there was already too much snow to drive the truck. Lila was sad to miss it. She had hoped they could visit West Salem for Easter, which was at the end of March. The snow had started to melt, but then there was a blizzard. "In like a lamb, out like a lion," said Herman as the children watched through the kitchen window. Lila cooked a ham for the occasion, but it didn't feel like much of a celebration. A week later, Alice died at home in West Salem.  

That spring there was a new postman. He was younger than "Rudolph" and had striking white-blonde hair. The first time he came to the house, he smiled and said, "I'm Fred Hicks and you&hellip;must be very busy!" Lila had taken the children outside for some fresh air, and they had discovered the mud around the water pump. She took the letter (which had Veda's handwriting) and dashed into the house without saying a word; by the time she returned, he was already gone. A few days later, he delivered a letter from Gladys. When Lila answered the door, she said "Hi, I'm Lila." Replaying the moment in her mind that night, she kicked herself for being so stupid. He knew her name already; it was on the letters. Two weeks went by before Fred returned for another delivery. Surprisingly, he said, "Do you like jokes? I have a joke for you."  

> One Sunday at church, the pastor was giving a sermon about forgiving your enemies. He said, "Raise your hand if you can forgive your enemies." Only half of the men and women raised their hands. Undeterred, he kept speaking. After ten minutes, he asked the same question. This time, three-quarters of the congregation raised their hands. Another ten minutes went by, and he was really getting into it! He asked the question again, and everyone raised their hands except for one person. 
>
> "Mr. Olson," he said with obvious frustration, "Why are you so unwilling to forgive your enemies? Surely, after living for eighty-six years, you should be able to do this with ease!" 
>
> "I can forgive," replied Mr. Olson, "but at this point&hellip;all my enemies are dead!" 

The joke was not that funny, but Lila laughed. She had not heard a joke in such a long time. It felt good to laugh again. 

Fred's joke got her thinking about jokes she had heard from Lloyd and from the soldiers. Many of them were not appropriate to tell around the children, but by the time Fred returned she had thought of one that was not too bad.  

> A man walks into a courthouse and tells the clerk that he wants to change his name. The clerk is busy with filing, so he says impatiently, "Alright, what is your current name?" 
>
> "Adolf Cockburn," the man replies. 
>
> In shock, the clerk stops filing. Feeling more sympathetic, he pulls a form out of a drawer and says, "What name would you prefer to have?" 
>
> With a smile, the man replies, "James Cockburn." 

Fred turned red in the face. Just when Lila thought that she had really offended him, he started laughing so hard that he couldn't speak.  

That spring, Alice and John started teething at the same time. A less experienced mother might have thought it was just a cold, but John was sucking him thumb again. Alice was starting to pull herself up and was gnawing on the edges of the bed frame. They were feverish, cranky, and hardly sleeping. Somehow, Myrtle Joyce was able to sleep through it, but Lila and Herman were not. After a week of losing sleep, Herman said, "We really need to slow down on having children." Lila agreed, but when they were not intimate, she felt like he was slipping away; it was the only way she felt truly connected to him.  

It was calving season, and Herman was spending longer days in the barn. She was never alone, but there were many times when she felt lonely. She yearned for some real conversation with another adult. Even when they were together, Herman still didn't talk much.  

Fred and Lila continued trading jokes. One day he said, "I'm allowed to have some time off for lunch. Would you mind if I sat here and ate with you?" When Lila didn't respond right away, he added "I don't mean to impose&hellip;I have a sandwich in my bag." 

Lila smiled and said, "Sure, let me make you some coffee to go with that." 

For several weeks they ate lunch together outside. The children enjoyed having "picnics" with Fred. Myrtle was just big enough to help by setting the plates on the blanket. It was something to do in the mornings. And then one day, he arrived during a thunderstorm. Fred knocked on the door to deliver the mail and said, "I guess I better go. It's too wet to eat outside today." 

Lila felt like her heart was falling into her stomach and quickly said, "No, don't go&hellip;you can come inside."  

The wind had picked up and it was rattling the windows. Alice was giggling as her older brother jumped on the bed, but storms always made Myrtle Joyce nervous. As soon as Lila was done making the coffee and sat down at the table, Myrtle Joyce climbed into her lap. Fred didn't seem to mind the chaos. He swallowed a bit of his sandwich and said, "So&hellip;you told me that you grew up in La Crosse. Where did you go to school? What kinds of things did you do for fun?" Herman was not interested in the past or the future, only in the present. He had never made Lila feel guilty for her bad choices, but he had also never asked what her life was like before they got married. At times, his silence felt uncaring. Being with Fred was different. It reminded her of being with Lloyd. She told him about going to the movies for the first time to see *The Wizard of Oz*. He had never seen it. As she described the film, he listened with rapt attention and laughed at her imitation of the Wicked Witch.  

Myrtle Joyce had fallen asleep in her lap. Fred said, "I guess I should get back to work now&hellip;the mail won't deliver itself." Lila began to push her chair back from the table, but he said, "No need, I can let myself out." He leaned over and kissed her on the forehead. It was so quick and unexpected. Before she could say anything, he was halfway out the door. She knew the kiss was wrong, but she wanted more of them.

## Notes

This chapter draws from my own experiences growing up as a child in northern Wisconsin. I remember how magical it was to see the first snowfall of the year. When I was in elementary school, my mother knitted scarves, hats, and mittens for me and my sister. (She was good at it, but homemade clothing was not very "cool" in the 1980s.) I learned the phrase, "In like a lamb, out like a lion," in my first-grade classroom.  

I also remember visiting elderly relatives who lived in nursing homes. My mother pointed out that they were so happy to see me (a child), but I was unsettled by their stares and touches.  

Lila is still struggling with living on the farm, especially with three small children. She is more isolated than ever from other adults; this is a common experience for young mothers. I have no idea what her relationship was like with my grandfather, but I imagine the hard work of raising small children was draining on their marriage. She may have been looking for a way out. This chapter reminds us of her sense of humor.  

Rural mail delivery was not guaranteed by the U.S. Postal Service until 1902. Even then, rural mail carriers were allowed certain flexibilities that urban carriers were not.  

For more information, see @gallagher2016a, @harris2018a, and @perel2017a.  