# Chapter Fourteen

The day of Earl's funeral was the day everyone's childhood came to an end. Hazel and John were both crushed by the loss of their son. For John, it called his choices into question, especially the decision he had made to stop farming and move the family into the city. Would Earl still be alive if they had stayed in Crawford County? There were dangers everywhere, but the city was filled with vehicles and that was the cause of Earl's death. Although everyone knew that the accident was not Theron's fault, Hazel quietly blamed him. He should have looked for Earl before driving off. What had possessed him to be so careless? Theron blamed himself too, but Lila would not know that until years later. He stopped coming by for breakfast and started parking the truck on the street in front of his own house instead of pulling it into the garage. It seemed like their father barely noticed; a few weeks after the funeral, he stopped working. He didn't have the energy. Lyle took over the business, and Cecil dropped out of school to help. 

For a few weeks after the funeral, the family had a steady stream of visitors; friends and neighbors stopping by to check on them, often with a casserole. (Many of the dishes were good, but Lila would never think about casserole the same way again). Viola and Myrtle came to visit with their mother, who made a beautiful sour cream and raisin pie. Although her parents didn't know them very well---Myrtle was in the grade between Lila and Earl---it was a good day in the Slaback house when they visited. Everyone was dressed; nobody was crying or yelling. When Mrs. Johnson said that she was "so sorry about what happened" and to let her know if there was anything she could do to help, her mother said, "Thank you so much for your kindness. We're managing." Lila knew that was not the truth, but her mother was too proud to ask for help. If someone offered something specific, ("Let me bring some extra jars of pickles for your pantry"), she wouldn't say no. Everything else, they would take care of themselves. It was an unspoken rule. Eventually the visits stopped, and the offers of help faded away. Everyone assumed that the Slabacks must be "doing fine" if they were not asking for anything.

Truthfully, they were not doing so fine. When their mother started drinking (which was easy now that Prohibition was over), Veda became the de facto head of the household. If Looy had been younger, she might have dropped out of school to take care of him. Thankfully, Looy was just old enough to start attending school in January. Veda was nearly fourteen and could do everything necessary to keep the household running, including the laundry, taking care of the garden, preserving food for the winter, and making sure that Lila and Looy were going to school. Lila took charge of making the beds, cleaning the bathroom, and cooking breakfast for everyone. Their mother usually made oatmeal, but Lila decided that toast would be easier. She could make bread for the whole week and toast a whole tray of slices under the broiler. With some jam, tea, and hard-boiled eggs, it would be a complete and nearly instant breakfast for the whole family. Nobody said a word about the change. A lot of things were changing. 

Underlying the emotional depression going on in their house was the Great Depression. Lila could barely stand listening to the news on the radio---strikes, soup lines, banks going out of business, organized crime, unemployment, terrible dust storms in Kansas---there seemed to be no end in sight to the difficulties the whole country was having. Although Aunt Hattie had worked as a waitress and her daughter worked at the Electric Auto-Lite factory, Lila realized that married women were not "supposed" to work outside of the home. Her teachers said that if every family had just one job per household, the problem of unemployment would be solved. Married women should stay home to take care of the cleaning and children and leave jobs to the men. Lila spent many hours thinking about it while she did chores. Her parents were married, but at the moment neither one was working. Did "odd jobs" count as jobs? If so, there were two people working in her house (Lyle and Cecil), but they were supporting seven people. Shouldn't there be some kind of allowance for the size of the family? Did farming count? Lila wished that chores counted as jobs. She would be rich if she could get paid for doing housework. 

Sometimes she fantasized about what it would be like to be rich. She would have a big fancy house---like the gray-and-white one next to the streetcar line heading downtown, which had a big tower over the porch (just like a castle!)---and it would have stained glass windows and beautiful rugs and feather pillows. She would have three cats (Annabelle, Izro, and Nora), and she would hire boys and girls from poor families to do all the chores---that way they could afford to stay in the city and not leave for somewhere else. It was hard saying goodbye to friends. As a rich person, she would never have to do laundry again and could eat cake and ice cream every day for dinner. She would buy all of her clothes at Doerflingers and tell the elevator man, "Third floor, please," like it was the most natural thing in the world. She would have a car and Veda could be her "show-fur." Lila giggled thinking about that one. What a silly word for someone who drives a car for other people. One day she was so busy fantasizing about being rich that she burned the toast. Nobody said anything at breakfast, but internally she kicked herself for the rest of the week. She would have to be more careful about getting lost in her thoughts.  

## Notes

In northern Wisconsin, casserole---also known as "hot dish"---is a classic food to give a family that is grieving, recovering, or overwhelmed with life. While it's possible to make it and eat it at home, it's more common to give it away. Casseroles are designed to be inoffensive and easy for the recipient to reheat. Sour cream and raisin pie is a classic dairy-based dessert from Wisconsin that my father's mother used to make for Easter. This scene is the second time Viola and Myrtle appear in the book. It gives us insight into the mindset of the Johnson family and how they were willing to offer support to less-fortunate neighbors.

I can only imagine how the Slaback family's process of grieving must have been compounded by the struggles of the Great Depression. One of my father's aunts (who was born in 1921, the year before Lila) talked about the Depression from time to time when she visited our home on Friday evenings to play cards and chat with my mother. One night she voiced the idea (expressed in this chapter by Lila's teacher) that there should be "only one job per household." As a young woman she had worked as a teacher but had quit when she got married. That was the social expectation at the time, for women to be homemakers and not work outside of the home. 

In the 1930 US Census, enumerators were instructed to use one of the columns to identify the "head of family" and "homemaker" for all single-family dwellings: 

> 132. Home-maker.---Column 6 is to be used also to indicate which member of the family is the "home-maker," that is, which one is responsible for the care of the home and family. After the word "wife," "mother," or other term showing the relationship of the person to the head of the family, add the letter "H," thus: "Wife---H." Only one person in each family should receive this designation. 

Lila might have coped by daydreaming. In this chapter, she dreams what it would be like to be rich and to take care of the people who are important to her (like her classmates, friends, and her sister, Veda). It gives her relief from reality, but it also causes some trouble and disconnection in her real life. This foreshadows events to come.  

For more information, see @census1930a, @cobble2004a, @keesecker1934a, and @mcelvaine2009a.  