# Chapter Four

That fall, there were two big changes. At the beginning of September, a new baby came to live in the Slaback house. Lila had noticed that her mother was getting bigger, but she didn't really understand why. She was only two years old when Earl was born. (She didn't know it, but her older siblings had learned about pregnancy by watching the cows on the farm. Lila and Earl were the only members of the family surprised to get a new brother.) Looy hardly slept. For the first few months, it seemed like he would never stop crying. He was healthy, but his little face would get dark red and he would cry for hours. The only way to soothe him was to bounce him or take him outside for a walk in the fresh air. All he did was cry and throw up and make stinky diapers. Looy's arrival made Hazel even more impatient and angry than usual. 

The second big change impacted Lila more directly. A few weeks after Looy's birth, John took Lila, Veda, and Cecil to register for school. Lila had not been old enough to attend when they lived in Crawford County, so it was a new experience. She had a lunch pail that Izro had filled with an apple and some sandwiches wrapped in a piece of cloth. The school was so big that there were many different classrooms. Lila was shocked when her brother and sister were led away to other parts of the building. She would be in first grade and was assigned to Miss Miller as a teacher. One of the women from the office took her hand and said, "Come with me, young lady." They walked down a long hallway past several other doors and the woman said, "This is the one!" There were many other children already inside the classroom. Miss Miller was standing at the front of the room and asked her to sit at one of the desks. Lila chose a seat next to a girl with freckles and curly red hair. She smiled and the other girl smiled back. The desk was smooth, with curlicues of metal on the sides. Most of the room was filled with desks lined up in neat rows. Lila would spend many hours running her fingers around the curlicues to pass the time. The boys liked to sit in the back so they could make jokes and cause trouble, but Lila was determined to be a good girl and sit quietly in her seat. 

Miss Miller had all the letters of the alphabet written on the blackboard and asked the students to copy her writing on their slates. Lila was astonished to realize that her desk had a slate and two pieces of chalk inside&hellip;every student had one. Even more astonishing was the next week when Miss Miller handed out books: they were blue, and she gave a copy to every student. Lila had never held a book. She knew about reading---her parents and older brothers sometimes read aloud from the newspaper while the rest of them listened. Miss Miller said, "Please keep these inside&hellip;" but Lila barely heard her instructions. The book was filled with colorful pictures of animals and children. The first story was about two children and a mother cat. She thought they must be on their way to church; the girl had a big white bow in her hair, a frilly white dress, and blue socks. Lila didn't have such fancy clothing, but she was satisfied with her appearance. She was more interested in the pictures of the animals. 

During lunch, Lila was relieved to see her sister and brother and many of the children from her neighborhood. Some of the boys were playing a rough and silly game of Red Rover. She quietly ate her sandwiches, not talking or being asked to talk---nothing out of the ordinary. At home, her parents and older brothers did most of the talking. They talked about the new truck (which was for work, not for the family to ride in), what lumber mills had the best prices, where they could sell the extra vegetables from the garden, who was building a new house two blocks away, and when they might have guests over to play cards. Even if Lila had a chance to speak (which was rare), the adults were not interested in that scary dog on the next block, what kind of cookie was Lila's favorite (chocolate chip), or what happened at school that day. The world was a place for adults and Lila would just have to wait her turn.

## Notes

Loyal (Looy) was the first member of the Slaback family to be born in La Crosse. My younger child had colic due to a severe dairy intolerance, so that experience informed my description of Looy's behavior and how it impacted the rest of the family. I was losing my mind from lack of sleep. I don't know what I would have done if I had seven other children! 

Roosevelt Elementary, named after Theodore Roosevelt, was the neighborhood school for young children on the north side of La Crosse. In Crawford County, the local school stopped at eighth grade; there was no high school in the 1920s. The 1940 census notes that John Slaback dropped out of school after fifth grade; Hazel dropped out after seventh grade. The two oldest children, Theron and Izro, finished school in eighth grade; they were too old to enroll in high school when the family moved to La Crosse. 

I used [archive.org](https://archive.org/) to look at historical examples of elementary school textbooks from the early 1900s. It is impossible to know exactly what textbook(s) Lila learned to read from, but two possibilities are *McGuffey's First Eclectic Reader* and the *Elson-Gray Basic Reader* (better known as the precursor to the "Dick and Jane" books). 

As a small child, a family member gave my parents a set of old-fashioned school desks. The first part was just a seat, and the last part was just a desk---they were secured to metal tracks and were clearly designed to be placed in longer columns. They were painted red with black wrought-iron curlicues on the sides. It was easy for me to imagine what a 1930s classroom might have looked and felt like. Red Rover was a game I played as a child. My children played it too. 

At the dinner table in my household, I was expected to be "seen and not heard." Conversation revolved around adult topics. Card-playing was a common entertainment for the adults when I was a small child. My parents taught me to play games like cribbage, rummy, spades, King's Corners, and solitaire. We had a television, but there were only a handful of channels. 

I spent a lot of time reading as a child; my dad often took me to the public library to feed my appetite for new books. My older child is dyslexic; I've often thought about how boring and frustrating my childhood would have been if I did not have books for entertainment. I don't know if Lila was dyslexic, but learning disabilities were barely recognized back then.

For more information, see @lacrosselibrary2022a, @hinshelwood1917a, @kelly2017a, and @katz2012a. 
