# Chapter Nineteen

When Veda and Lila went back to school in January, Viola Johnson announced that she was dropping out of school to get married. It was not the first time this had happened; the first was Lila's friend, Kathleen, who got pregnant when she was fifteen. Her boyfriend, Michael, was only sixteen, but their parents---who were all Catholic---insisted that they fix the problem immediately by getting married. Lila had attended her wedding. As she had always dreamed, the wedding was big and so was her dress. Despite being "knocked up," it was a beautiful day. The church was packed, and Kathleen was radiant. Two years later, with two children and a third on the way, she still claimed that she was thrilled with her new life. Lila wondered if that was really true; her own mother was never thrilled by anything. Kathleen and Michael were living with his parents until they could save enough money for a house of their own. 

Unlike Kathleen, who was nearly the same age as her husband, Viola's husband-to-be, John Schneider, was several years older. How did they meet? Viola wouldn't say. Everyone knew that her first love was Samuel Collins, but her father wouldn't give Viola permission to marry (or even date) one of those dirty Irish Catholics. Later, Lila heard that Viola's father had discovered that Viola and Samuel were holding hands and passing love notes in school. His solution was to find her a good Lutheran man and get her married as quickly as possible. The fact that she was months away from getting her high school diploma made no difference. Even Viola's mother agreed that it was a waste of time for a woman to plan a career; Viola should be planning to have children and then stay home to raise them. Viola was a good student, but she was also a good girl. She knew it was no use arguing with her parents. A few months later, her sister Myrtle also decided to drop out of school and marry John's younger brother, Carl. Myrtle had never dated and was giddy to be a "real woman."

Like Viola, Veda was also a good student. She had her eyes set on finishing her degree and becoming a nurse, not on dating. As a result, she was the first member of the Slaback family to graduate from high school. Lila thought her parents should have been proud; curiously, they were indifferent. As long as Veda continued to do her chores, it didn't seem to matter what she did with the rest of her time. They never said that school was a waste of time for a woman, but they also never encouraged her to pursue anything besides getting married. (To be fair, they also never encouraged the boys to finish school or to get a job outside of the family business.) Veda reasoned that she would need to work for at least one year to earn enough money for nursing school, so she applied to work as an usher at the Riviera. Lila thought it was a brilliant move. She could earn money and watch the movies for free.
	
That job was where Veda met Red. He was two years older than Veda and was living at his uncle's house until he could afford to move out. At the end of her first shift, Red offered to walk her home. "You never know what kind of hooligans might be roaming at night, waiting to take advantage of a beautiful young woman like yourself." Veda blushed and accepted his offer. Although his real name was Francis, everyone called him "Red" because of his hair. His parents were Catholic and had ten children. Red was the oldest one; he had moved to La Crosse to find work. Veda couldn't stop talking about him. Red is so handsome! Red has such a funny laugh! Did I tell you what he said about that new Disney film, Pinocchio? 

One day Lila stopped her in midsentence and said, "Veda, I'm tired of hearing about Red all the time. Are you in love with him or something?" 

Veda's mouth dropped open, and she said, "Yes, I suppose I am." 

They decided to invite him for dinner. Veda said she was nervous, but they agreed that there was no point in trying to keep a relationship secret; someone in the family was bound to find out eventually. Why not just get it out in the open? It was January, so they decided to have him over on Sunday and make a big, hearty pot of beef stew. Veda said she heard that "the way to a man's heart is through his stomach." It might not be true, but why take chances? Although they didn't tell anyone that Red was coming over for dinner, the whole family was there, even Cecil and Gladys and their daughter, Deanna (who Lila's mother said was "totally spoiled"). He rang the doorbell promptly at 6:00 and Lila answered the door. She had imagined that he would be tall and handsome, but aside from having red hair and freckles, he was actually pretty average. Lila wondered what Veda saw in him. Red politely asked, "Is Veda home?" and Lila stood aside with a sweep of her arm, indicating that he should enter.

Dinner was oddly quiet. Lila wondered if Red was going to ask for Veda's hand, but it seemed that he was truly just there for dinner. As usual, her father and brothers talked business. One of their neighbors was moving to Iowa to be with her daughter (who had five children and another one on the way); she had hired them to fix all the woodwork and refresh the plaster. It was an old house, so there was plenty of work to do. Finally, her father said, "So&hellip;Red, is it? Tell us a little about yourself."

He went back to eating his stew, and Red stammered, "Well, I guess there isn't too much to say. My parents are farmers; they live in Marquette County, about halfway between La Crosse and Sheboygan. I came to La Crosse to look for a different line of work&hellip;I supposed I'm not too interested in being a farmer." John's father nodded his head; it was the same choice he had made years earlier. 

Lila's mother spoke up and said, "Do you have any brothers or sisters?" 

"Yes ma'am, four brothers and five sisters. I'm the oldest." 

Veda (who was usually silent at dinner) spoke up and said, "We work together at the Riviera Theater." 

And surprisingly, that was it. As soon as Veda spoke, the conversation moved on. They had chocolate cake and coffee for dessert. Red said that he "better get going" and Veda walked him to the front door. Did anyone notice that Veda was in love?  

When they cleared and washed the dishes, Lila noticed that Veda had regained some of the color in her face. Veda said, "Well that went alright." 

Lila said, "Yeah, I guess. What are you going to do now?" 

Veda said, "I don't know. Keep working together, keep walking home together&hellip;watch movies." Lila thought it sounded pretty boring. Why settle for the first man who showed an interest when you were as beautiful as Veda? Scarlett O'Hara didn't settle for Rhett Butler just because he wanted her to.  

## Notes

In the 1930s and 1940s, it was not unusual for teenagers in the Midwest to drop out of high school, especially if they were getting married or if the family needed them to work. Girls in particular were not strongly encouraged to finish school. Census records tell me that Viola married as a teenager. Her husband, John Schneider, was several years older and had been out of school for years; it seems unlikely that they would have met without family intervention. I have no idea if Viola had a crush on an Irish Catholic classmate, but many Protestants in the US viewed them with deep suspicion and would have considered such a match to be highly inappropriate.  

I learned about Francis "Red" Metcalf and his family mostly from the 1940 US Census. Veda and Lyle were the first members of the Slaback family to pursue recreational dating; Veda just settled on a partner more quickly than her older brother. Unlike John and Hazel Slaback, Red migrated to the big city on his own before getting married. 

American author and journalist Franny Fern (1811--1872) is credited with coining the now-common advice, "The way to a man's heart is through his stomach."

For more information, see @dolan2010a, @snyder1993a, @syrett2016a, and @warren1992a.  
