# Chapter One 

Lila was five years old when her family moved to La Crosse. She told her doll, Elizabeth, "Don’t be scared. I won’t let anything happen to you." There was barely enough room in the wagon for everyone to sit. Izro made her sit in her lap. She didn’t want to---she wasn’t a baby! Earl, who was only three years old and the real baby of the family, sat in their mother's lap. Izro whispered into her ear, "Are you excited about getting on the train?" She nodded her head. Her parents had been planning this trip for a long time. They were moving to a new house in the big city. Lila could tell that everyone was excited.

In truth, Lila was also sad. She was thinking about her cat, Annabelle, and how she would never see her again. One of the cats that lived in their barn had a litter of kittens the year before. Annabelle was the only one that survived. She was a tiny ball of gray fluff when Lila picked her up and carried her into the house. Her mother ordered her to take it back outside, but Lila was in love. The kitten was so soft and had beautiful green eyes. She kept sneaking the kitten back into the house until finally, her mother gave up and said the cat could stay. Lila fed Annabelle scraps from her plate until she was old enough to hunt for mice. She didn't stay in the house very long. Lila looked for her whenever she went outside. There were plenty of other animals around the farm, but Annabelle was the only one that was truly hers. That morning with all the commotion, Lila had not been able to find her. She looked in the barn, behind the house, under the chicken coop, down by the creek---everywhere she could think of---but Annabelle was not there. (She didn't know it, but Annabelle was hiding with her first litter of newborn kittens.) She was too old to cry about it. Her brothers would have teased her for caring so much about a stupid cat. Izro was busy helping with the cleaning and her mother never wanted the cat in the first place. There was nothing that could be done, so Lila tried not to think about it.

Lila had never been on a train before. On quiet nights she could hear their whistles off in the distance, but she had never seen one up close. Her father purchased tickets from the man who ran the grain elevator and they sat on their trunks to wait, which were packed with everything they owned. The first train, which took them from Soldiers Grove to Prairie du Chien, had only one car for passengers. The rest of the train was for hauling freight. Aside from the conductor and the brakemen, the Slabacks were the only people riding the train that day. Lila's mother insisted that she sit next to her on the hard wooden bench. Earl was getting fussy, but he stopped as soon as the train started moving. Veda, who was two years older than Lila, sat next to her. She was smiling, but Lila noticed that she was gripping the bench like it was the only thing saving her from certain death. It seemed like everyone was holding their breath as their seats rumbled and the train picked up speed, taking them away from Crawford County.

Hazel and John had both grown up in Crawford County. John had inherited the family farm from his parents, Levi and Amy Slaback. Although he was the youngest of nine children (since his younger brother, Warren, had been killed as a young child when he was kicked in the head by a cow), most of them were girls who had gone to live with their husbands as soon as they got married. Elmer, John's older brother, was good at math in school and decided that he didn't want to be a farmer. He had started his own business as a builder and was living with his wife and five children in a different town. Frank, his much older brother, had waited so long to get married that everyone thought he would be a bachelor forever. His wife, Hattie, was a widow with two children when they met. They had moved to the big city of La Crosse, where Frank found a good job as a cutter at the rubber mill. Lila didn't know it at the time, but Hattie was also working outside of the home at a restaurant for tourists known as The Pearl.

Lila wished that she had been allowed to sit by the window, but at least she could see the tops of the trees as they flew past. It took less than an hour to reach Prairie du Chien, which had a special building just for train passengers. While her father went over to a man standing behind a window to purchase more tickets, the rest of the family sat down by the big clock in the middle of the room and started eating their lunch, which they had carried with them in a basket. Soon it was time to get on the train again. This one was just for passengers. The cars were shiny, and the benches had cushions with soft fabric. It was so comfortable and very fast---much faster than the first train. Lila's mother relaxed a bit and allowed her to stand by the window so Lila could see what was happening. Not long after they left the station the trees cleared, and she could see an enormous stretch of water. It was dark blue and there was a long, flat boat being pulled by a smaller boat. Her brother, Theron, told her it was the Mississippi River. Lila didn’t know there was that much water in the world. Already, the landscape was very different from the farm.

Although she didn't mean to, Lila fell asleep on the train. One minute she was watching the river and the next minute Izro was telling her, "Wake up, Lila. We need to get off the train and you’re too big to carry." They had arrived at another train station, but this time they were not going inside. Uncle Frank was waiting for them with a truck. "Welcome to La Crosse!" he said and gave Lila's mother and father a warm hug. When John was thinking about getting out of farming, he and Theron traveled to La Crosse and stayed with Frank and Hattie for a few days. During the last long winter on the farm, they had shared their stories about the city so many times---about the tall buildings, the cars, the places to shop, and the crowds of people dressed in fancy clothes---that to Lila, the city already seemed like a familiar friend.

As they stood in the train station, Lila counted her brothers and sisters and parents and Uncle Frank. Ten people. She wasn't in school yet, but she was proud that she could count. Izro had taught her how. Her father left to find the trunks and her uncle said, "Who wants to go first?" Her mother decided that she would go, taking Izro and the younger children. Their new house was on the northern edge of the city. John had built it with help from Elmer, who knew the best places to buy lumber and fixtures. Hazel wanted to open the windows and let in some fresh air before they moved everything inside.

There was just enough room in the front of the truck for Uncle Frank, Hazel, Izro, Veda, Lila, and Earl. Lila sat in Izro's lap again and for once she was glad. A truck was much faster than a wagon. What if they crashed? What if Uncle Frank drove into the river? They closed the doors and started driving down the street. Lila was relieved that he wasn't driving too fast. By the time they reached their new house, she thought maybe driving wasn't so bad. 

## Notes

This chapter establishes some important facts about the Slaback family. John and Hazel grew up in Crawford County, Wisconsin on farms that were less than one mile apart. When they were first married, they moved to La Farge, Wisconsin (near John's brother, Elmer), but they moved back to Crawford County in the early 1920s to take over the farm owned by John's parents, Levi and Amy Slaback. John was the only living son who attempted to make a living as a farmer.

There had been a rapid expansion of the railroad system in rural Wisconsin, which led farmers to make a choice: buy a tractor, acquire more land, and start farming cash crops (a choice made by my paternal grandfather's parents), or sell the land and move to the city. John and Hazel Slaback made the latter choice. When they left the farm, they already had seven children. John's oldest brother, Frank, was the first member of the Slaback family to move to the big city of La Crosse. At the time, it was one of the largest cities in Wisconsin outside of the Milwaukee area.

Many farms in Wisconsin have "barn cats" that are largely feral and help to catch mice. I have no idea if Lila really owned a cat, but this chapter establishes Lila's caring nature and how barn cats are typically treated (tolerated, but not loved). It would have been heartbreaking to leave a cherished pet behind, especially knowing that nobody else cared. 

I have no idea how John's brother Warren died, but he was young. Getting kicked in the head by a cow is a very Wisconsin way to die. Cows are usually gentle, but they're also very strong and can be deadly when provoked. 

The train was a plausible way for a large family to travel from Crawford County to La Crosse. It is highly unlikely that John and Hazel Slaback would have owned a truck before moving to the city. In the 1920s, farmers commonly used horse-drawn wagons for transportation. 

For more information, see @wisc1952a, @current1977a, @sanders1999a, and @white2000a.
