# Prologue

I never met Lila, but her life cast a long shadow on mine.  

Both of my parents came from large families. My father's parents were Catholic and had eight children. My grandfather graduated from high school when he was fifteen and wanted to be a lawyer, but his mother needed him on the farm. He farmed until he developed a severe allergy to the mold in hay. When my father was a small child, they moved into town and my grandfather started a business with two of his brothers, selling farm equipment and building pole barns. My grandparents expected their children to be well-educated; some of them grew up to be teachers. Holidays at their house in Bloomer, Wisconsin (population: 3,000) were filled with good food, debates about politics, "catching up," and turkey-induced naps on the living room floor. In the summer, my grandparents had a big garden that filled their backyard. Most of their grandchildren (including me) also grew up in Wisconsin. There were tragedies from time to time, like my aunt Phyllis dying from breast cancer when she was only 28, but for the most part, it was a loving and stable group of people. When I became the first person in my extended family to earn a PhD, I dedicated my dissertation to my paternal grandparents. They would have been proud.  

My mother's family was also large, but very different. Since her parents had both passed away, family visits involved different stops. Aunt Bonnie lived in Sparta with her husband and children. Uncle Larry had been adopted by a family near Holmen. His adoptive father, Grandpa Peterson, let us feed carrots to his Shetland ponies. Grandma Peterson made the most delicious *sandbakkels* (Norwegian sugar cookies) and always gave us a paper plate full of treats for the drive home. I loved visiting them. Aunt June lived in Indiana, so we didn't see her very often. Uncle Randy had been adopted by Grandma and Grandpa Schneider (Myrtle and Carl), who lived on the edge of West Salem. They had a big family, which made the holidays crowded. I didn't realize until I was a teenager that Randy was my mother's half-brother. My aunts, Laurie, Pam, Charlou, and Uncle Steve were actually my cousins. John Schneider was Myrtle's second husband---not Randy's adoptive father---but he was also my great-uncle. We were all related in multiple and confusing ways.  

Aunt Myrt (Myrtle Joyce) lived in La Crosse. By the time I was born, she was a single mother with four children, living in public housing. Although I didn't know it at the time, her life was the most similar to Lila's. Compared to my father's family, her house was chaos. There were lots of strangers and drinking and nobody ever talked about politics. One of my early memories is sitting around with some adults watching *Halloween*, which is about a costume-wearing serial killer who stabs children. It must have been my first R-rated film. We had cable at home, but my parents never watched adult movies; even MTV was forbidden. I wasn't sure what my aunt (or really most of my mother's family) did for a living. When Myrt's son started going to prison, my parents warned me to stay away from him.  

Some of my mother's family members showed up for my high school graduation party, but we didn't have much to talk about. I was leaving for college in the fall. None of them had been to college; some had not even graduated from high school. The most highly educated one in the family was my mother's younger sister, Bonnie, who worked as a nurse. When I got married just before my twenty-first birthday, there was a noticeable sense of happiness and relief in my mother's family. I had done something they could relate to! Now my parents would be able to have grandchildren! I imagine they were somewhat disappointed when I stayed in college and continued into a graduate program instead of having babies right away. My first child was born when I was 29. My choices made us mutual strangers.  

From time to time while I was growing up, I asked questions about my mother's parents. Where did they live? What were they like? How did they die? My father had an opportunity to meet my grandfather, Herman Schneider, who died from a heart attack a few months after my parents' wedding. I met his second wife, Emma, who lived in a tiny house on French Island and was a very sweet and quirky woman. She only had one tooth and refused to wear dentures. One winter she grew a beard! (She said it was cold and she didn't feel like shaving.) My grandfather was a farmer, but I eventually learned that he never had his own farm. He dropped out of school after fourth grade and worked for other farmers in La Crosse County for the rest of his life.  

My grandmother, Lila, remained a mystery. My mother, Alice, was only eleven years old when she died. In many ways, Lila was a big question mark to both of us. In my late twenties, I was diagnosed with an autoimmune thyroid disorder. Realizing that it was a genetic condition, I told my parents they should get tested. My mother said, "Oh, your grandmother had a goiter." That was the kind of information I always got about Lila---random facts. Never enough to get a real sense of what she was like. I knew some (not all) of her siblings' names. I knew she was in her thirties when she died. I knew she had given birth to at least seven children, but most of them were not my mother's full siblings. My grandfather was not the only father. How many others were there? I had many questions, but the answers I received were always brief and confusing. The subject made my mother uncomfortable. At family gatherings there were whispers. Once I heard my mother describe my grandmother as a "hussy."  

I went to graduate school to study textiles and clothing. I wasn't all that interested in American history; I spent a semester in Africa when I was in college, and I wanted to go back. Instead, I ended up studying the history and politics of dress among Somali refugees. When I moved to Indiana in 2004 to work as a professor at Indiana University, my research shifted to contemporary Islamic fashion.  

Along the way, I started having children of my own. My son was born when my daughter was two years old, and I was overwhelmed. I thought of both my grandmothers; one had seven children and the other had eight. How did they cope? I couldn't imagine having even a third child. As my children grew self-sufficient enough that I could do things at home besides making meals, changing diapers, and giving baths, I started working on my genealogy. It was amazing what resources had become available. I discovered that only half of my mother's family (her father's family) was German, not 100% as she had always told me. Lila's ancestors had come to North America from various parts of northwest Europe, including the British Isles, France, and the Netherlands. Two of them were on the Mayflower. One was an accuser at the Salem Witch Trials. Most were farmers, but not the prosperous kind.  

During the process of getting divorced, I started thinking about my family history again. Being a single mother was better than being married, but it was never something I had planned for. Why did I assume that the only way to have children was to get married? I wasn't ashamed to be a single mother. I had a good job. I could take care of myself. Unfortunately, I realized that I was also vulnerable. I thought the children were getting old enough to stay at home while I ran errands, but what if something happened while I was gone? What if they turned on the stove and started a fire? What if a maintenance person showed up at the apartment and thought that I had "abandoned" my children? Is that how my mother and her siblings ended up in foster care? I wondered how Lila had coped with being a single mother. Was there anyone who supported her? My mother (Lila's daughter) had stopped working when I was born; my parents always claimed that it was a choice they made together, but it severely limited my mother's independence. For better or worse, Lila had forged a very different path. I started to feel like maybe Lila had been judged unfairly by her family and by society at large.  

In 2017, I became director of the Elizabeth Sage Historic Costume Collection at Indiana University, a position I held for four years until the staff was restructured. This led me to new interests in American history, especially working-class men and women and minorities (groups that are not very well represented in "fashion" collections). In the summer of 2019, I decided to write a novel about Lila. If I couldn't get answers to my questions, I would take my best guess by writing historical fiction. I wanted to explore generational trauma, how women make choices about their lives, and of course---given my background as a historian of fashion, dress, and the body---the landscape of dress and what it was like to be a working-class woman in Wisconsin in the first half of the twentieth century.  

---

Through a combination of intelligence, white privilege, financial aid, and determination to be independent (and avoid turning into my mother), I slowly made my way into a middle-class lifestyle as a professor. My story could have turned out very differently. My father worked in a factory for most of my childhood. While my classmates were out drinking and having sex and starting to have babies, I taught myself how to get into an elite, private college by reading books from the public library. I was in love with learning. It was my ticket out. In ten years, I earned a bachelor's degree, a master's degree, and a PhD. I knew I wanted to have children someday, but birth control gave me choices that Lila did not have.  

Lila had a very different sort of life. In a little over ten years (1944--1955), she had seven children. It was a particularly bad time to be a single mother. Between the end of World War II and the Roe v. Wade decision that legalized abortion, hundreds of thousands of pregnant teens and young adults were sent away and forced to give their babies up for adoption.[@fessler2006a] There was enormous pressure from parents, the communities they lived in, the government, and a rapidly growing "adoption industry" to hide those pregnancies and to stigmatize mothers who thought they could raise a child without a husband. As far as I know, Lila was twenty-two years old the first time she gave birth. She managed to keep that child and got married before having two more, but she had little support to manage her growing family. She died in 1958 when she was only thirty-six years old. The official cause of death was malignant hypertension, but the truth was more complicated. Unrelenting work and stress, repeated pregnancies, and abuse of amphetamines had destroyed her mental and physical health.  

The Slaback family was not proud of Lila, the afterthought who could never just accept her place in life. Absorbed in their own problems, they expected her to be self-sufficient, but when that turned into real, adult independence they punished her for it. Lila wanted more. Her choices were not always good ones, but I admire her strength and her desire to have more---to love and laugh freely and to be her own person. It was not the kind of life a good woman in the early twentieth century was supposed to want.  

## Notes

I have done extensive historical research to recover this story, but I have compressed some events and guessed at many details. Any errors are my fault alone.