# Chapter Seven

While the adults in Lila's neighborhood were going to work and entertaining themselves with picnics and card games, the children occupied themselves with school, climbing trees, ice skating, and endless games of tag, duck-duck-goose, and kick-the-can. Birthday parties were a special treat, with cake and ice cream, games that were only played at parties, and small presents for the birthday boy or girl. Lila's classmates often anticipated their birthday parties for months, especially who would be invited to attend. Telling a friend, "You're not invited to my party!" was an insult. Although a few mothers invited the whole class, most could not afford to have so many guests, which made invitations a kind of currency; giving and withholding invitations was important for establishing one's social status. Having parents who could afford a big party was an easy way to become popular.

Lila was not one of the popular girls, but she was invited to parties from time to time. At the start of second grade, Viola Johnson invited Lila to attend her party. She was the oldest child in her family; her sister Myrtle had just started first grade. They lived in the same neighborhood as Lila, but on the opposite side of the school---close to the church where Theron and Izro were married. Their father spoke English with a thick Norwegian accent. To decorate the house for the party, the girls had made strings of paper flowers and their mother had baked a fancy cake with white and pink frosting. They had also made a large drawing that they would use to play "pin the tail on the donkey." Lila had only played once before, but she thought it was fun. Starting with the birthday girl, each child would be handed a "tail" (a strip of paper with a pin in the end), blindfolded, spun around, and then released in the direction of the donkey. The winner would be the person who came closest to putting the tail in the right place. Some people would miss the drawing entirely or pin the tail in a funny place like the donkey's ear. There was no way to tell what you were doing with the blindfold on.

To Lila's surprise and delight, they also played "musical chairs." There were eleven children at the party (including Viola and Myrtle) so they set ten chairs in a circle in the middle of the sitting room. Viola explained the rules: her father was going to play music on his fiddle as everyone walked around the circle. As soon as he stopped, everyone should sit down as quickly as possible. The last person (who would not have a place to sit) would be declared "out" for the rest of the game. They would then remove a chair and do the same thing again until there was only one chair left. The last person with a place to sit would be the winner. Lila recognized the song that Viola's father played: Pop Goes the Weasel. She was the third person to go "out," but she didn't mind---it was just as fun watching everyone. Viola and her sister lasted longer; when Myrtle went out, she burst into tears. An older boy named Peter was the winner. 

All of the children ate cake and watched as Viola opened her presents. Lila's mother had given her a present to take to the party; it turned out to be a little sack filled with candies. Viola said, "Oh thank you, Lila!" But as she unwrapped the other presents, Lila felt a bit embarrassed. It seemed like the rest of the presents were much nicer---a teddy bear, some clothes for her doll, a jump rope, and even a yo-yo (a new toy that was becoming popular at school). Viola thanked every person. As they were leaving, Mrs. Johnson thanked all of the children for coming. Lila said politely, "Thank you for inviting me." She was used to roaming around the neighborhood with Veda and increasingly with Earl, but her brother Cecil was waiting at the door to walk Lila home. That was a nice surprise. She had expected to walk home alone.

As soon as they could no longer see Viola's house, Cecil ran off. He was laughing and said, "Catch you later!" Lila sighed. He was probably heading to the playground for a game of baseball. It was a popular thing for boys to do when they were not in school. Cecil even had a small collection of baseball cards, which came in packs of cigarettes purchased by their father and brothers (who would have thrown the cards away if they were not so fun for the children to collect and trade with their friends). Cecil's prize possession was a card for Pat Malone, the star pitcher for the Chicago Cubs. He liked to pretend that he was Pat Malone, staring down famous batters like Babe Ruth and Mel Ott (who were played by his friends, James and Frank). All of them pored over the newspapers for the latest stats, arguing about which team was the best and who would make it to the World Series that year. As Lila walked by the playground, she saw them already absorbed in a game. The boys didn't notice her.

When she got home, her mother was outside in the garden. "You're just in time. Go change your dress and help me pick these vegetables. I want to sell some of them tomorrow." Now that Izro was married and Veda and Lila were growing up, her mother was demanding more and more that they help with the chores---weeding and watering the garden, washing the dishes and putting them away, making the beds, sweeping the floors, and peeling the fruits and vegetables as she prepared the rest of the dinner. Veda was nine years old and able to do almost all of the chores. Lila was seven and still learning, but she preferred taking care of the younger boys instead of cleaning. It was more fun to make up games and take them for walks around the neighborhood than to be stuck in the house or the yard doing chores. 

The worst chore of all was the laundry. In the summer, it could be done outside. After they filled the wash tub with dirty clothes, pails of boiling water and a bit of soap, it was Lila's job to stir the clothes for a while with a wooden paddle---like making soup, except there was nothing delicious at the end of the process. Then the clothes would have to be scrubbed on the washboard, rinsed in a tub of clean water, put through the wringer, and hung on the line to dry. It was hot, exhausting work. Although nobody in the house had much clothing, every week the family had at least two tubs of dirty clothing plus two tubs of sheets and towels. The diapers had to be washed even more frequently (but thankfully, not ironed). In the winter they did laundry in the basement, which was cold and dark. One side of the basement was filled with ropes to hang wet clothing, which turned the dirt floor into mud. In the summer, the dried clothes smelled like sunshine and flowers; in the winter, they smelled like a graveyard.

Lila's mother was always in a hurry. It was not enough just to do the chores; she expected them to be done efficiently and well. Nothing Lila did was ever quite good enough for her. There was always a better and faster way. Lila didn't understand why it was fine for the older boys to play endless games of baseball while she and Veda were stuck doing chores. Shouldn't the boys help with the cooking and cleaning? Wouldn't it be reasonable for them to help take care of Earl and Looy? For a while, Lila said these things out loud, but her mother's response was always so angry that she stopped saying anything. It didn't take long to realize that it was easier just to do what she was told and keep her head down. When the family ate dinner that night---two whole chickens plus a big tray of roasted squash, dripping with butter and brown sugar (one of Lila's favorites)---there was no discussion about the work it took to get the meal on the table. Chores would be one of her lifelong frustrations. 

## Notes 

My description of Viola's birthday party is based on parties I attended as a small child, just with live music played by a parent instead of a record player. (I found evidence on [Ancestry.com](https://www.ancestry.com/) that Viola's father played the violin.) "Musical chairs" is an ancient game from Europe. "Pin the tail on the donkey" was invented in Wisconsin in the late 1800s, but it was still popular at children's birthday parties in the 1980s.

This chapter is the first time the reader meets Viola and Myrtle. I grew up knowing Myrtle as "Grandma Schneider." Until I worked on this project, I had no idea that Myrtle and Lila were classmates at Logan High School in the 1930s. Since their class had fewer than 100 students, I'm certain they knew one another as children.

This chapter reinforces how household activities were gendered in the United States in the early 1900s (and are still largely gendered today). Gas- and electric-powered washing machines did not become widespread until the 1940s, so doing the laundry was a particularly labor-intensive chore. I have a heavily used washboard that belonged to my father's mother. The basement of my father's childhood home had a dirt floor; I can only imagine how awful it was doing laundry in the basement during the winter. I started doing cleaning chores at a very early age (washing and drying the dishes, folding laundry, vacuuming, etc.). I always felt intense pressure from my mother to do the chores well and efficiently. Roasted squash with butter and brown sugar was one of my mother's favorite dishes in the fall. I learned to enjoy it as an adult.

For more information, see @bowen2014a, @wilker2010a, and @woersdorfer2017a.