# Chapter Six

That night, Lila slept upstairs in the attic for the first time. There was plenty of space, but she didn't understand why it was necessary for Izro and Myron to have the room downstairs to themselves. Myron's parents (who were old, even older than her own parents) were sleeping there too, "Just for the night." It took her a little while to fall asleep in the unfamiliar space, which is how she noticed that Myron's father was snoring. Lila giggled. It was a deep rattle like the sound of a bullfrog, but there were no frogs in the winter. Although it was cold in the attic, she was warm enough sharing a bed with Veda. They had the quilt that they usually shared with Izro. She hoped that Izro was warm enough downstairs without it. 

The next morning, everyone ate breakfast together. There wasn't quite enough room at the table for everyone to sit at the same time, but the older boys said they could wait. Izro and her mother cooked an endless number of pancakes, which they ate slathered with butter, maple syrup, and raspberry jam. When they were finished, Myron's father said, "I guess it's time that we should leave." Izro, Myron, and his parents put on their coats, and everyone started hugging. What was happening? Where was Izro going? When she gave Lila a hug, Lila started crying. She knew she was being a baby, but she couldn't help it. Izro told her, "Don't cry&hellip;I'll start crying too." Lila did her best to dry her tears. She didn't want to cause Izro any trouble. Lila wanted to go outside and watch them leave, but her mother told her to watch from the window. That night she and Veda went back to their old bedroom, but it was lonely without Izro. Who would give her a kiss goodnight and comb her hair in the morning? Her mother was busy with Earl and Looy. Lila, Veda, and her mother were the only girls left in the house. Lila was grateful that she was sharing a room with Veda.

A few days later was the start of the new term at school. Everyone was excited, talking about the fun things they had done over the break and showing off their presents. The principal came into the classroom and said that they would have a new teacher starting tomorrow. Miss Miller (who was now Mrs. Johnson) had left her position to get married. One of the boys asked why and the principal explained: married women could not be teachers because they would be too busy having babies and taking care of their houses. Lila had not been very attached to Miss Miller but losing her compounded her sense of loss from Izro moving out. 

During lunch, she told her friend, Kathleen (the girl with the red hair and freckles who occupied the desk next to hers) about the wedding. "How lovely! I can't wait until I get married. I want to have a big white dress&hellip;even fancier than the dress I'm wearing for First Communion next year&hellip;and my whole family will be there, and it will be so happy and beautiful. I wonder what my new last name will be? I wonder how many children I'll have? Tell me about your sister's dress!" Lila wished that she could be so excited. The church and the wedding dresses were beautiful, but she had mixed feelings about what happened after the wedding. It might be exciting to live in a new place, but would you miss your family? Would they miss you? Izro was living in Onalaska now and Lila had no idea when she would see her again. 

For a few weeks, their mother braided Veda's hair in the morning. She was not very gentle or patient. Lila thought it must hurt when she combed out the snarls in Veda's hair, but Veda never complained. Then Veda would attempt to braid Lila's hair. She was also not very good at it---not like Izro. By lunchtime her braids would be loose; by the time the girls walked home from school, at least one braid (sometimes both) would be completely undone. One of her ribbons got lost and her mother scolded her for being careless. By spring, their hair was starting to get a bit wild. One day, her mother announced that she was tired of dealing with it---she was giving Lila and Veda a haircut. Veda's eyes opened wide, and she looked like she was going to cry, but they both knew that it was no use complaining. Lila's first haircut was so short that she looked like her brothers. When they visited Aunt Hattie that weekend, she said, "Your hair is so stylish now, Lila! You look like a flapper." Lila thought it was just plain ugly. She didn't know what a "flapper" was or why any girl would want to look like a boy.  

## Notes

The opening scene in this chapter---where Lila is listening to Izro's new father-in-law snore and compares it to a bullfrog---gives us more insight into her personality. I never met Lila, so I don't know what she was like in real life. Her children only knew her as someone who was struggling, but what was she like as a child? What were my parents like as children? I thought some humor was necessary to remind the reader that she was a whole and complex person.

In the early 1900s, it was very common for teachers (mostly women) to be forced to resign if they married or became pregnant. This was framed as being "best for the children," but it was also a political (and patriarchal) move to prevent women from working outside of the home, especially in the more prestigious, middle-class jobs in schools, hospitals, and courtrooms. The message to girls was clear: plan to have a husband and babies, don't plan for a career.

I was that "wild child" who could never keep my braids looking nice, no matter how tightly my mother braided them. I had my first haircut when I was around seven years old; my hair was so long that it went past my hips. My mother decided it was necessary because there had been a lot of chlorine in the pool where I took swimming lessons; it wasn't really a choice for me. Flappers in the 1920s "bobbed" their hair, a masculine, hyper-modern look. While it was popular among fashionable young women, the style was not well-received among older and more conservative segments of US society. I hated having my hair washed, combed, and braided, but I would have been horrified to "look like a boy."

For more information, see @apple1986a, @simon2000a, and @fitzgerald1920a.
