# Chapter Ten

In 1931, Cecil was in eighth grade, Veda was in fifth grade, and Lila was in third grade at Roosevelt Elementary (named after Teddy Roosevelt, not that communist). The Depression was taking a real toll on their classmates. Some of the older students were dropping out of school to work. Some had to leave La Crosse because their fathers were looking for jobs in other cities. Veda's best friend, Minnie, was sent away to live with her relatives, who still owned a farm in Vernon County. Although Lila's parents did not seem too concerned about the whole situation, worry began to follow her around like a hungry wolf. Lila was not the worst student in her class, but she was also not one of the best. The worry made it difficult to concentrate.

Aunt Hattie had stopped working as a waitress. She was in her fifties and said that it was important for older people to let young people have the jobs, but in truth it also gave her time to do charity work, throw parties, and work on improving her reputation (which had been damaged by the repeated stories in the newspaper about Lloyd). Theron's wife, Borgny, was content to be a housewife and volunteered with the "Bethel Busy Bees," which made quilts, visited sick people in the hospital, and organized fundraisers. Like Borgny, everyone in the group was a member of Bethel Lutheran, the neighborhood church where she and Theron had been married. Aunt Hattie was not a regular member of any church, but she made that work to her advantage; it allowed her to host events in her house for a variety of groups---one week it might be the LDS Ladies Relief Society, the next week it could be Saint Wenceslaus or the American Legion Auxiliary. She had a beautiful silver tea service and a large set of matching china; as a hostess, she was always very gracious and elegant. The constant rotation of groups kept "Hattie Slaback" on everyone's mind as a model of generosity, but it also kept them from getting too close and asking questions. 

The house on Kane Street was full for Easter. Izro and Myron were visiting for a few days so everyone could meet their son, LeRoy. Theron and Borgny's daughter, Hilda Hazel, had the honor of being the very first grandchild (and being named after her grandmother), but LeRoy had been born during the same month. With blonde hair and blue eyes, the two of them looked practically like twins. Lila was dismayed to realize that she was no longer one of the "children." She was allowed to do the children's egg hunt in the park, but otherwise, it was like every other day: beds to make, food to prepare, dishes to wash, and younger brothers to keep out of trouble. Izro was a guest now and could not be expected to help with the chores. Lila burst into silent tears when her mother told her to sweep the floors. Hazel's patience had been wearing down all day and Lila's tears were the last straw. "You need to grow up, Lila&hellip;if you can't stop crying, you should go join the babies in the other room." Izro found Lila in the kitchen washing dishes (still crying) and hugged her. Lila had missed her so much. 

Some people forget to eat when they're having a difficult time. Lila was the opposite; the worry and sadness made her eat more. Being in the kitchen all the time, it was easy to get extra food: a taste of the soup to make sure it was done, a dinner roll that accidentally dropped on the floor (hide the evidence!), or a few bites of dessert that one of the younger children had failed to finish. It would have been a shame to waste anything when so many people were going without. Like her teacher said, it was her civic responsibility to do what she could. As a result, Lila was getting a bit "stout." When she looked in the mirror in the bathroom, the only thing she admired was her eyes. They were like the color of a quiet lake---dark green, with a hint of blue from the sky's reflection. Her hair was light brown (so boring), her nose was a little big, and her cheeks were way too big. Nobody else in her family had a head shaped like a pumpkin. 

## Notes

My oldest child is dyslexic, a learning disability that clusters in families. I have no idea if Lila was dyslexic, but she could have been. Although she went to high school, she had fallen behind her peers that were the same age. It appears that she did not graduate. 

Hattie Slaback and Borgny Slaback were mentioned often in the *La Crosse Tribune*. Borgny was involved in the Bethel Busy Bees (associated with Bethel Lutheran Church), but Hattie's pattern of involvement in church and philanthropic groups was more scattered. She may have had a difficult personality; she may have found it hard to explain her independence or her son's prison record. I can only speculate.

This chapter reminds us of how much the Slaback family has changed. Lila is no longer a little girl; she and her sister Veda are the only girls in a house full of boys. The oldest grandchildren are close in age to Lila's youngest brother. As an older mother who had raised many children, I imagine that Lila's mother, Hazel, was quite exhausted. Family stories have indicated to me that she did not have much patience and was not a pleasant person to be around. As a child growing up in the Great Depression, I imagine that Lila was dealing with a lot of fear and grief without much support. Eating is one way to stuff emotions instead of feeling them. Photographs show that Lila was overweight as a child, but the rest of her family members were not.

For more information, see @brumberg2010a, @elliott2014a, and @mcgarvie2003a.  
