# Chapter Thirty-Eight

When the baby was born, Lila decided to name him after both of his grandfathers---John Edward Schneider. Herman was so proud when he held his son for the first time. He embraced Lila and told her that he couldn't wait to have everyone back home. After a week in the hospital, Carl and Myrtle drove her back to the farm.  

John was such an easy and sweet baby. Edward and Alice were overjoyed about their oldest son's growing family. Herman and Lila began spending almost every Sunday in West Salem. Gladys said it was too bad they didn't live a bit closer. Although Herman had to get back to the farm to help with milking, Lila often stayed behind for the rest of the day. Alice enjoyed spending time with her grandchildren, and Lila enjoyed spending time with Gladys. She was going to parties at Camp McCoy and dating a veteran named Carl Schliebe. He had been married before the war but returned to find that his wife had run off to Minnesota with another man. Lila and Gladys laughed and talked like they had been close friends for their entire lives.  

One weekend that summer, Gladys said that they should plan a trip to La Crosse. Lila almost objected that she had nothing to wear, but then she thought about the red uniform at the bottom of her dresser. When she tried on the dress the next day, she could hardly believe that it fit. John was in the crib and Myrtle Joyce was standing on the bed. Lila twirled around and said (not expecting an answer), "What do you think?" Myrtle Joyce clapped, and Lila laughed. Two weeks later she was with Gladys driving to La Crosse in the green truck. "This is so exciting!" said Gladys. Lila was excited too. The children were spending the night with Aunt Nora.  

Gladys and Lila had decided to go dancing at the Trocadero, one of the new nightclubs downtown. It was thirty-five cents to hear the band and dance from eight p.m. to midnight. The dance floor was already packed by the time they arrived. It was an ocean of khaki, button-down shirts, and swirling dresses. As they paid for admission, the band started playing a new song and the crowd formed a circle to watch two dancers in the middle. Shockingly, the male dancer was black. His movements were so fluid and powerful&hellip;it was like nothing Lila had ever seen before. He lifted and spun his partner around like she was weightless. "Wow, they can really dance!" said Gladys. Lila had forgotten where she was for a second; she was so captivated by the dancers. A young man asked Gladys to join him and pulled her into the crowd.  

Lila was just starting to think about getting a drink when a man came up behind her and said, "Lila Slaback." She turned, and it was Lloyd. A shock ran through her body---joy, horror, longing, excitement---she had never expected to see him again. He obviously didn't know that she was married now. "Dance with me, beautiful." He held out his right hand, and Lila took it. Without another word they started dancing. To Lila, it felt like time had stopped and she was eighteen again---no husband, no children---just her and Lloyd. His collar was unbuttoned, and he smelled like cigarettes. His hair was turning gray. His left hand was on her hip, and Lila wanted him to pull her closer. They danced for two songs and Lloyd whispered in her ear, "I've missed you so much." Then he smiled and melted into the crowd, like he had been a mirage. She didn't see him again for the rest of the night.  

Two days later, while Herman was working and the children were napping, Lila pulled out the letters from Lloyd that she had kept hidden for years. She should have destroyed them or thrown them away&hellip;why couldn't she just be happy with her life? It was embarrassing that she could not forget her first love and move on. She unfolded one of the last letters she had received from Lloyd before her engagement to Herman.

> February 5, 1944
>
> Dear Lila,
> The days have been so cold, but I keep myself warm by thinking about you. I want to share a bed with you. I want to tell you dirty jokes and watch your face blush. I want to lick your tits and feel the shiver of pleasure in your body.  
>
> Love, Lloyd

At the bottom of the letter was a picture of two snails. One was holding a gun and telling the other snail, "I'll give you just two days to say your prayers, buddy!" She didn't want to miss Lloyd, but she did. 

## Notes

This chapter represents the best time in Lila and Herman's marriage. Herman is thrilled to have a son, and an "easy baby" gives Lila some relief. (My children were not easy as babies, so I know how infancy can be physically and emotionally draining.) Things are going relatively well for the extended Schneider family.  

Dance halls and live bands were popular entertainments in La Crosse in the 1940s; it was easy for me to find examples and cover charges in the newspapers (which people living outside of the city would have used to find such opportunities). La Crosse was hostile to black residents and visitors; bars and dance halls were unusual spaces where whites (like Lila) could interact with blacks. They were also spaces where young people could explore their sexuality.  

Lloyd was out of prison in 1946. I have no idea if Lloyd and Lila reconnected in real life, but this scene gives us more insight into how Lila feels about the city and her life before marriage. She misses feeling carefree and sexually desirable.  

For more information, see @heap2009a, @mcbee2000a, and @simmons2009a.  