# Chapter Thirty-Two

Lila had not seen Viola since she dropped out of school to get married. Myrtle was in the car with them, holding the baby in the back seat. "Get in!" she said. "You can hold Joan." John was driving. He was tall with dark hair and a ruddy complexion. Lila wondered if he looked like his brother, Herman. She was feeling nervous about meeting him.  

Earlier that week, Lila had gone shopping downtown. Her clothes were getting so tight, but she had never been handy with a sewing machine. Viola had purchased a new one and said that Lila could use it, but when she sat in front of the machine her head was filled with echoes of her mother's voice: "You're going to break it! Don't do it that way. What did I tell you?! You couldn't sew a straight line if your life depended on it." She had the money from waitressing, so why not spend a little? After combing through the racks at Woolworths for a while---wondering what size dress she would need in her "state" and working up the courage to try some things on---she stumbled into a small section of maternity clothing. It didn't look that different from the rest of the clothing on the floor, but when she tried on a dress, she realized that it had extra buttons on the inside that would allow her to adjust the size as her belly grew. She bought four dresses in a flattering wrap style. The cotton fabric would be chilly for the rest of the winter, but her skin was too sensitive for wool.  

Her dress for the trip to West Salem was brown with tiny yellow and orange daisies. It wasn't glamorous, but it was presentable. Lila had giggled in the mirror that morning thinking about what a "knocked-up cocktail waitress in need of a husband" would look like, but this wasn't the day for truth-in-advertising. Her feet were starting to swell and felt pinched inside her shoes. She had purchased a pair of brown wool stockings---a concession to wholesomeness---and they were making her legs itch. The only thing she was happy about was her hair. She didn't love the color, but it was thick and shiny and beautifully curled. She had pinned it back on one side with an elegant gold-colored barrette. As Viola, Myrtle, and John chatted about the latest gossip from West Salem, the baby fell asleep in Lila's arms. Her eyelashes were so long and delicate, and she smelled heavenly. Her tiny fist was wrapped tightly around Lila's finger.  

The drive to West Salem did not take long. It was cold and sunny, and the trees glittered like diamonds. The Schneiders lived in a tiny house on the edge of town. The front stairs were crumbling, and the house was overshadowed by an enormous pine tree. Gladys, John's younger sister, was at the front door waiting to welcome them in. There was no turning back now. The house smelled like naphtha soap and roast beef. John's mother, Alice, gave Viola and Myrtle a hug, and then she turned and said, "Welcome; you must be Lila," with a slight German accent. She was wearing a long dress and a beautiful shawl that she had knitted herself using different shades of brown wool. She gave Lila a hug like they had known one another for years. It made Lila feel better about being there.  

A few minutes later John's older sister, Nora, walked through the door with a small boy. Her dress was shorter and more fashionable. She kissed her mother on the cheek and put on an apron to help with the cooking. Where was everyone else? Lila sat down at the table and looked around the main living area. There wasn't much to see. There were two doors leading to the bedrooms. A cast-iron stove provided heat and doubled as an extra place to cook. On the wall next to the table was a calendar from 1935 with a bouquet of flowers. It was the only colorful thing in the room. There was no radio and---Lila realized with horror---no indoor plumbing. She dreaded trudging through the snow and using the outhouse, which was sure to be unheated.  

As she listened to the family's chatter, she learned that John had another older sister, Helen, who lived in La Crosse. Her husband had died in a tragic hunting accident not long after their son was born. She was raising him alone and worked in the Trane factory on the south side of the city. (Lila had heard of it but was not familiar with any of the neighborhoods south of downtown.) Nora's son, David, was the third grandchild. Viola's children, Rose and Joan, were the second and fourth. Alice clearly loved visiting with all of her grandchildren. Rose and David took turns bouncing on her knees; they were gleeful as she performed little rhymes that Lila did not understand. Gladys and Nora were finishing up the meal. As they distributed the tin plates and well-used silverware, Herman, his father Edward, and the youngest brother, Bobby, arrived. They had been milking cows and smelled faintly like hay and manure.  

Herman washed his hands in a basin by the front door and sat across the table from Lila. He was very quiet. They didn't speak to one another during the meal. Lila wasn't sure that he even noticed her. He was very tall and slim and ate his boiled carrots, salted potatoes, and slice of roast beef in silence. His flannel shirt was heavily patched. He had dirt under his fingernails and sad-looking eyes. 

Nora asked Lila if she would like another cup of tea and said, "Tell us a little about your family, Lila. What are they like?" 

Everyone stopped talking and turned their heads. Lila blushed. "Well, I'm not sure what to tell you." In her mind, she was thinking of her life in the city---the streetcars, the bustle of people going about their business, the movie theater where Veda had met Red, working at Carroll's---it was different from West Salem, which was a much smaller town. She didn't want to offend them or reveal too much about her situation. After a few moments, she said, "My parents used to be farmers. We moved to La Crosse when I was five years old, so I don't really remember it, although we sometimes went out into the country to see relatives and pick apples. My parents recently left the city, so I'm living with my sister. I have two sisters and five brothers; well&hellip;four brothers, since one of them died in a car accident." 

Myrtle blurted out, "I didn't know that your parents were farmers." They had been friends for a while at that point, but Lila was not surprised. Myrtle was not a very good listener. For the benefit of everyone in the room, Myrtle cheerfully added, "Lila and I went to grade school and high school together." She beamed as Lila smiled awkwardly.  

After the meal, Nora suggested that they should go for a walk. Herman joined them, but as they approached the stockyard by the railroad tracks, he said, "See you later&hellip;I have some errands to run before I head back to the farm." It was the only thing Lila heard him say that afternoon. 

Once he was gone, Gladys leaned in and said, "Lila! You have to tell us what it's really like to be in the city. There must be so many handsome men there." 

For a second, Lila imagined what it would be like to have Gladys as a sister-in-law. It was an appealing thought. Gladys was not married, and they were close in age. "You should come visit," said Lila. "That would be so much fun!" 

Gladys replied, "I've known all the men in this town since they were little boys and I'm bored to death with them."  

The village of West Salem was only a few blocks wide and a few blocks long. As they walked, Gladys pointed out Christ Lutheran (which the family faithfully attended every Sunday morning), the creamery, the high school, and the photography studio where Nora worked. There was one block of shops along Leonard Avenue with a hardware store and a small movie theater. When they returned, the children were sleeping, and the house was very quiet. Viola said that she would stay there while John drove Myrtle and Lila back home. Nora and Gladys gave everyone a hug. As Lila was buttoning her coat, Alice said, "I hope we will see you again, dear." She put her hand on Lila's belly and smiled. Lila had said nothing about the pregnancy or her reasons for visiting, but it was clear that Alice understood.  

## Notes 

My mother was brilliant at sewing but very impatient and critical when teaching me. To this day, I prefer sewing by hand. I don't know if Lila's experience was similar, but I used this chapter to draw in a little research on the history of maternity clothing.  

Since my mother was named after her father's mother, I assume she played an important role in approving my grandparents' marriage. In this book, I imagine her as a creative, tolerant, and welcoming person---representing the best parts of the Schneider family. I know from census records and phone directories that Nora worked for years as a photographer's assistant. Helen---who was a single mother for a long time---lived on the south side of La Crosse and held an office job at the Trane factory (which is still in business and manufactures HVAC equipment).  

West Salem is only eleven miles away from northern La Crosse, but the cultural distance between them would have been much greater in the 1940s than it is today---before highways, television, and the Internet. I looked at historic maps to get a feel for the layout and density of West Salem in the early to mid-twentieth century. Having lived in both rural and urban areas, I know that access to technology (plumbing, electricity, cell service, etc.) is a massive privilege but also easy to take for granted when you have it.  

Although Hamlin Garland---West Salem's most famous resident---had died a few years before Lila went there to meet her future husband, his book, *A Son of the Middle Border*, offers insight into the history and culture of the region.  

This early description of my grandfather, Herman, is based on my experiences with my brother-in-law, Serge Akou---a very quiet, professional jazz musician who seems to save all of his self-expression for his musical performances. Through no fault of their own, some people are very difficult to know.  

For more information, see @garland1917a, @riney-kehrberg2016a, and @semler2024a.  