# Chapter Thirty-One

That afternoon when the house was quiet again, Veda told Lila that she would have to stop working. What if she fainted again? It wasn't safe for her or the baby. She said it with a gentleness that had been absent from the conversation with Aunt Hattie and their mother. Lila wanted to push back and tell her to mind her own business, but Veda had a point. She would have to take better care of herself if she was going to keep this baby. She had never thought much about becoming a mother, but she was beginning to feel a deep longing for the child growing inside of her. A child of her own: nobody was going to make her give it up.  

For the rest of the month, Lila mostly kept to herself. After a few awkward dinners, she decided to eat alone in her room; it was better than facing the look of rejection on Red's face. She missed going to work though. She missed earning money and flirting with men at the bar. She missed hearing their jokes and laughter. Most of all, she missed leaving the house. There was a cloud of shame hanging over all of them. Lila couldn't go to church in her "condition." Going outside for any reason was risky; the neighbors were sure to notice.  

One cloudy day in February, Lila decided that she needed some fresh air. She slipped out of the house while Veda was shopping for groceries. She didn't have any destination in mind. It was just good to be outside. After walking for a few blocks, she decided to head in the direction of Myrtle's house. When she rang the doorbell, Myrtle answered right away and invited her in for cookies and tea. It was such a relief to see a friendly face. Myrtle didn't know anything yet about the pregnancy. It was warm and cozy inside. Myrtle was barefoot and wearing a house dress and a white apron; she was in the middle of making a coffee cake for a luncheon at the church. "Take your coat off and stay a while," she said.   

When Myrtle turned her back to check on the cake, Lila took off her coat and hung it in the little closet by the front door. By the time Myrtle had turned back around, Lila was sitting at the table. "I haven't seen you in ages!" she said gleefully. "I have so much news to tell you." Her sister, Viola, had given birth to a baby girl in November, her parents' second grandchild. Myrtle had crocheted a blanket for the christening and was making her a layette. There was a tiny sweater lying on the sofa. As Myrtle rattled on about Viola's two precious little girls, Lila thought about her own impending "miracle." The hot tea was making her feel a bit dizzy.  

After an hour Lila said, "Thanks for the tea; I guess I should be going." 

Myrtle replied, "Why don't you stay for dinner? If you don't, I'll just end up eating cheese and crackers and reading a trashy romance until midnight. You have to save me." They both laughed. 

"I guess I could," said Lila. 

"Great! I'll get some sausages from downstairs, and you can peel the potatoes. They're in the cabinet near the door." 

Feeling relaxed, Lila got up to look for a paring knife. She could hear Myrtle coming back up the stairs. She flipped the switch at the top of the stairs and said, "These sausages are really good." 

Lila was standing at the sink washing the potatoes when Myrtle put her hand on her shoulder. With a tone of astonishment, she said, "Lila&hellip;are you&hellip;pregnant?" Lila didn't answer, so Myrtle continued. "Why didn't you say anything? Who is the father?" A tear rolled down Lila's cheek, and Myrtle gave her a hug. "I'm so sorry that I didn't notice before. Bring a chair from the table and I'll peel the potatoes."  

As they made dinner, Lila told her about Daniel. It felt good to talk. Being with Daniel that night had been a moment of beautiful pleasure, except---now here she was, pregnant and unmarried. Myrtle usually did most of the talking, but this time she was quiet. By the time Lila finished telling the story (including how her family had reacted), Myrtle was at the stove frying the sausages and hash browns. She said, "You're really in a pickle, Lila. What are you planning to do now?" It was a question and not a demand. 

"I told them I would get married and keep the baby, but I don't know how to pull it off. How can I find a man who will marry me like this?"  

As they ate dinner Myrtle said, "I have an idea. Carl has an older brother who never got married. His name is Herman, and he works as a hired man on a farm. He's shy, but he's nice." 

Lila said, "A farmer? No thanks." 

Myrtle swallowed her bite of sausage and said, "Beggars can't be choosers. You should at least give Herman a chance. I'm going out to West Salem next weekend for lunch with the Schneider family. Herman will be there, and you can go with me as my friend. Maybe it will turn out to be nothing, but it will get you out of the house. Viola and her husband John are picking me up. I'm sure they won't mind if we pick you up too." 

As they said their goodbyes with another hug, Lila promised that she would go with them.

## Notes

In this chapter, we learn more about the changing relationship between Lila and her older sister, Veda. Veda cares about Lila, but she fears rejection from her family, her church, and her own husband---her compassion can only extend so far. The acceptance Lila receives from Myrtle contrasts sharply with the behavior of the Slabacks.  

Until the "baby boom" started after World War II, pregnant women were generally expected to conceal their condition (e.g., with a maternity corset) or stay home. As an unmarried woman, the pressure on Lila would have been especially intense. Page Boy, the first ready-to-wear maternity clothing brand in the US, had only just begun selling their designs nationwide in 1939.  

"Take your coat off and stay a while" is a phrase I heard often growing up. It's friendly but also a bit sarcastic, as if the visitor doesn't have enough sense to shed their winter coat without being asked to do so. The phrase, "beggars can't be choosers," is also passive-aggressive.

For more information, see @goldman2013a and @regis2013a.  