# Chapter Thirteen

Outside of the house on Kane Street, life continued as normal. Lila heard later that Nora had her birthday party. Of course she did. Her little brother was still perfectly alive. Veda and Lila had already cleaned most of the house, so to pass the time they listened to the radio and played with Looy. Their mother disappeared into her bedroom on Friday evening and didn't reappear until Monday morning---not even for meals. Lila thought she must be starving but knew better than to comment. Even in good times, her questions were usually ignored or met with anger. Everyone was so quiet. Lyle and her father left for a while to do some work since they would not be able to work on Monday. Cecil stayed upstairs for most of the weekend.

On Monday morning, Lila woke up to find that several of the neighbors were getting the house ready for the funeral. They brought extra chairs and platters of food; Lila had never seen the table so loaded. She was combing her hair and putting on her clothes (regretfully, she noted that the yellow dress barely fit) when the undertaker arrived. He set up a small platform near the front door and then a few of the men helped carry in the coffin. Lila was relieved to see that her brother would have a proper burial, but she was also curious. What did he look like in there? Shortly before the service, the reverend arrived and opened the top half of the coffin. As soon as he left the room to speak with her parents, Lila went up to the coffin to take a peek. Earl was wearing the clothes he usually wore to school. She noticed that two of the buttons on his shirt were broken, but otherwise there was nothing out of the ordinary; Earl looked like he was sleeping. Veda was standing beside her, quietly crying, Lila was usually the more emotional one, but on this particular morning, she was surprised to feel nothing. She wasn't angry or frightened or even sad. Maybe, she thought, this is what it meant to be "in shock." Lila touched Earl's hand like she had done many times before, but it was so cold and stiff---so lifeless---that she quickly pulled her hand back. 

By ten o'clock the house was filled. Many people were standing. Some had to stand in the kitchen or outside; there wasn't enough room for everyone. Lila recognized many of Earl's classmates. Aunt Hattie and Uncle Frank were sitting in front with her parents. Theron and Izro were also in front. Lila had not noticed when Izro arrived. Since there would be another service before the burial in Crawford County, the reverend did not speak for long. When the line formed so everyone could see Earl and talk with her parents, Lila joined the line for food. The neighbors had put together an impressive spread. In addition to a huge plate of ham sandwiches, there were bowls of vegetables, bowls of pickles, trays of cookies, a basket of apples, and numerous pots of coffee and tea. When Lila bit into one of the sandwiches, she was surprised to find that it had a generous slab of butter; it was not what she had expected, but it was good. She went back for a second helping (and then a third helping) and nobody said a word.

By noon, most of the visitors were gone. The adults were standing near the front door, having a discussion. Aunt Hattie said, "Well it's settled then; Hazel and John will ride with us and Lyle will drive the children." It was time for the men to carry Earl to the truck. One of the neighbors, Mrs. Christiansen, was still standing over the coffin. Her husband and son had been killed in an automobile accident just a few weeks earlier. Lila was surprised that she was there. The reverend put his hand on her shoulder and said, "Mrs. Christiansen, can I walk you back to your house?" She nodded and started moving towards the front door. Theron softly closed the lid as the men lifted the coffin off the pedestal. They carried it to the truck and placed it in the middle of the flatbed. As Lila climbed in and sat down, she thought about their most recent trip to Crawford County. Just two weeks ago, the truck had been filled with bushels of apples from Aunt Stella's farm. Today, instead of weeding and picking vegetables, they were on their way to put Earl in the ground. It was so desperately strange and wrong. 

Earl was the first member of the family to die in La Crosse. To Lila's parents, it seemed natural that he should be buried with the rest of the family in Crawford County. To Lila, it was yet another insult. They were going to leave Earl out there, all alone, and go back to La Crosse like nothing ever happened. There had been frost on the ground that morning, but by the time they arrived at the church next to her grandparent's farm, it was becoming a beautiful day. The sun was warm, and the air was rich with the smell of fallen leaves. The snow could start falling any day now; every last bit of sunshine was a gift. Only five years had passed since the family moved to La Crosse, however, Lila barely remembered the church. The building was already packed when they arrived. As they filed into the first pew, Theron, Lyle, Cecil, and her father carried Earl's coffin to the front.

"Today, we are here to bid farewell to our beloved brother, son, nephew, and grandson, who was called to Heaven at such a tender age&hellip;." Lila barely heard the rest of the service. She could feel the weight of her body sitting on the bench, her lungs filling and releasing the air, her heart pounding in her chest, and her toes pressing into her shoes (which were far too small, but it would be months before her family could afford another pair). Physically, she was very much alive, but it seemed like her feelings had died the same day as her brother. Veda's handkerchief was already damp with her tears. Lila's handkerchief was sitting in her pocket, unused. All around the church, she could hear people sniffling and quietly crying---their grief was like a weight pressing on her shoulders and chest. She did not feel like she could join them; in her mind was a phrase that she had heard many times: "Big girls don't cry." Earl was her brother, but she felt like a stranger looking at the scene through a glass window.  

After the burial, there was another dinner. The food was delicious and there was so much of it: roasted chicken, smoked ham, baked potatoes with butter and sour cream, pumpkin pies, apple pies, bowls of pickles, and a giant block of cheddar cheese. For a little while she played with her younger cousins, but the pinched look of disapproval on Aunt Hattie's face ended the fun. She was supposed to be in mourning like a proper young lady. It felt like another injustice. She tried so hard to be good, but Aunt Hattie never seemed to notice her good behavior. By the time they drove home, it was already getting dark.  

## Notes 

I was younger than Lila the first time I went to a funeral, but I distinctly remember when my great-grandfather died. I was nine years old. During the viewing of his casket (where family and guests view the body one last time), one of my younger cousins asked if he could touch my great-grandfather's hand. I was surprised by that request but also curious, so when I thought nobody was looking, I touched my great-grandfather's hand. His skin was soft and very cold. Like Lila, I quickly pulled my hand back.

"Funeral sandwiches" are common in the United States. My experience, growing up in northern Wisconsin, is that they consist of white bread with ham and a lot of butter. In the South, funeral sandwiches are also known as "party sandwiches" and can be served for any occasion (happy or sad) where a large group of people is expected. For working-class families, the closer you go to the source of the food (i.e., the farm), the more plentiful it becomes.

What place did John and Hazel Slaback think of as home? Since they decided to bury their son in Crawford County (where they had both grown up), I suspect they were not feeling completely settled in La Crosse. I'm not sure they ever planned to move back or could have afforded to, but feeling like a place is "home" is more connected to the heart than reality. For Lila---who moved to La Crosse as a small child---I imagine the city always felt like home. This created a distance between her and her parents, but I'm not sure they would have recognized it. If they ever did, it was probably too late to benefit Lila. Despite being part of a large family, Lila was generally on her own to find her way as a city girl.

For more information, see @cann2018a, @doka2014a, and @sweeney2014a.  
