# Chapter Thirty-Seven

One day, Lila was outside drawing water to wash diapers when she noticed a green truck turning by the barn and heading in her direction. As it came closer, she could see Gladys waving to her. She hadn't realized how much she had been drowning in a sea of loneliness until she saw her face. Her heart leapt as she watched Gladys park the truck and step out. 

"I could hardly wait for the roads to dry up so I could come visit you!" 

Lila had already set down the bucket of water and walked over to the truck. She hugged Gladys and said, "I'm so relieved to see you!" 

Gladys laughed and said, "That's quite a hug! I guess you really did miss me."  

They were sitting at the kitchen table when Herman came home for lunch. He poured a cup of coffee and took one of the sandwiches. "Hi Gladys. When did you get here?" 

"A little while ago," she replied. "Lila and I are just catching up." 

When he finished chewing his first bite of the sandwich, he said, "You should give Lila a driving lesson. I told her that I would do it, but I've been busy with the calves."  

When Herman left and they had finished eating, Gladys said, "Well&hellip;are you ready for the lesson?" Lila could hardly believe it. It was such a treat just having Gladys for a visit; now she was teaching her to drive. Gladys picked up Myrtle Joyce, and Lila cautiously opened the driver's side door and stepped into the cab. She sat down and Gladys handed her the key. "Put this in the ignition right here and then press the button on the dash." Lila followed her directions and the truck roared to life. Speaking louder, Gladys pointed out the clutch, the brake, and the gas pedal. "We probably won't go far today&hellip;the first thing is to learn how to shift and use the clutch." The truck rolled forward a bit and then lurched to a stop. Lila was horrified, but Gladys was laughing. "Everyone does that the first few times. It takes a little practice to get it right." It wasn't long until they were out on the road. When they finished the lesson, Gladys opened the door of the glove box and pulled out an envelope. "This is for you," she said. "It's an application for a driver's license. You just have to fill it out and give them fifty cents." 

That Sunday, Herman said he wanted to go to West Salem for church. As they walked to the truck, he handed the key to Lila. "You can be the driver this time." Lila blushed as he took Myrtle Joyce and opened the passenger door. Herman gave her directions to Christ Lutheran; she was proud of herself for only stalling the truck once. Alice, Nora, and Gladys were happy to see her again. Since her wedding dress no longer fit, she had worn her favorite blue maternity dress. It was obvious that she was expecting again. During lunch she told Nora and Gladys that Herman was encouraging her to go to La Crosse for the birth. Nora said, "You could come here, but I'll ask Viola for ideas." A few weeks later, Nora said, "I have good news for you! Viola's parents offered to let you stay at their house&hellip;you can go to St. Ann's for the birth." St. Ann's was the maternity hospital for St. Francis, where Lila had learned of her first pregnancy.  

It was a hot day in August when Herman drove her to the Johnson house. It was strange (but also a relief) to be away from Myrtle Joyce. They had taken her to West Salem to stay with Alice until Lila was home with the baby. Since the day she was born, Lila and Myrtle Joyce had never been apart for more than a few hours; now they would be apart for a few weeks.  

When Herman and Lila arrived in La Crosse, Viola's mother, Bertha, was at home with her three youngest daughters. Evelyn and Rosemary were teenagers; Ruth was only four years old. Bertha showed Lila where she would sleep, then said she needed to go. She and her husband had opened a bar and she needed to help with the evening rush. Rosemary turned on the radio and suggested that they play a game of cards. "It takes four people for euchre, so let's play gin rummy." Evelyn agreed and pulled a deck of cards and a notepad from a drawer in the kitchen.  

The next day, Myrtle dropped by. Carl had been home for almost two months, and she was still giddy about it. They decided to take a streetcar downtown to see the new Abbott and Costello movie. On the way she talked non-stop; it made Lila giggle. She missed being close to Herman, but she had also missed La Crosse---hearing the traffic, smelling the river, feeling dwarfed by the tall buildings, and imagining the stories behind the snippets of conversation she overheard ("If you don't tell your mother, Margaret, I will.") Growing up she had taken the city for granted, but now it was calling to her like the sirens of Greek mythology. Her time with the Johnson family passed by too quickly.  

## Notes 

When I did some research for this chapter, I was surprised to learn that Wisconsin and Alaska were the last two US states to require examinations for new drivers (1956). In the 1940s when Lila was a young adult, drivers could get a license just by applying and paying a small fee. The scene where Gladys teaches Lila to drive is based on my own experiences learning to drive a car with manual transmission. Safety features like seatbelts and car seats for children were unheard of in the 1940s.  

In this chapter, Lila stays with the Johnson family (Myrtle and Viola's parents) before the birth of her second child. Being in La Crosse makes her nostalgic for city life. This is foreshadowing for upcoming chapters.  

For more information, see @fwha1997a, @kahane1986a, and @nader1965a.  