# Chapter Thirty-Three

It wasn't long after that when Veda announced that she was pregnant again. They were sitting at the dinner table, and Lila had been thinking about the trip to West Salem. She wondered whether Herman was interested in her. Red said, "That's so wonderful, Veda!" He leaned over, and they kissed. Lila felt invisible. There was no joy for her pregnancy. Looy stood up with his plate and said, "I'm heading to Rob's house." They had never talked about Looy's child; Lila reflected later that the Slabacks handled the worst things by pretending they never happened. They heard the back door swing open and shut. Lila felt a strong kick from the baby. What was she doing still living here with Veda and Red? She should be married by now, living her own life. Veda looked happy for the first time in weeks.  

A few days later, Lila decided to pay another visit to Myrtle. As soon as she opened the door Myrtle squealed, "Lila! You're just the person I wanted to see!" She walked in and saw that Myrtle had been baking again. The table was filled with pies and cookies. Myrtle said, "Why don't you go sit in the living room? The church is raising funds for the school, and I'm making some treats for the cakewalk&hellip;I'll be there in just a minute." Lila sat down without taking off her coat. She suddenly felt very tired from the walk to Myrtle's house. She was starting to doze off when Myrtle walked in with a tray of coffee and sugar cookies shaped like rabbits. "It looks like you could use a little coffee," she laughed. As she poured a cup and added cream and sugar, she said, "I have the best news for you, Lila&hellip;Herman is interested, and the family thinks you're adorable." 

"Really?" said Lila. "How do you know? Herman didn't say so much as two words to me." 

"He's just quiet like that," said Myrtle. "He told John, who told Viola, that he doesn't mind you being pregnant. He would consider the baby his own. He thinks you're beautiful, and his mother and sisters think you would be a good match. I do too." 

Lila wasn't sure about it being a good match---he was much older, had never lived in the city, and seemed even more boring than Earl---but where else was she going find someone to marry?  

The family wanted her to visit again for Easter. This time, Herman drove to La Crosse to pick her up. Veda and Red were getting ready for church when he knocked on their door. From the bathroom, Lila heard Red say, "Can I help you?" 

"Yes, I'm here to pick up Lila." 

Lila had not told them about Herman or even about her first visit to West Salem. She had told them she was visiting with Myrtle that day. Red stood at the door in shock. Lila popped her head out of the bathroom and said, "I'll be with you in a minute." Veda stepped out of the bedroom with David in her arms. They stared as Lila put on her shoes and coat. "I'll be back this evening," she said as she walked to the door. Herman was wearing gray trousers, a light blue button-down shirt, and a gray sweater vest. He had shaved, and his hair was neatly combed. He smiled shyly when he saw Lila. This time, he smelled like Ivory soap. They walked to the truck and Herman opened the passenger door. Lila did not look back; she would deal with Veda and Red later.  

The drive to West Salem was very quiet. Lila tried to get a conversation going. The snow was starting to melt. "It looks like spring is finally starting." 

"Yes," said Herman. "Soon it will be calving season." 

"That must be a busy time of the year for you." 

He nodded his head and said, "Yes, indeed." 

She wanted to know so many things&hellip;what did Herman like to do for fun? Who were his friends? What did he think about getting married? She could keep a conversation going with another person but was never very good at being the one who asked questions. Not knowing what else to say, she decided to be silent and look out the window. The trees were bare and there were patches of mud showing through the snow.  

As they approached Herman's parents' house, he said, "I need to do some things before dinner. I'll drop you off at the house, but I'll be back in a bit." 

"That's fine," said Lila, even though her stomach was churning. 

Gladys answered when she knocked on the door. The only other person at home was Alice, who was checking the oven. "Where is everyone?" said Lila. 

"Viola and John are picking up Myrtle, Helen, and Duane. Nora is doing something at church, and I think Dad, Ray, and Bobby are checking on the cows. Don't worry though! I guarantee that everyone will be here in time for the Easter ham." She helped Lila take off her coat and hung it on a peg by the front door. 

Alice said, "*Willkommen*! I'm so happy to see you again, dear. I have a present for you on the table&hellip;why don't you have a seat?" 

Lila noticed a small package wrapped in brown paper, and Gladys said, "Open it!" 

It was a tiny sweater and booties. "I'm so touched," said Lila softly. "Did you make these?" 

"Yes!" replied Alice. "I spin the wool and make clothes for all of my babies and grandbabies."  

As promised, the house was full by the time the meal was ready. The kids and some of the adults had to sit on the floor, but nobody seemed to mind. Herman pretended to be a horse, giving the kids little rides around the living room. He had changed his clothes to a heavily worn pair of denim overalls and a flannel shirt. The adults talked in small groups while they drank tea and ate the delicious apple streusel that Alice and Gladys had made. Lila learned that Helen was the same age as her older sister, Izro. She asked Lila what kind of work she did in the city; she and Gladys listened attentively as Lila described working at Carroll's. There was no drinking and no yelling&hellip;nobody stormed out in tears. It was a peaceful day.  

As Herman gave her a ride home that evening, Lila felt very content. As they reached the door on Kane Street, he leaned over and gave her a kiss on the forehead. "Goodnight," he said, and immediately turned to get in the truck. 

"Goodnight," said Lila quietly to his back.  

Veda was in the kitchen cleaning up from dinner. "Who is that man?" she asked with a flat tone. 

Lila hesitated for a moment. "His name is Herman. Myrtle introduced us&hellip;he's the older brother of her husband, Carl." 

"Is he your baby's father?" 

"No," said Lila. 

Veda sighed. "How long have you known him?" 

"Why does that matter? He wants to marry me." 

Veda was scrubbing a large pan beside the sink. They stood there in silence for what seemed like an hour. "You have made so many bad choices, Lila. I know I'm not your mother, but I have to tell you that I disapprove. That man is old enough to be your father. You hardly know him." 

Raising her voice, Lila said, "You were there when Aunt Hattie told me that I either had to get married or give the baby up for adoption, remember? I am not giving this baby away." 

Veda turned to look her in the eye. "So, you're going to make yet another bad decision? Two wrongs don't make a right." She paused, then said, "If you're going to get married, then you should let Aunt Hattie make a match. Find a man who lives in the city and will let you work outside the home if that's what you're so determined to do." 

Lila hissed in disgust and left the kitchen. She would rather die than have another conversation with Aunt Hattie.  

She walked to her bedroom and started piling her meager possessions on the bed: a stack of letters, the scarf from Lloyd, the cookie tin full of cash, a hairbrush, an apron, and the dresses she had purchased a few weeks earlier. There was a little more in her dresser, but she wouldn't be able to carry everything. She ripped her pillow out of its case and began stuffing it with the items she had selected.  

"What do you think you're doing?" Veda was standing in the doorway. 

"I'm going to Myrtle's house." 

"No, you're not," she demanded. "You need to stay here and talk about this." 

Harshly, Lila said, "Don't get in my way, Veda. I'm leaving. Nothing I do is ever good enough for this family." She walked to the closet by the front door and grabbed her coat and shoes. 

"Red, I need your help right now!" yelled Veda. 

He had fallen asleep putting David to bed and seemed confused. "What's going on?" he said with a yawn. 

"Lila is trying to leave. You need to stop her!" 

Gently, he put his hands on Veda's shoulders and said, "Let her go." 

As Veda started sobbing, Lila finished putting on her coat and shoes. She picked up the pillowcase and walked out the front door, letting the screen door slam behind her.  

## Notes

My description of Herman's clothing is based on family photographs and relevant issues of the Sears catalog---an important pre-Internet resource for rural households to buy ready-to-wear clothing and accessories. Some digitized issues are available on [archive.org](http://archive.org/). Ivory is a popular American brand of soap manufactured by Procter & Gamble.  

The Schneider-family Easter scene (both the meal and the time for playing and socializing) is based on my experiences with my father's family---another large family that happily crowded together for the holidays. I have fond memories of "horseback riding" with older relatives and giving younger children rides when I was a teenager. This is the reader's first insight into what Herman might be like as a parent.  

My best friend in high school had grandparents in southeast Wisconsin who shared stories and rhymes with their grandchildren in German.  

In this chapter, we get a deeper understanding of how Lila's choices and her family's choices have put her in a bad position. The Slabacks have demanded that she get married but have not considered how difficult it might be to find a match on short notice in the middle of a war. Veda is not necessarily wrong to think that Lila is making a bad choice, but what alternatives does Lila really have? Veda's husband, Red, is also forcing Veda to take sides (his side) by shaming Lila and holding Veda back.  

For more information, see @emmet1950a, @swasy2012a, and @zeitlin2013a.  