# Chapter Thirty-Six

Although Lila was never much of a reader, a few months later she was cleaning the house and noticed the *Wedding Embassy Yearbook* from Fields. As she leafed through it, she read the author's advice about "honeymoons": 

> If your honeymoon is to be spent inside U.S. borders, you will probably be driving or taking a train. Remember food and lodging if you drive. Railroad diners are not cheap. Figure such costs ahead of time. If you're lucky enough to be honeymooning on a cruise ship or a trip to foreign shores, you must figure in transportation for two from your hometown to New York or San Francisco and back. Things like that are easy to overlook.  

It was ridiculous advice. Nobody she knew had ever been to New York or San Francisco. She wasn't even sure what state San Francisco was in. 

For most of her life, Lila had been a listener. At school she listened to her teachers; at dinner she listened to her parents and older brothers. At work, her listening skills made her an excellent waitress. She never forgot an order. Living with Herman was different because he said so little. Lila found it unnerving. Desperate for someone to communicate with, she tried making friends with Evelyn. To her disappointment, she found that Evelyn was always on the go. As the president of the La Crosse County Homemakers Association (and mother of only one child), she was constantly gardening, sewing quilts, and making pies. A wall in their house was filled with ribbons that she had won at the county fair. Lila found Evelyn intimidating.  

She begged Herman to show her how to drive the truck. If she could drive, she could visit Alice and Gladys or go shopping with Myrtle in La Crosse. He promised that he would as soon as the snow was gone. That winter was one of the longest she had ever known. It should have been a happy time with a new baby and a new husband. Instead, she felt isolated, bored, and sad. Every day was basically the same. Herman would be gone by the time she woke up. He would come back with a fresh canister of milk, which they would drink with slices of bread from the day before. Sometimes there would be eggs, but the chickens did not lay as much in the winter. At first, she marveled over the different colors of the shells---white, light brown, darker brown with speckles, and pale green (the flock belonged to Evelyn, and she had many different breeds of chickens)---but after a few weeks, the novelty wore off. For lunch, she made grilled cheese. For dinner, she might open one of the jars. They had many dinners of oatmeal with fruit, milk, and blackstrap molasses. Myrtle Joyce was crawling all over the house. Lila missed listening to the radio and taking walks around La Crosse. She could walk down the road as much as she liked (and often did), but there was so little to see&hellip;just endless farmhouses and empty fields.  

On Sundays, they went to church with Vilas and Evelyn. It was a one-room Lutheran church on Gills Coulee Road. Most of the congregants had grown up together. As Lila later confessed to Myrtle, she stood out like a sore thumb. She didn't know the words to the service. She didn't know any of the songs. Some churches had books to help people follow along with the service, but this one did not. There was no need since they knew what to do.  

After the first week, the pastor told her that if she wanted to join everyone for Holy Communion, she would need to take confirmation classes. The thought filled Lila with dread. She had never been a good student. So, every two weeks when it was time for communion, she stayed in her pew, held the baby, and tried to make herself inconspicuous. She noticed that the other mothers with small children would pass them around so everyone could take turns going up to the altar, but nobody offered to hold Myrtle Joyce. Was it because she was not Lutheran or because they questioned whether Herman was the father? Lila had no idea.  

Since it was easily her best outfit, she wore her wedding dress every Sunday to church. Other young women did the same thing, but it was making Lila feel extra self-conscious. She was losing weight from the pregnancy and the dress was growing more and more loose every week. Lila did her best to take it in without a sewing machine, but she was hardly a professional seamstress. She was sure that everyone could tell and was silently evaluating her. In February, Lila stopped losing weight; she was pregnant again. Her first thought was how glad she was that she could stop fussing with the dress.   

Herman was thrilled by the news that she was expecting. One muddy day in April she took a walk with Myrtle Joyce. Evelyn was outside feeding the chickens and asked where Lila was planning to deliver the baby. "I suppose with Herman's mother in West Salem. That's where Myrtle Joyce was born." Evelyn paused with her hand in the pail of grain. "It's not safe to give birth at home&hellip;do you know how many women die of infections? You really should go to the hospital." Lila quickly put the conversation out of her mind, but Evelyn did not.  

A few weeks later, Herman asked Lila if she wanted to stay in La Crosse until the baby was born. Evelyn had pressured her husband into talking with Herman. 

"I could stay with Myrtle if she's willing." 

Herman paused to think. "Carl is coming home from Europe soon. What about your family?" 

Lila relished the thought of spending a little time in La Crosse, but her heart sank when he mentioned her family. Who was she supposed to stay with? Veda and Red? Lyle and Allene? For days, the possibilities tumbled through her mind. She was so distracted that one evening she accidentally burned the potatoes. She burst into tears, but Herman said nothing. His silence confused her. Did he not care about dinner? Did he not care about her? She wished that he would yell or slam the door. Anything would be better than silence.  

It was calving season and Herman was even busier than usual. Myrtle was pulling herself up on the furniture and shuffling around the room. The trees had come back to life, but Lila was feeling increasingly lifeless. One day blended into another. There was no friendship, no laughter, no radio, no movies. It was just endless work. Endless boredom. What was the point of washing the dishes or making another loaf of bread when she would just do the same thing the next day and the day after that? There was no end in sight. She was so tired of drawing water and waiting for it to boil. She was tired of cooking food that she barely felt like eating.  

## Notes

At the time of the 1940 census, Herman was working as a "hired hand" for Vilas and Evelyn Young on a farm near Hamilton, Wisconsin (population 1,342). From archival newspapers, I learned that they were quite a busy and impressive couple. Vilas had finished high school and enjoyed breeding cattle for show; he was a long-time judge of livestock at the La Crosse County Fair. Evelyn had attended college for two years and served as president of the La Crosse County Homemakers Association. As a highly educated woman, she likely would have been exposed to consumer trends like medicalized childbirth. I don't know if she influenced Lila, but I do know that Lila's second child was born in a hospital and not at home. The time she spent in the city preparing for and recovering from the birth would have changed her relationship with her first child and husband---unintended collateral damage, even if the birth was physically safer.

In rural areas (even today), churches can be wonderful places to connect and gain support. There was just one problem for Lila: she didn't know how to fit in. Having grown up in a non-religious family, she didn't know any of the songs, rituals, or rules. She probably felt self-conscious about being an outsider with a newborn of questionable status. It would have been easy for her to feel judged and "take things the wrong way," even if that was not the intent of the other churchgoers. Herman knew what to do in church, but (even if he was willing to teach Lila) many churches are segregated by gender in their activities. This chapter draws on my own experience of fitting into a religious community that is completely different from the one where I grew up.

For more information, see @goldstein2012a, @mullen2017a, and @devries2001a.  
