# Chapter Three

Shortly after they arrived in La Crosse, Uncle Frank and Aunt Hattie took the family to Grandad Bluff for a picnic. There was a park at the top with a magnificent view of the city. Lila had met Uncle Frank the day he picked them up from the train station, but it was her first time meeting Aunt Hattie and her cousins, Kenneth and Lloyd. Hattie was taller than her mother and older too---more like a grandmother than an aunt. She was wearing a light blue dress with short sleeves, a long string of beads, and a matching hat with a darker ribbon. Lila didn't mind when Aunt Hattie leaned down to give her a little hug; her dress was soft, and she smelled like flowers. (That night, her mother made a comment about the short length of Hattie's dress and how scandalous it was for a woman her age to dress that way.)  

Her cousin Lloyd was seventeen---almost the same age as her brother, Lyle, except that he was the youngest in the family. He had wild black hair and dark eyes with a look of mischief. Lila heard her uncle say that Lloyd had left school and was training to be a cabinet maker; maybe he could work for John. Lila felt a mixture of excitement and nervousness around Lloyd. Her own brothers ignored her most of the time, but Lloyd did not. They played a thrilling game where Lloyd held her by the feet and spun her around in a tight circle with her arms and hair flying out. Veda didn't want to give it a try; she said just watching made her feel dizzy. Lila and Earl took turns until Aunt Hattie said sternly, "That's enough now."  

Lila, Izro, and Aunt Hattie went into the kitchen to finish preparing the lunch. The night before, Izro had baked several loaves of bread and pound cake. They put some in a basket along with a container of butter, some jars of pickles (which Hazel had made from the tiny beets and cucumbers that were just starting to appear in their garden), a big block of cheese, a sack of fresh peas, and two jars of strawberry jam. They also added a knife to cut the bread and cheese, a cutting board, cups for water, and some plates and silverware. Lila's mother commented that the younger children would not need plates; they could hold their sandwiches and wander off to play. Lila thought that was a good plan; maybe she wouldn't have to eat the peas. She didn't really like them, but children had to eat whatever food they were given. It was a rule.  

When the picnic basket was ready, the group filed out the front door. They would walk together to the nearest streetcar line and then ride the rest of the way. Lila's father carried Earl on his shoulders. Although she knew it was wrong, Lila felt a bit jealous. She consoled herself by thinking, "At least I'm old enough to walk on my own. I don't need to be carried." Before she knew it, they had reached the first stop on the streetcar. It was five cents to ride. Uncle Frank paid for the tickets. The first streetcar took them past Frank and Hattie's house (Lloyd pointed it out to his cousins). When they reached downtown, they switched to another streetcar that would take them down Main Street and up the hill, close to the top of the bluff. Built on a plain next to the Mississippi River, most of the city was flat. Although the bluffs on the other side of the river went all the way to the shore (which made it impossible to farm and difficult to build houses), Grandad Bluff was two miles east of the river. In the summer, it was popular for families to go hiking and take picnics. Aunt Hattie had been there many times with her friends. When the line ended, it was just a short walk into the park.  

At the edge of the park, there was a wooden deck where you could go to get the best view. Lila went up to the railing, but Veda shook her head and refused, saying that it was "too scary." They were high above the city. Lila wondered if she could spot their house. She found the bridge that went over the river and was looking around trying to find their neighborhood when suddenly she heard, "Lloyd Spencer Slaback, you get away from there this instant!" Aunt Hattie was furious. Instead of staying on the deck, Lloyd was going around the railing to the very edge of the cliff. Lloyd laughed and said, "I was just trying to have fun." Lila felt sick to her stomach. It made her nervous for Lloyd: nervous that he could fall, but also worried about what Uncle Frank would do to him once they got home. If her brothers behaved that way, her father would have hit them with a belt. Aunt Hattie went back to talking with Lila's parents like nothing was wrong, but Lila wasn't able to eat much when it was time for lunch.  

## Notes

Before I started this project, I had never heard of Uncle Frank and Aunt Hattie. From census records, I learned that Hattie was originally from Michigan. Her father served in the Civil War; after the war, he moved the family from Michigan to Wisconsin. Hattie married when she was only fifteen years old and had two children with her first husband, Frank Udell, before he died in 1899. In 1902, she married Frank Slaback, who was 35 years old. It was his first marriage; I imagine the Slaback family had given up hope that he would ever get married.  

For three years, Hattie lived as a single mother. In the 1900 census she was listed as "head of household." She and Frank Slaback had three more children and moved to La Crosse shortly before World War I when Hattie was approximately 40 years old. She was working outside of the home and had her own listing in the phone directory. For the time, this was an astonishing amount of independence. Frank was also working at the La Crosse Rubber Mills; having two incomes would have lifted the family into the middle class, but I imagine that Aunt Hattie was regarded with intense suspicion by more conservative members of the Slaback family.  

Until the 1940s, Hattie Slaback was the only member of the family listed in the society pages of the newspaper. Fortunately for me, Slaback is an uncommon name, so it was not too difficult to sort through historic newspapers and find mentions of the family.  

This chapter helps readers understand the visual landscape of La Crosse. As a child, I visited all the places in this book, including Grandad Bluff. My cousin, Paul, was a teenager at the time; he did exactly what Aunt Hattie scolded Lloyd for doing. The foods that they took on the picnic are the kinds of things that would have been available in late spring for a working-class family with a backyard garden.  

My parents were both middle children in large families, so I grew up with many cousins. It was a thrill when the older cousins would play with me or let me tag along on their adventures. The activity of spinning in a circle (or being spun)---often to the point of dizziness---was something I did many times as a child. I spent a lot of time outdoors, regardless of the weather.   

For more information, see @morser2003a, @Barillas2006a, @nolen1911a, and Guide to the Mississippi Valley Public Service Company Records [-@mississippi1914a].  
