# Chapter Twenty-Three

True to his word, it was not long before Lloyd returned. One day Lila was walking to her new job (she had answered an ad looking for a "girl for general housework"), and there he was, perched on the edge of a stone wall, smoking a cigarette. It was October and the trees were flush with orange and yellow leaves. One leaf had fallen on Lloyd's head, and Lila playfully brushed it off. 

"Hey, that was my hat," said Lloyd. They both laughed. "What do you say we go to my place?" 

Lila was curious to see where Lloyd was living but said, "Mrs. Davis will fire me for sure if I'm late for work again." 

With a grin, he replied, "I'll be waiting when you finish." 

For several days, Lloyd waited for Lila until she finished work. All she wanted to do was walk home, eat dinner, and get some sleep, but Lila appreciated having someone to walk with. Lloyd treated her like a real adult and told the funniest jokes, although his language would have made most women blush (even most men). Lila had never done anything so exciting and dangerous. Spending time with Lloyd was her first major act of rebellion against her parents and Aunt Hattie. She decided that on Saturday she would go with Lloyd to see his place; she could tell her parents that she had been at the movies. Lloyd gave a cowboy "Yahoo!" when she told him, and he practically skipped all the way to Rose Street. 

As they approached the boarding house, Lloyd said, "When we go in, just follow me and don't talk to anyone." It was dim and chilly inside. There were mailboxes and a small desk near the front door. "Good, the desk is empty tonight. I swear that woman thinks we're just a bunch of good-for-nothing children&hellip;" Lloyd took Lila's hand and led her towards a flight of stairs. As they went upstairs and approached a door in the middle of the hallway, he pulled a key out of his coat pocket. "This is the one!" Lila was not expecting much, but Lloyd's room was worse than she had imagined. The floor and walls were bare, and the room was just barely large enough for Lloyd's bed; in the corner, there was a pile of laundry and some empty bottles. His bed was not made, and it was loosely covered with a ragged gray blanket. Lila could hear someone moaning in the next room. He shut the door and hung his coat on a big nail. "I know it's not much, but the view sure improved when you walked in." The condition of the building and its occupants made Lila feel sick to her stomach, but she tried not to show it. She was an adult now.  

Lloyd slipped off her coat and laid it over the edge of the bed. It was navy blue wool, but in the dim light it looked black; without her coat, it was quite chilly in Lloyd's room. 

"Where do you go to the bathroom?" 

"Oh&hellip;just down the hall. Sometimes when I'm too lazy, I piss in one of those bottles." 

Lila was imagining what it would be like to piss in a bottle (being a woman, it was something she had never considered) when Lloyd put his arm around her waist. Although he smelled like cigarettes, his body was warm and reassuring. She had never been so close to a man who was not her father or brother. Lloyd said, "I'll try not to hurt you." For the first time, Lila wondered what Lloyd had in mind---it was clearly not just a tour of his place. He put his hand on her breast and gently pushed her backward on the bed. Lila immediately realized that this would be her first sexual experience. She had heard her brothers whispering about it with their friends, but she felt very unprepared. Also, Lloyd was her cousin. Everyone knew that cousins were not supposed to do this kind of thing. She uttered, "Lloyd, I don't&hellip;" but Lloyd whispered, "Don't worry beautiful, I'll take good care of you." As his breathing grew louder and faster, she was surprised to find that hers was too. It was so painful that first time but thrilling in a way that she had never experienced before. Lloyd was clearly enjoying it. 

When Lloyd finished, there was a pool of blood on the sheets. Lila was horrified. "I'm so sorry, it must be that time of the month!" 

Lloyd chuckled and said, "That's normal for your first time&hellip;don't worry about it." 

Although she knew the room was nearly bare, she couldn't help looking around for something to use as a washtub. She knew that if the blood was allowed to dry it would be nearly impossible to get the blanket clean again, even with bleach. It was the kind of thing that would make her mother furious. Lloyd must have noticed her look of rising panic. As she buttoned the front of her dress, Lloyd put his hands on her waist and said, "It's OK&hellip;Lila&hellip;don't worry about it." A tear spilled and rolled down her cheek. She felt like a child for crying, but she couldn't help it. Lloyd gave her a hug and said, "I'll walk you home."  

For several weeks, Lloyd was waiting for her nearly every day. One day he surprised her with a beautiful scarf. It was so soft---pink, with red roses in the center. Lila had never owned anything so gorgeous, but she didn't ask where it had come from. Lloyd had secrets. To keep her mother from noticing, she hid the scarf under her mattress. Another time, he gave her a bouquet of real roses. The smell was divine, and the petals felt like heavy silk, but Lila giggled, "What am I supposed to do with these?" On the way back to her neighborhood, they took a stroll through Oak Lawn cemetery and laid the roses on Norma Jean's grave. 

One night Lloyd said, "You're the best thing that ever happened to me, Lila. I wish we could be together like a real married couple." Lila was ambivalent. She had grown very attached to Lloyd, but did she really want to get married? She had stumbled into a relationship that was starting to seem like an ideal: affectionate and fun, but with no strings attached. One of the best things about being with Lloyd was that they could never get married. As much as she wanted to be an adult (and she was), the thought of starting a family and becoming a housewife filled her with dread. She never dared to ask him if he wanted to get married or what he thought marriage would be like. It was not a relationship that involved deep discussion.  

## Notes

For this chapter, I scoured classified ads in the *La Crosse Tribune* to see what kinds of jobs were available to young women in 1941. Lila was getting too old to work as a child minder, but she did not have any special qualifications or training. The most common advertisements were for housekeepers (domestic servants), both part-time and full-time. Although many households in major cities like Boston, Philadelphia, and Chicago were hiring Black women by the 1930s and 1940s, La Crosse was a sundown town. Regardless of race, the pay was extremely low because domestic servants were excluded from the Fair Labor Standards Act of 1938.

As an alcoholic and recently released prisoner, Lloyd's options for housing would have been extremely limited. I have no idea where he lived when he was not in prison, but he might have lived in a boarding house or a halfway house. Although marriages between cousins are allowed or even encouraged in some countries, they are generally illegal in the United States.  

For more information, see @kearns1999a, @loewen2018a, @ottenheimer1996a, and @palmer2010a.  