# Chapter Twenty-Seven

One day Lila went to work and was shocked when a man answered the door. "Can I help you?" he said. 

"Yes, I'm here to clean for Mrs. Davis&hellip;is she in?" 

The man looked her up and down and said brusquely, "My mother has become very ill. The doctors are not expecting her to survive much longer&hellip;your services are no longer needed here." He shut the door in her face before she could respond. It was the end of the week, and Mrs. Davis was supposed to pay her the next day. She knocked on the door again, but the man didn't answer.  

Veda had relented on telling Lila to go to church but did ask her to "set a good example for Looy." On the occasions when she went to mass, Lila would inevitably look around at the other parishioners and think, "Is this really my life?" It was so boring. Lila could have found another cleaning job but decided that she needed something more exciting. With the last bit of money she had earned by working for Mrs. Davis, she took a streetcar downtown to purchase a dress and a new pair of shoes. Her usual "housedress and apron" was good enough for cleaning, but it was not going to help her land a job as a waitress. With the war going on, many young women were working as waitresses; there weren't enough men to fill all of the jobs and it was becoming much more socially acceptable. Lila had already stopped at five places to inquire if they were hiring, but they all said something like, "Sure, leave your phone number and we'll give you a call." Lila didn't have a phone or a phone number.  

The first place she went to look for a dress was Doerflingers, but she felt so conspicuous. She walked up the stairs to avoid the elevator man. When the sales staff asked if she would like any help, she politely said, "No thank you, I'm just looking." She noticed that two of the clerks were engaged in a quiet conversation. Were they talking about her? After a few minutes, she left and walked down Main Street. It was her first time wandering alone downtown and there were so many shops. Shops for shoes. Shops for jewelry. Shops just for flowers.  

At the end of the block was "the five-and-dime," F.W. Woolworth. Lila pushed open the door and immediately felt better. The lights were bright and cheerful, and the store was full of people of all ages---regular people like her, not rich people. Lila walked past the lunch counter near the front. Signs informed her that "Ladies Clothing" was on the second floor. As she began trying on the dresses, Lila was relieved to find that she had no trouble fitting into them. It was very different from her first experience shopping with Aunt Hattie. After some consideration, she decided to buy a knee-length, navy blue dress with white trim around the collar and a new pair of pumps. Food was being rationed, but clothes and shoes were not. The total cost was eight dollars and forty-five cents. Lila was not used to spending that kind of money, but the next day when she put on the outfit, Veda said, "Wow, Lila! You look stunning!" It was a good feeling. At the first restaurant she walked into with her new outfit, the manager offered her a job on the spot.  

Lila could hardly believe it, but the pay at Carroll's was more than double what she had been earning from Mrs. Davis. Sometimes she helped with a little cleaning (sweeping floors or washing the dishes) but overall, it was much easier and more fun being a waitress. Lila enjoyed talking with the customers and making suggestions. Often it was just about the weather ("Boy it sure is a nippy one today!"), but sometimes they asked, "What is your favorite?" or "What do you think about the soup of the day?" It was a joy for someone who loved to eat. Lila often tried the specials since the meals were free for employees. Although she had to wear a uniform---a light blue, button-down dress with a white apron and a little white cap---the owner gave everyone on staff extra money to purchase their uniforms from a particular shop downtown. It saved money and made it easy to get dressed for work. Lila felt proud to be part of the Carroll's team. She even won the award for "Employee of the Month" in October.  

After 6 p.m., the restaurant turned into a bar. In the back of the building there was a dance hall and a small bowling alley. It was always packed, especially on the weekends. Not far from La Crosse there was a large army base---Camp McCoy. Lila had heard that recruits were being sent there for training before heading off to war. La Crosse was the place where they went to get drunk. As she walked to and from work, Lila noticed that the number of bars in La Crosse was increasing rapidly: Killian's, Fish's, the Cavalier Lounge&hellip;even Cecil was talking about opening a bar. One day the manager at Carroll's asked if she could stay for a few minutes after work. She worried all day that she had done something wrong and was about to be fired, so she was relieved when the manager said, "Could you start working in the evening? You would make a great cocktail waitress, Lila." It was flattering to think that she might be "great" at something. Without thinking she replied, "Yes, I'm willing to work in the evening." She didn't know how she was going to justify the late hours (or working in a bar) to Veda and Red, but why not?
	
The uniform for evening was different---a short, red dress with a matching shrug tied in a bow to give a glimpse of cleavage, and strappy, black high heels. No apron, no pockets, no pads of paper for writing down orders. It was very glamorous, but in the beginning, Lila was nervous. There were so many things to learn, like the names of all the cocktails. What on earth was a pink squirrel? She laughed the first time someone ordered one. 

The first weekend she worked at the bar, Lila told Veda that she was going to the movies for a double feature. 

Veda replied, "Oh that sounds like fun! Have a good time." 

Lila carried her uniform in a grocery sack and put it on right before her shift. One of the other waitresses noticed her changing in the tiny women's bathroom. While touching up her make-up, she said, "You look great&hellip;just try to have a good time. Act like you're at a party and not at work." Lila smiled but didn't respond. She was too nervous. She hoped that nobody would notice when she returned home at 3 a.m. For a few months, it seemed like nobody did.  

## Notes 

One of the difficulties of working-class life is lack of awareness about laws and the legal system. Refusing to pay for labor that has already been performed is illegal, but what was Lila going to do about it? Probably nothing.  

I remember going to the "five and dime" when I was a child. It was unpretentious and a place where my mother felt comfortable. She bought my first purse at F.W. Woolworth's, although I rarely carried it and wasn't sure I needed one. I wasn't very ladylike. During the war, uniforms were considered "utility" clothing and would have been more affordable than regular clothing.  

Carroll's was a real restaurant in La Crosse in the 1940s. I used historic newspapers to gather the names of bars and restaurants that were popular in La Crosse during Lila's adulthood. Towards the end of the writing process, I had a great conversation with a distant cousin (Linda Wood) about her mother's experience as a young woman in West Salem. She often went to parties at Fort McCoy and married a veteran.  

For more information, see @cobble1992a, @fournier2008a, @plunkett-powell2014a, and @joselit2014a.  