# Chapter Twenty-Six

Veda's baby, whom they named David, was born just a few days after the new house was finished. Lila thought her parents might wait a few weeks before moving so Hazel could help Veda and they could spend a little time with their new grandchild, but Hazel was clearly anxious to get going. Since there was no high school near their new house, and it was too far to drive to La Crosse or Onalaska on a daily basis, the family had decided that Looy would stay behind and live with Veda and Red. As they all said their goodbyes at the curb, Veda promised that they would be up for a visit soon. And that was that. Lila had helped pack their belongings in the back of Theron's truck; on the first day of summer, they drove off.  

Although Lila had been in the house on Kane Street plenty of times without her parents, it was strange knowing that they would no longer be living there. They had all known that this day was coming, but Red and Veda seemed to be in shock. Were they really the owners of this house now? Veda went back to taking care of the baby, and Red went back to work. Veda was not as demanding as Hazel. Lila was glad that she had not quit her job after all.  

One night at dinner a few weeks after their parents had moved, Veda announced that it was time for all of them to start going to church on a regular basis. David should be baptized as soon as possible; it would be a blessing for them to go to confession on Saturdays and mass on Sundays. Lila inwardly groaned---the Slabacks were not churchgoers. Why did Veda have to be in charge? 

Looy said, "Do I really have to go?" 

Without hesitation, Red calmly answered, "As long as you're living in my house, yes you do."  

That summer Lila finally received a letter from Earl, but it was not the kind of news she had been expecting.  

> August 2, 1942
>
> Dear Lila,
>
> I should have written to you earlier, but I wasn't sure what to say. When I tried to join the Navy, they told me I had a heart murmur, so I'm "not eligible" to join the service. Can you believe that? I thought they would take anyone right now.  
>
> I've been living in Illinois and working as a truck driver. There's no easy way to say this, but I've met someone else. Her name is Aline. We got married, and we're planning to move to La Crosse in a few months. I didn't want you to find out from someone else. 
>
> I'm sorry that things didn't work out between us. You seem like a nice girl. Please keep the ring. You can sell it if you need to.  
>
> Sincerely, Earl  

Lila knew the family would be upset, but she was relieved. She had never agreed to get married and now she didn't have to say yes or no. The wedding was off. She tucked the letter under her mattress and decided to think about how she was going to tell everyone. Would her mother and Aunt Hattie start pressuring her again? She was grateful that she had been the one who checked the mail that day. Nobody else knew of the letter's existence.  

After a few weeks, she decided to break the news to Veda. It was Lila's day off and Red was at work. They were sitting in the front room watching the baby as Veda worked on knitting him a sweater. "Veda, I have something to tell you&hellip;I'll be right back." She retrieved the letter from Earl, which was looking rather crumpled after all of the times Lila had read it, and stuffed it back under her mattress. "I need your advice about something. I want you to listen and then take a moment to think before you say anything." Veda stopped knitting as Lila read the letter out loud. 

She stared at Lila and opened her mouth, but for a few moments, nothing came out. "What are you going to tell mom and dad?" Veda asked. 

Lila said, "I have no idea! It's not my fault that Earl married someone else. It wasn't even my idea to get engaged in the first place." 

Veda said, "Calm down, Lila, of course you wanted to marry Earl. Don't exaggerate. I just don't know how you're going to tell Mom or find another man to marry. You should tell Aunt Hattie." 

Lila was shocked. She didn't think Veda was trying to be mean, but was that really her best advice? Lila said, "I need to wash the dishes now," and walked away.  

Telling Myrtle was not much better. She burst into tears like Earl had died. Lila didn't tell her that she had never wanted to marry Earl. After Veda's reaction, she had decided that it was probably best to keep that information to herself. Through her tears, Myrtle said, "I don't know why I'm the one who's crying&hellip;I should be comforting you." Lila gave her a little hug. Why did this have to be so hard? She wasn't even sure she wanted to get married, but everyone was acting like her life was over unless she could get engaged again. It seemed to be the only thing anyone cared about. After a few minutes, Myrtle went into the kitchen for another plate of cookies. "We just need to find you another man. That will make everything better. In a few months, we'll say, 'Earl who?' and laugh about the whole thing!" Lila doubted that was true.  

With the wedding off and Lloyd in prison, Lila decided to become a regular at the movie theater. The price of tickets had increased by three cents, but it was bliss. No chores, no talk of "finding a man," just a box of popcorn and two hours of escape. She skipped *I Married a Witch* based on the title but watched everything else---war movies, cartoons (*Bambi* was popular that fall), science fiction, mysteries, dramas---she enjoyed them all. The comedies were her favorite. The first time she saw Claudette Colbert was that year in *The Palm Beach Story*. What a smart and funny woman! When her husband couldn't provide for her, she didn't sit around moping about it. She took matters into her own hands and left to find an exciting new life. Lila was still wearing the ring from Earl, but she took it off that night.

## Notes 

When my friends started having babies, I was fascinated (and frankly, a bit jealous) at how some grandmothers joyfully spent weeks or even months helping their daughters and grandchildren. I did not have that kind of support. My mother and her mother did not either. Lila probably came from a long line of mothers who were neglected and marginalized by society.  

The 1943 phonebook lists John and Hazel Slaback as living on S. Salem Rd. Cecil and Gladys were living at the original Slaback house on 2211 Kane Street. I don't know who inherited the house directly, but it stayed in the Slaback family for some time. I have proof (such as marriage records from the state of Wisconsin) that Earl married a different woman, but I'm not sure how his engagement with Lila fell apart. 

In this chapter, Veda is establishing a life for herself as a Catholic and stay-at-home mother. It is not the kind of life Lila wants for herself. This is how siblings start to drift apart as adults---not because they don't care about one another, but because they simply have different interests and different visions for living a good life. I don't know if Lila was the avid moviegoer I make her out to be in this book, but I imagine how films would have presented options (like divorce) that older members of the Slaback family were unaware of. The usefulness of their advice was probably very limited at times.

For more information, see @greif2015a, @illouz2023a, and @pfeifer2014a.  