# Chapter Twenty

Not long after the dinner with Red, Lyle announced that he was getting married. Lyle and Allene met through Aunt Hattie; her daughter, Ruby, knew the bride's family from church. Since Allene's family lived in Minnesota, the wedding would be held across the river in Winona. With hardly a pause in the dinner conversation, their father said, "Congratulations, Son, it's about time." Lyle was twenty-six and had dated so many women; the whole family had started to wonder if he would ever settle down. Veda said she would ask for the day off from work. 

On the day of the wedding, the weather was gorgeous. It had been a cool spring, but it was warm and sunny on that particular day in June. The apple and plum trees were in full bloom and the farmers were busy planting their fields. Everything smelled so fresh and green. Lila, Veda, and Looy rode to the wedding with Cecil and Gladys; their parents were riding with Uncle Frank and Aunt Hattie. Lila smiled all the way to Winona, basking in the sun; it was a relief to be away from the adults. With a little of the money she had earned by childminding, Lila had hired one of the neighbors to make her a dress. She had slimmed down as a teenager and loved how the light green dress fit closely around her waist and hips. When she tried it on, the neighbor told her, "You look so glamorous!" A few days before the wedding, Lila had set her hair into a finger wave and shined her shoes. That morning, she picked a peony bud and pinned it near her left shoulder. For the first time she could remember, she felt truly beautiful. She wished she could wear lipstick but knew her parents wouldn't approve. Lipstick was for whores. 

Allene was six years younger than Lyle, but hardly a child bride. She wore a dress that had been passed down through her family. It was white with beautiful panels of handmade lace and embroidery around the bodice and hem. She also wore a crown of flowers instead of a veil. The effect was glorious; Lyle looked like he was ready to burst with joy and desire. The church was full, mostly with members of the bride's family. Lloyd was still in prison, but Lila thought of him. What was it like in Stillwater? Lila wondered if he would return to La Crosse and if the family would ever forgive him. She felt sorry for Lloyd. He had made some mistakes, but the punishment had been very harsh.  

When Lyle and Allene said their vows, Veda cried silently into her handkerchief. Lila gave her a nudge to say, "This isn't a funeral&hellip;" and Veda whispered, "I'm just so happy for them." When the ceremony was finished, everyone walked across the street to another building. It was filled with tables and chairs and there was a long table piled with food: big platters of ham and beef roast, spring vegetables, loaves of bread, big pitchers of beer, and the largest cake that Lila had ever seen. Lyle had just married into a family of German-Hungarian farmers. As Lila would soon learn, there was nothing they loved more than a beautiful wedding celebration with good food, good beer, and good music. 

The bride's father thanked everyone for coming to the wedding and wished the couple many years of health and happiness. By the time everyone had a plate of food, the musicians were warming up for a lively night of dancing. Lila had a glass of beer with her lunch and was already feeling very relaxed. One of Allene's cousins asked her to dance, and she eagerly agreed. She had no idea what she was doing but quickly realized that it didn't matter. The group was moving in a circle and would just pull her back and forth; it was exhilarating. All the younger people were dancing---even some of the older people---and the time flew by. 

It was very late when they left the wedding. Cecil and Gladys were also having a good time. It was like the wedding they wanted but didn't get to have. When Lila's parents left that afternoon with Uncle Frank and Aunt Hattie, they took Deanna with them so they wouldn't have to worry about the baby. Aunt Hattie said she was "too old for this foolishness," but the young people should enjoy themselves. Lila had not expected to have such a taste of freedom. It made her feel temporarily sorry for disliking Aunt Hattie so much. Cecil had to stop drinking early so he would be sober enough to drive home, but they had a fantastic time celebrating. Lila could not remember a time when she had felt so happy. Between school and chores and childminding, it felt like all she ever did was work. 

When it was time for Lyle and Allene to leave and the bride tossed her bouquet into the crowd, Veda was the one who caught it. Lila squealed and said, "Your wedding must be next!"

## Notes

I found a record of Lyle Slaback's marriage license in a State of Minnesota database that is open to the public. My impression of Aunt Hattie is that she was the Slaback family matchmaker and "busybody," sometimes for good and sometimes not. Her daughter, Ruby, lived across the river in Winona, Minnesota, and was an active churchgoer; it seems likely to me that her connections led to this match between Lyle and Allene, who grew up in Minnesota.

I remember going to weddings as a child and what a rush of freedom it was to be in a roomful of joyful, drunken, distracted adults who would let you get away with almost anything (like eating all the sugar cubes or getting drunk for the first time). A good wedding reminds adults of their commitments to one another, but also happier, innocent times---for a little while, everything is right in the world. This feeling of euphoria is enhanced by vigorous dancing. (In Wisconsin, polka is a long-standing favorite.)

In this chapter, Lila is on the precipice of adulthood, getting a glimpse into her possible futures. So is Veda, who catches the bride's bouquet. Lila wonders about Lloyd who has been in prison for a while, missing out on happy times like family weddings. Her body is changing into a more adult (and slender) form; she feels beautiful in a new dress, paid for by her own hard work.  

For more information, see @bailey1989a, @march2015a, @mcbee2000a, and @wallace2004a.  
