# Chapter Twenty-Nine 

The manager at Carroll's was thrilled when Lila returned and announced that she was available to work again. Two of the waitresses had decided to join the WAVES^[The WAVES (Women Accepted for Volunteer Emergency Service) was a program established in 1942 that allowed women with a high school diploma to enlist in the US Navy. Since Lila had not graduated from high school, she was not eligible to join.], and they had been short-staffed. In very little time, Lila was back to her usual routine. There was no end in sight to the stream of soldiers moving through La Crosse. Lila had stopped trying to remember the names of her customers; even the "regulars" would be gone after a few weeks.  

The price for a movie was reduced on Tuesday evenings; one week Lila asked Myrtle if she would like to go. ("My treat," she said when Myrtle objected to the cost). They decided to watch the latest movie with Claudette Colbert, *So Proudly We Hail!* Lila assumed that it would be another comedy, but it was not. It was about women serving in the army as nurses and falling in love with the soldiers. Myrtle cried when one of the nurses was killed and said that the movie was "so romantic." On the way home she said that Carl was stationed in California; she wanted to take the train and go visit him, but women weren't allowed on the base. Lila wondered if that was the truth or if Carl had reasons for wanting Myrtle to stay home in Wisconsin. Working at Carroll's, she had observed that there was little difference in behavior between the soldiers who were married and those who were not. She wondered if she should tell Myrtle that she was being naïve but decided against it. She didn't want to hurt her feelings.  

The soldiers mostly went to the bars in groups. Every weekend, the city of La Crosse was like a giant party. They played darts and card games, smoked and drank, told jokes, and bragged about their exploits. One of the waitresses, a tall, glamorous blonde, openly relished having sex with them. Lila had never known a woman who was so open about it; she was like a movie star. Claire received more tips than anyone, but then one day she simply disappeared. Where had she gone? When Lila asked the manager, he brusquely told her, "Don't ask questions."  

Lila tried to memorize some of the jokes to share with Lloyd. One night, she noticed a soldier who was sitting by himself in the corner. He was older than usual and seemed to be lost in thought. When he nursed a single beer for more than two hours, Lila took him a fresh one and said, "There's plenty more where that came from." 

He smiled a bit and said, "Thanks&hellip;I don't know what I'm doing here." 

Lila had met plenty of soldiers who were homesick or nervous or just plain scared (not that they wanted to admit it), but this one&hellip;it was like he had come to the bar from a funeral. "You mean, you don't know why you came to Carroll's?" she said. 

The man chuckled. "No, I know why I came to this bar&hellip;I just don't know what I'm doing so far from California, getting ready to head off to war. This is not how I imagined my life would turn out." 

Lila sat down beside him; it couldn't hurt to give him a little extra attention. He had sandy hair and smelled like cigarettes and Old Spice.  

He started telling a story. "A few nights ago, it was time for lights out and the sergeant said, 'Men, I want you to look up into the sky and tell me what you see.' 

One person spoke up right away and said, 'Sir, I see millions of stars.' 

The sergeant replied, 'Alright. Now what do the stars tell you?' 

Someone on the other side of the room said, 'They tell me that I can always find my way home as long as I look for the north star.' 

Another said, 'They tell me that God exists and everything else is insignificant.' 

My bunkmate added, 'The stars tell me that the sky is clear tonight, and the weather will be good tomorrow.' 

It was a very somber mood. Then the sergeant barked, 'You're all wrong. If you can see the stars when you're in bed, then somebody stole your damn tent.'" 

Lila laughed out loud. He had told the joke with such a dry sense of humor; Lila didn't think it was a joke until the punchline. "You really got me there. My name is Lila, by the way." 

The man smiled and held out his hand, "Private Daniel Oxnard." 

A feeling like electricity rippled through her body when they touched. Lila said, "Well, I need to go back to work now, Daniel, but I'll bring you another drink. Compliments of the house."  

Daniel stayed for most of the night, but he slipped out before they had another chance to talk. It was a busy night and Lila had made over fifteen dollars in tips. Before leaving work, she slipped the five-dollar bills into her brassiere. (One of the other waitresses had told her, "A thief might take your purse, but the money will be safe if you keep it close.") By the time she returned to the neighborhood, the sun was peeking over the horizon. A few nights later, Daniel was back. As soon as she noticed him, Lila made a beeline for his table. "Welcome back, soldier. I wasn't expecting to see you again." 

Daniel replied, "Well, a bad penny always turns back up." 

Lila laughed, "I wouldn't say you're a bad penny. I'm glad you came back." 

He sat in the corner again and ordered a beer, but when Lila brought the drink to his table, he asked when her shift would be done. 

"3:00," she said, thinking how long it had been since someone offered to walk her home. Her shift flew by. She found Daniel standing in the parking lot, waiting and smoking a cigarette. 

He smiled and said, "Where to?" 

Carroll's was on French Island. There were many islands in the Mississippi, but this was the largest one in the area. Lila smiled back and said, "This way," pointing in the direction of the Clinton Street bridge.  

That day the weather was unusually warm for September. The cicadas were buzzing; it felt more like summer than fall. After they crossed the bridge, Daniel asked, "Can we walk by the river for a little while? I've never seen the Mississippi up close before. I feel like I'm in a Mark Twain novel." 

"Sure," said Lila. It was no special thrill for her to see the river, but she didn't mind taking a detour. When they got to the shoreline, she took off her shoes and put them in her handbag; it would be impossible to walk along the sand in heels.  

The moon was full that night, and the air was thick with humidity. Daniel said, "I was a truck driver back home&hellip;my family is in the sugar business." 

"Oh?" said Lila. "My oldest brother is a truck driver too. My family is in the plastering business." 

"Plastering like&hellip;the walls? Or getting plastered?" 

Lila laughed, "A little of both, I guess." How had he guessed about the drinking problems in her family? It was like he could read her mind. 

Soberly, Daniel said, "I'm a tank driver now. We got our marching orders this week; we're heading to Europe in a few days." 

Lila put her hand on his bicep. "I don't know what to say, but I hope you make it back." 

Daniel put his hands on her waist. "I want to make love to you Lila. You're so beautiful and I miss being with a woman." His hands were warm and gentle. It had been over a year since Lloyd was arrested. She leaned over and kissed Daniel. He untied the front of her dress, and they sank down into the sand. It was like being in a movie. Lila wanted to give him a happy memory; one last enjoyment before going off to war. It was so passionate and romantic. They could have been spotted by anyone passing by, but Lila did not care.  

## Notes

The last chapter of Part I is extremely fateful: Lila meets a funny, handsome soldier. He asks to walk her home (something Lloyd often did) and she accepts. Although she knows that not all soldiers are trustworthy, movies have primed her for the thrill of spontaneous "romance," like having sex on a moonlit beach with a soldier who is heading off to war.  

The timeline is accurate for the conception of Lila's first real-life child, Myrtle.  

For more information, see @bachner2008a, @glitre2013a, and @king2001a.  

