# Chapter Twenty-Two

Veda's wedding was held at Saint James Catholic Church, which was only one block away from the Riviera Theater; she had been taking classes there to get the dispensation. Aunt Hattie---who never missed an opportunity for a good spectacle---offered to take Veda shopping for a wedding dress. When Veda announced her offer, however, their mother's face darkened. "How dare that woman intrude&hellip;everyone knows that the mother of the bride is the one who should handle the dress and flowers." 

Veda said, "I'm so sorry! I'll tell her right away that you want to take care of it." 

The conflict added a sour note to the planning. Even on the day of the wedding, Hazel was unusually cold to Aunt Hattie. Veda was mortified. She wanted everyone to be happy. Although they could not afford much, Veda looked radiant. Thin, with gorgeous hair and a pale complexion, she would have looked just as beautiful in a flour sack. 

Lloyd had been released from prison, but he had not returned to La Crosse right away. To everyone's surprise (and Aunt Hattie's dismay), he turned up at Veda's wedding reception. Lila was eating when Lloyd crept up behind her and whispered, "Hey beautiful, where have you been all my life?" Lila blushed and turned to look at him. He was thinner than the last time she saw him (before he went to live in Winona) but still handsome. No other man had ever talked to her like Lloyd. She felt a rush of excitement. Lloyd asked if they could go somewhere to talk and she agreed. She pretended like she was getting up for a second helping and then snuck out the kitchen door. Lloyd suggested that they walk down to the river so he could have a cigarette. He offered one to Lila, who politely declined. 

As Lila had imagined, the last few years had been difficult for Lloyd. He talked about what it was like in prison: the mice, the terrible food, being cold all the time, the concrete walls and scratchy clothes infested with lice, and worst of all, never knowing what the guards or other prisoners might do. During his second year in prison his cellmate, Robert, was stabbed to death during an argument. Lloyd said he had forgiven the shop owner and the police and attorneys, but nobody would give him a fair shake at another job. What was he supposed to do with the rest of his life? Lila listened carefully. She couldn't do much to help Lloyd, but she could listen. She found it flattering that he trusted her. Lloyd's life was even worse than her own. 

Then he paused and said, "Enough about me&hellip;how has life been treating you, gorgeous? The boys must be flocking to your door by now." Lila blushed. She didn't realize that Lloyd was gauging her experience (or lack of experience) with men. It was so rare that anyone asked her, "How are you doing?" How was she supposed to respond? They had walked all the way to the river and were sitting on a large limestone rock near the Clinton Street bridge. They could hear the constant stream of cars and trucks driving past.  

Lila was still thinking of what to say when Lloyd leaned over and kissed her. It was her first time being kissed and she really didn't know what to think. Lloyd pulled back to see her expression and must have liked it because he leaned towards her again and gave her a longer kiss. His hands were warm on her cheeks. To her astonishment, she felt him reaching his tongue into her mouth. What in the world was going on? He pulled back again and smiled. "Now what was it you were saying?" Lila blushed. She truly had no idea what to say. Should she tell him about her mother's drinking problem or the endless years of chores&hellip;or how she had decided that it was time to drop out of school? Would he advise her to get married and stop being silly? She didn't think so, but she was feeling apprehensive about getting advice from the family, even from Lloyd. She held out her hand and said, "I guess we should walk back now."  

Two blocks from the church, Lloyd said he had to go. He was meeting up with some friends. "I'll look for you another day; don't worry," and with a smile, he turned. Lila waved. Aunt Hattie had noticed her absence and asked where she had been. 

"I just needed some fresh air, so I took a little walk." It was not entirely a lie. 

Aunt Hattie gave her a skeptical look and said, "You missed the serving of the cake." 

Thankfully, Allene came to her rescue and said, "There you are! Come dance with me. Lyle says that he's tired, but I'm just getting started." One of Red and Veda's co-workers was a fiddler, and he had agreed to gather a small band to play at the reception. It was turning into a lively evening.  

## Notes

I'm not sure what church Veda and Red attended, but Saint James was a real church located just one block away from the Riviera Theater. In my experience, weddings tend to draw out the best behavior from people, but also the worst behavior. It is not hard for me to imagine tension over who would pay for the critical pieces of a wedding, like the bride's dress. 

Like Lila, I received some inappropriate attention from male relatives when I was a teenager. Weddings are chaotic (especially receptions) so that gives predators unusual opportunities. I have no idea if Lloyd was a predator or not, but some family members were. My first "French kiss" was foisted on me by a relative who is no longer alive. He would have done more if I had not carefully avoided him for the rest of the event.  

During the Great Depression, many families in rural areas saved money by making clothing out of feed sacks and flour sacks, which were often printed with paper labels or ink that could easily be washed out. Lila might have seen flour sack dresses when visiting extended family.  

For more information, see @howard2008a, @leonard2019a, and @miller2007a.  
